ENVIRONMENT: "local"
SERVICE_NAME: "backend-portal"
SERVICE_VERSION: ""
GRACEFUL_WAIT_TIME: 300
SERVER_HOST: "0.0.0.0"
SERVER_PORT: "3000"
# Order by alphabetically
APP:
  PAGINATION_PER_PAGE: 20
  MAX_PAGINATION_PER_PAGE: 100
  BULK_DISBURSEMENT_EXPIRE_LOCK_MINUTE: 1440
  DISBURSEMENT_PROCESS_EXPIRE_LOCK_SECOND: 60
  MASKING_SENSITIVE_DATA: password,token,accessToken,otp,otpCode,refreshToken,X-EXTERNAL-ID,X-Internal-Service-Key,X-API-Key,X-Request-PIN,X-Access-Token,Authorization,secret-header,bankCardNo
  PDK_LOGGER_USED: ZAP # Oneof: ZAP or SLOGGER. Default: ZAP
  USE_OVER_FETCH_PAGINATION: false
  INITIAL_PAGE_WINDOW: 5
AUTO_SPLIT_PAYMENT:
  PROCESSOR_LIMIT_DEFAULT: 2000000000
CONDUCTOR:
  ADDRESS: http://localhost:8080
CARD_FUNDED_PAYOUT:
  EXPIRY_AFTER_MINUTES: 30
  PARTNER_PROCESSOR_LIMIT:
    MPGS: 20000000
    CYBS: 30000000
DATABASE:
  DIALECT: "mysql"
  HOST: "localhost"
  PORT: "3307"
  MAX_IDLE_CONNS: 10
  MAX_OPEN_CONNS: 50
  MAX_IDLE_TIME: 300
  MAX_LIFE_TIME: 3600
  SLAVE_HOST: "localhost"
  SLAVE_PORT: "3307"
REDIS:
  HOST: "localhost"
  PORT: "6380"
  CACHE_DB: 0
  MAX_RETRIES: 3
  MIN_RETRY_BACKOFF: 0 # Default is 8 milliseconds
  MAX_RETRY_BACKOFF: 0 # Default is 512 milliseconds
  DIAL_TIMEOUT: 15 # Default is 15 seconds
  READ_TIMEOUT: 15 # Default is 15 seconds
  WRITE_TIMEOUT: 15 # Default is 15 seconds
  POOL_SIZE: 25 # Default is 10 connections
  POOL_TIMEOUT: 30 # Default is 1 seconds
RABBITMQ:
  HOST: "localhost"
  PORT: "5673"
  HEARTBEAT_IN_SECONDS: 6
RABBITMQ_STREAM:
  HOST: "localhost"
  PORT: 5552
  VHOST: "cdc"
  HEARTBEAT_IN_SECONDS: 6
DICTIONARY:
  PATH: "docs/dictionary-i18n.json"
FDS:
  SCORE_THRESHOLD: 80
  TIMEOUT: 5000 # in ms
  BIN_LENGTH: 6
  FEATURES:
    PROOF_OF_PAYMENT:
      VELOCITY:
        ENABLED: true
        WINDOW:
          INTERVAL: 1
          UNIT: HOUR
        THRESHOLD:
          COUNT: 5
        ACTION: BLOCK

FEATURE_FLAG:
  LOG_LEVEL: INFO # DEBUG, INFO, WARN, ERROR
  POLLING_INTERVAL: 10
  FILE_FORMAT: "YAML"
  START_WITH_RETRIEVER_ERROR: false
  OFFLINE: false
  CONSUL_ADDR: ""
  CONSUL_CONFIG_PATH: "backend-portal:feature-flag"
  CONSUL_PAYMENT_IMAGES: "backend-portal/payment-images"
  CONSUL_PAYMENT_INSTRUCTIONS: "backend-portal/payment-instructions"
  CONSUL_APP_VERSION: "backend-portal/app-version"
  SLACK_WEBHOOK_URL: ""
  EXPORTER_SLACK_WEBHOOK_URL: ""
FRAUD_NET:
  BASE_URL: "https://30647.api-sandbox.fraud.net/"
SOKRATECH:
  BASE_URL: "https://api-sandbox.sokratech.io"
  WORKFLOW:
    PAYOUT_TRANSACTION_ID: ""
    PAYMENT_TRANSACTION_ID: ""
  TIMEOUT_SECONDS: 60
GCS:
  SERVICE_BUCKET_NAME: ""
  REPORTING_BUCKET_NAME: ""
  PROOF_OF_TRANSFER_FOLDER_NAME: "crm/transfers/images"
  TNC_DOCUMENT_FOLDER_NAME: "tnc-documents"
  MERCHANT_RESERVED_SHORT_NAME: "crm/merchants/reserved-short-names"
  MERCHANT_DOCUMENT_FOLDER_NAME: "merchants/documents"
  MERCHANT_LOGO_BUCKET_NAME: "stg-merchant-logo"
  INVESTIGATION_POP_FOLDER_NAME: "investigations"
HOST:
  STAGING: ""
  PRODUCTION: ""
HTTP_CLIENTS:
  MERCHANT_CALLBACK:
    DIAL_TIMEOUT: "30s"
    REQUEST_TIMEOUT: "120s"
    MAX_IDLE_CONNS: 100
    MAX_IDLE_CONNS_PER_HOST: 5
    IDLE_CONN_TIMEOUT: "50s"
    PROBE_INTERVAL: "10s"
    MAX_PROBES: 3
INVESTIGATION:
  MAX_FILE_SIZE_MB: 5
  ALLOWED_FILE_EXTS:
    - "png"
    - "jpg"
    - "jpeg"
    - "pdf"
MERCHANT_CALLBACK_TASK:
  # EXAMPLE_TASK_NAME:                  // Task Identifier
  #  BATCH_SIZE: 6                      // Number of tasks to be fetched in a single request. Set to -1 to disable the worker, or 0 to use the default value.
  #  POLLING_INTERVAL_DURATION: "200ms" // Delay time for the worker before polling the next tasks. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  #  POLLING_TIMEOUT_DURATION: "500ms"  // Max wait time for the worker while waiting to fetch the list of tasks (based on the batch size). Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  PREPARATION:
    BATCH_SIZE: 6
    POLLING_INTERVAL_DURATION: "50ms"
    POLLING_TIMEOUT_DURATION: "50ms"
  SEND_CALLBACK:
    BATCH_SIZE: 6
    POLLING_INTERVAL_DURATION: "50ms"
    POLLING_TIMEOUT_DURATION: "50ms"
  WRITE_CALLBACK_LOG:
    BATCH_SIZE: 6
    POLLING_INTERVAL_DURATION: "100ms"
    POLLING_TIMEOUT_DURATION: "100ms"
  WRITE_CALLBACK_METRIC:
    BATCH_SIZE: 6
    POLLING_INTERVAL_DURATION: "500ms"
    POLLING_TIMEOUT_DURATION: "1s"
MERCHANT_PORTAL:
  USER_INVITATION_URL: "https://dashboard-stg.harsya.com/login-invitation"
  LOGIN_URL: "https://dashboard-stg.harsya.com/login"
  LOGO_URL: "https://dashboard-stg.harsya.com/assets/images/iki.png"
  DASHBOARD_GUIDE_URL: "https://harsya.gitbook.io/harsya-dashboard-guide"
  PAYMENT_SIMULATION_PATTERN_URL: "https://dashboard-stg.harsya.com/simulation/payment/%s" #$1=paymentID
  CARD_FUNDED_PAYOUT_URL: "https://dashboard-stg.pivot-payment.com/card-funded-payout"
  CARD_FUNDED_PAYOUT_SAVED_CARD_URL: "https://dashboard-stg.pivot-payment.com/card-funded-payout/saved-cards"
  PAYMENT_RECEIPT_BACKGROUND: "https://storage.googleapis.com/pg-staging-static-files/icon/payment-receipt-background.png"
  RECEIPT_SENDER_NAME: "PT Harsya Remitindo"
MONITORING:
  IS_ENABLED: false
  MAX_BYTES_PER_PAYLOAD: 500000
  MAX_MESSAGES_PER_PAYLOAD: 5
  WRITE_TIMEOUT: 15
MULTI_FACTOR_AUTHENTICATION:
  TIME_BASED_OTP:
    TOTP_ISSUER: PivotPayment
    TOTP_SECRET_SIZE: 32
    TOTP_PERIOD_IN_SECONDS: 30
    TOTP_RATE_LIMIT:
      REQUEST_LIMIT: 1
      REQUEST_WINDOW: 1s
PAPER_COMMUNICATION:
  BASE_URL: "https://comm.stag-v2.paper.id"
  PLATFORM_NAME: "Pivot"
  SENDER_ORIGIN: "PGMailgun"
  EMAIL_SENDER: "Pivot No-Reply <no-reply@pivot-payment.com>"
  EMAIL_LOGO_URL: "https://storage.googleapis.com/pg-staging-static-files/icon/pivot-logo.png"
PERMISSION:
  PATH: "docs/menu-and-permission-list.json"
SNAP_CORE:
  BASE_URL: "localhost"
FLIP_PAYMENT_GATEWAY:
  BASE_URL: "https://bigflip.id/big_sandbox_api"
USER_OTP_CONFIG:
  MAX_SEND_RESET_PWD: 10
  MAX_SEND_RESET_PIN: 3
  MAX_SEND_CHANGE_PWD: 3
  MAX_SEND_USER_LOGIN: 10
  MAX_FAILED_VERIFY_RESET_PWD: 3
  MAX_FAILED_VERIFY_RESET_PIN: 3
  MAX_FAILED_VERIFY_CHANGE_PWD: 3
  MAX_FAILED_VERIFY_USER_LOGIN: 3
  EXPIRATION_SECONDS_FORGOT_PASSWORD: 300
  EXPIRATION_SECONDS_RESET_PIN: 300
  EXPIRATION_SECONDS_CHANGE_PASSWORD: 300
  EXPIRATION_SECONDS_USER_LOGIN: 300
  EXPIRATION_SECONDS_FIRST_TIME_LOGIN: 300
  RESEND_DELAY_SECONDS_FORGOT_PASSWORD: 240
  RESEND_DELAY_SECONDS_RESET_PIN: 240
  RESEND_DELAY_SECONDS_CHANGE_PASSWORD: 240
  RESEND_DELAY_SECONDS_USER_LOGIN: 240
  RESEND_DELAY_SECONDS_FIRST_TIME_LOGIN: 240
  RESEND_DELAY_SECONDS_DEFAULT: 30
  USER_LOGIN_WAIT_AFTER_SEND: 2
  USER_LOGIN_WAIT_TIME_MINUTE: 60
  FIRST_TIME_LOGIN_MAX_SEND: 32
  FIRST_TIME_LOGIN_MAX_FAILED_VERIFY: 3
  FIRST_TIME_LOGIN_WAIT_AFTER_SEND: 3
  FIRST_TIME_LOGIN_WAIT_TIME_MINUTE: 60
  USER_LOGIN_REMEMBER_IN_MINUTE: 43200 # 30 days
CREDIT_CARD:
  WEBVIEW_URL:
  PROCESSOR_URL:
CREDIT_CARD_REFERENCES:
  DEFAULT_FEE:
    OTHER_CHANNEL:
      AMOUNT: 2000
      PERCENTAGE: 2.5
    CUSTOM_CHANNEL:
      LOCAL_VISA:
        AMOUNT: 1500
        PERCENTAGE: 2.75
      FOREIGN_VISA:
        AMOUNT: 1500
        PERCENTAGE: 3
  DEFAULT_VIRTUAL_TERMINAL_FEE:
    TYPE: AMOUNT_PERCENTAGE
    AMOUNT: 2000
    PERCENTAGE: 2.5
  DEFAULT_CARD_FUNDED_PAYOUT_FEE:
    INSTANT:
      TYPE: PERCENTAGE
      AMOUNT: 0
      PERCENTAGE: 1.4
    STANDARD:
      TYPE: PERCENTAGE
      AMOUNT: 0
      PERCENTAGE: 1.3
  DEFAULT_SPLIT_PAYMENT_FEE:
    TYPE: PERCENTAGE
    AMOUNT: 2000
    PERCENTAGE: 2.5
  CARD_BRANDS:
    - VISA
    - MASTERCARD
    - JCB
    - AMEX
INSTALLMENT_FEE:
  DEFAULT:
    AMOUNT: 2000
    PERCENTAGE: 2.5
  CHANNEL: # each array index represent 1 fee configuration (fee - amount - percentage)
    BRI:
      TENOR: [3, 6, 12]
      AMOUNT: [2000, 2000, 2000]
      PERCENTAGE: [2.5, 2.5, 2.5]
    BNI:
      TENOR: [3, 6, 12]
      AMOUNT: [2000, 2000, 2000]
      PERCENTAGE: [2.5, 2.5, 2.5]
    KB_BANK:
      TENOR: [3, 6, 12]
      AMOUNT: [2000, 2000, 2000]
      PERCENTAGE: [2.5, 2.5, 2.5]
    UOB:
      TENOR: [3, 6, 12]
      AMOUNT: [2000, 2000, 2000]
      PERCENTAGE: [2.5, 2.5, 2.5]
    MANDIRI:
      TENOR: [3, 6, 12]
      AMOUNT: [2000, 2000, 2000]
      PERCENTAGE: [2.5, 2.5, 2.5]
    OCBC:
      TENOR: [3, 6, 12]
      AMOUNT: [2000, 2000, 2000]
      PERCENTAGE: [2.5, 2.5, 2.5]
    DBS:
      TENOR: [3, 6, 12]
      AMOUNT: [2000, 2000, 2000]
      PERCENTAGE: [2.5, 2.5, 2.5]
    BCA:
      TENOR: [3, 6, 12]
      AMOUNT: [2000, 2000, 2000]
      PERCENTAGE: [2.5, 2.5, 2.5]
WORKER_POOL:
  DISBURSEMENT: 25
OTLP:
  HOST: "otel-collector-host"
  INSECURE: true
  TLS_CLIENT_CONFIG:
    INSECURE_SKIP_VERIFY: true
  METRIC:
    INTERVAL: 5 # seconds
    EXPORT_TIMEOUT: 30 #seconds
XB_CORE_PROCESSOR:
  BASE_URL: "http://localhost:3001"
  DEFAULT_USD_RATE: 4321.25
  DEFAULT_LOCAL_FEE: 10.0
  DEFAULT_SWIFT_FEE: 25.0
  EXTENDED_EXPIRED_AT: 5 # in minutes
CREDITCARD_CORE_PROCESSOR:
  BASE_URL: "http://localhost:3001"
PAYMENT_UI:
  PAYMENT_LINK_URL: "https://link.here?token=%s"
  PAYMENT_SUCCESS_URL: "https://link.here/success?token=%s"
  PAYMENT_FAILED_URL: "https://link.here/failed?token=%s"
  PAYMENT_PROCESSING_URL: "https://link.here/processing?token=%s"
UNIFIED_PAYMENT_CONFIG:
  MASTER_QR_DUPLICATION_ID: ""
  CHANGE_PAYMENT_METHOD_FROM_VA: true
  CHANGE_PAYMENT_METHOD_FROM_QRIS: true
  CHANGE_PAYMENT_METHOD_FROM_CREDIT_CARD: false
  CHANGE_PAYMENT_METHOD_FROM_EWALLET: true
  MAX_AUTHORIZE_TRANSACTION_MINUTES: 10080 # 7 days
  RETRY_EXPIRING_AUTHORIZED_TRANSACTION_MINUTES: 1440 # 1 day
  EXPIRING_PROCESSED_PAYMENT_BACKOFF_MINUTES:
    - 1
    - 3
    - 5
    - 10
    - 15
    - 30
  EXPIRY_CONFIG:
    MODE: "PARTIAL" # ALL, PARTIAL, OFF
    EXCLUDED_MERCHANTS:
      - "193b2a46-3ca0-4d1a-9dae-7536b1b4a5f5"
  VIRTUAL_ACCOUNT:
    MIN_AMOUNT: 10000
    MAX_AMOUNT: 999999999
    MAX_EXPIRY_DURATION: 10
    MAX_EXPIRY_DURATION_UNIT: MINUTES # SECONDS, MINUTES, HOURS, DAYS
    DEFAULT_VA_CONFIG_MERCHANT_ID: ""
  QR:
    MIN_AMOUNT: 10000
    MAX_AMOUNT: 9999999999
    MAX_ACTIVE_STATIC_QR_PER_MERCHANT: 12
    MAX_EXPIRY_DURATION: 10
    MAX_EXPIRY_DURATION_UNIT: MINUTES # SECONDS, MINUTES, HOURS, DAYS
  CARD:
    MIN_AMOUNT: 10000
    MAX_AMOUNT: 9999999999
    ACCEPTED_CHANNELS: ["VISA", "MASTERCARD", "JCB"]
    MAX_EXPIRY_DURATION: 10
    MAX_EXPIRY_DURATION_UNIT: MINUTES # SECONDS, MINUTES, HOURS, DAYS
  EWALLET:
    MIN_AMOUNT: 1
    MAX_AMOUNT: 9999999999
    MAX_EXPIRY_DURATION: 10
    MAX_EXPIRY_DURATION_UNIT: MINUTES # SECONDS, MINUTES, HOURS, DAYS
  AUTO_INQUIRY:
    COOLDOWN_SECONDS: 30
PAYMENT_SETTLEMENT:
  CREDIT_CARD:
    OTHER_CHANNEL:
      TYPE: "T+5"
      DAY_TYPE: "ANYDAY"
  VIRTUAL_TERMINAL:
    TYPE: "T+2"
    DAY_TYPE: "ANYDAY"
  VIRTUAL_ACCOUNT:
    OTHER_CHANNEL:
      TYPE: "INSTANT"
      DAY_TYPE: "ANYDAY"
    BCA:
      TYPE: "T+1"
      DAY_TYPE: "ANYDAY"
    BSI:
      TYPE: "T+1"
      DAY_TYPE: "ANYDAY"
  QRIS:
    OTHER_CHANNEL:
      TYPE: "T+1"
      DAY_TYPE: "ANYDAY"
  EWALLET:
    OTHER_CHANNEL:
      TYPE: "T+2"
      DAY_TYPE: "ANYDAY"
  CARD_FUNDED_PAYOUT:
    TYPE: "D+1"
    DAY_TYPE: "ANYDAY"
    CUT_OFF:
      WINDOW:
        START_TIME: "14:00:00"
        END_TIME: "16:00:00"
      DEFERRAL:
        OFFSET_DAYS: 1
        EXECUTION_TIME: "12:00:00"
    SETTLEMENT_TIME: "12:00:00"
MERCHANT:
  DORMANT_VALIDATION: true
  CACHE_STATUS_DURATION_IN_MINUTES: 1440
  DORMANT_CONDITION:
    NO_ACTIVITIES_IN_MONTHS: 24
    NO_TRANSACTION_IN_DAYS: 60
VAULT:
  ADDRESS: http://localhost:8200
  SECRETS:
    USER_ENCRYPTION_KEY:
      MOUNT_PATH: backend-portal
      SECRET_PATH: user
      KEY_NAME: encryption_key
    MERCHANT_CREDENTIALS:
      SECRET_PATH: backend-portal-transit
      SECRET_KEY: merchant-credentials
    PAYMENT_ENCRYPTION_KEY:
      MOUNT_PATH: backend_portal
      SECRET_PATH: payment-encryption-key
WITHDRAWAL:
  AUTO_WITHDRAWAL_DEFAULT_STATE: "OFF" # OFF, ON
  AUTO_WITHDRAWAL_DEFAULT_SCHEDULING_TIME: "15:00:00"
  AUTO_WITHDRAWAL_BANK_CODE_TO_BE_EXEC_AFTER_TRIGGER: ["213"]
  MIN_AMOUNT: 10000
  MAX_AMOUNT: 250000000
  LIMIT_OVERBOOKING: 1000000000
  LIMIT_NON_OVERBOOKING: 250000000
  ACTIVE_CONSUMER: 10
  AUTO_WITHDRAWAL_WORKER: 10
  DISBURSEMENT_BALANCE_CONFIG:
    WITHDRAWAL_AFTER_INACTIVITY_DAYS: 55
    NOTIFICATION_AFTER_INACTIVITY_DAYS: 45
  PAYMENT_BALANCE_CONFIG:
    WITHDRAWAL_AFTER_INACTIVITY_DAYS: 15
    NOTIFICATION_AFTER_INACTIVITY_DAYS: 10
  VIRTUAL_TERMINAL_BALANCE_CONFIG:
    WITHDRAWAL_AFTER_INACTIVITY_DAYS: 15
    NOTIFICATION_AFTER_INACTIVITY_DAYS: 10
DISBURSEMENT:
  MIN_AMOUNT: 10000
  MAX_AMOUNT: 250000000
  DAILY_LIMIT_MERCHANT: 10000000000
  DAILY_LIMIT_MERCHANT_PLATFORM: 50000000000
  BENEFICIARY_LIMIT:
    AMOUNT: 1000000000
    VELOCITY: 10
  OVERBOOKING_BANK_MAX_AMOUNT: 1000000000
  OVERBOOKING_BANK_MAX_AMOUNT_FOR_CUSTOM_RULE: 10000000000
  CUT_OFF_TIME_WINDOW:
    ENABLED: true
    SAME_DAY: true
    GMT: 7
    START_TIME: "00:00"
    END_TIME: "04:59"
    TIME_LAG_FOR_SENDING_REPORT_SECOND: 15
    BANNER_SHOW_BEFORE_MINUTE: 60
    BANNER_STATUS: "Any transactions made between 00:00 - 04:59 (UTC +7) will be processed at 05:00 (UTC +7)."
    TRANSACTION_INFO: "The transactions approved are pending due to cut-off time between 00:00 - 04:59 (UTC +7). Processing will resume at 05:00 (UTC +7)."
  SCHEDULE_PAYOUT_ALERT_IN_MINUTE: 10
SLACK:
  PAYMENT_NOTIF_WEBHOOK_URL: ""
  MANUAL_TOPUP_NOTIF_WEBHOOK_URL: ""
  XB_PAYOUT_STATUS_UPDATE_WEBHOOK_URL: ""
  PAYOUT_CUT_OFF_TIME_WEBHOOK_URL: ""
  BENEFICIARY_PAYOUT_LIMIT_WEBHOOK_URL: ""
  FDS_ALERT_WEBHOOK_URL: ""
  PAYOUT_ALERT_WEBHOOK_URL: ""
  PG_ALERT_WEBHOOK_URL: ""
  WITHDRAWAL_ALERT_WEBHOOK_URL: ""
  TOPUP_NOTIF_WEBHOOK_URL: ""
  VCC_SETTLEMENT_TRANSACTION_INQUIRY_ALERT_WEBHOOK_URL: ""
RATE_LIMIT:
  LIMIT: 10
  TIME_OPTION: SECOND # SECOND, MINUTE, HOUR, DAILY
WALLET_BACKEND:
  HOST: ""
  INTERNAL_PREFIX_URL: "/internal/v1/"
CIMB:
  BASE_URL: ""
  PATH: ""
  RETRY_CONFIG:
    DEFAULT_BACKOFF_IN_SECONDS: [1, 3, 5]
ADVANCE_AI:
  BASE_URL: ""
  JOURNEY_ID: ""
DUKCAPIL:
  URL: ""
  THRESHOLD: 95
  FIELD_THRESHOLDS:
    NAME: 100
    GENDER: 100
    DOB: 100
    POB: 100
    JOB: 100
    ADDRESS: 95
    RT: 95
    RW: 95
    VILLAGE: 95
    DISTRICT: 95
    REGENCY: 95
    PROVINCE: 95
WHITELISTED_IPS:
  - ""
PAYMENT_SIMULATION:
  CARDS:
    BLOCKED_BY_FDS:
      - 4440000334400008
      - 5550000334400008
      - 3330000334400008
    REQUIRE_REVIEW_BY_FDS:
      - 4440000334400009
      - 5550000334400009
      - 3330000334400009
GCP_CONFIG:
  PROJECT_ID: example-project
  SECRET_MANAGER:
    ENCRYPTION_SECRET_NAME: example-encryption-secret
PAYMENT_FEE_DEFAULTS:
  EWALLET:
    DANA:
      TYPE: PERCENTAGE
      AMOUNT: 0
      PERCENTAGE: 1.3
    SHOPEEPAY:
      TYPE: PERCENTAGE
      AMOUNT: 0
      PERCENTAGE: 4
  OTHER:
    TYPE: AMOUNT
    AMOUNT: 4000
    PERCENTAGE: 0
RECON:
  SCANNING_TOLERANCE_IN_DAYS: 5
REORGANIZE_TABLE_PARTITION:
  ACCOUNT_TRANSACTIONS:
    ANALYZE_TABLE: true
    RANGE_PARTITIONS:
      - PARTITION_NAME: p_cold_archive
        DATA_OLDER_THAN_DAYS: 180
      - PARTITION_NAME: p_cold_historical
        DATA_OLDER_THAN_DAYS: 30
      - PARTITION_NAME: p_warm
        DATA_OLDER_THAN_DAYS: 7
      - PARTITION_NAME: p_hot
        DATA_OLDER_THAN_DAYS: 0
SHORT_LINK_REDIRECTION:
  URL_FORMAT: "https://payment-stg.harsya.com/s/%s"
  INVALID_URL: "https://payment-stg.harsya.com/invalid-link"
BIGQUERY:
  PROJECT_ID: ""
  LOCATION: ""
  QUERY_TIMEOUT_SECONDS: 60
  MAX_RETRIES: 3
  PAYOUT_SUCCESS_METRICS_TABLE: "imah_data_mart_layer.rpt__payout_success_metrics__daily"
  PAYMENT_SUCCESS_METRICS_TABLE: "data_mart_layer.rpt__payment_success_metrics__daily"
VCC_SLACK_RECIPIENT:
  DEFAULT_RECIPIENT: ["S09S89NKSCU", "S06N4CY0AFM"]
VCC_TERMINAL:
  DEFAULT_CONFIG:
    ACQUIRER_MERCHANT_ID: "TEST001999200220"
    CARD_TYPES: ["CREDIT", "DEBIT"]
    ALLOWED_BIN_NUMBERS: NULL # Allowed all BIN numbers
    PRINCIPAL_AVAILABLE: ["VISA", "MASTERCARD", "JCB"]
  TRAVEL_AGENTS:
    BOOKING: "Booking.com"
    AGODA: "Agoda"
    EXPEDIA: "Expedia"
    TRIP: "Trip.com"
    PELAGO: "Pelago"
    TRAVELOKA: "Traveloka"
    TIKET: "Tiket.com"
    RAKUTEN: "Rakuten Travel"
    HOTELBEDS: "Hotelbeds"
  EXPIRY_AFTER_MINUTES: 30
  CONSUMER_COUNT: 5
  WORKER_COUNT: 25

REPORTING_CONSUMERS:
  FEATURE_NAME: #
    ENABLED: false
    STREAM_QUEUE_NAME: "backend_portal.table_name"
    CONSUMER_NAME: "BACKEND_PORTAL"
    RETRY_COUNT: 5
    RETRY_DELAY: "500ms"
    COMMIT_SIZE: 100
    COMMIT_INTERVAL: "6s"
