# Need to Rotate for Every 6 months
# Last Rotated At: 
# Last Rotated By: 
CONDUCTOR:
  BASIC_AUTH:
    USERNAME: username
    PASSWORD: password
CRM:
  API_KEY: ""
SNAP_CORE:
  INTERNAL_SERVICE_KEY: ""
# End of the secret that need to rotate
INTERNAL_API_KEY:
  SALT: ""
  HASH_RESULT: ""
  AUTOMATED_TEST: ""
  SIMULATION: ""
  CARD_ENCRYPTION_SECRET: ""
JWT_SIGNATURE_KEY:
  USER: ""
  MERCHANT: ""
  TOKEN_OTP_KEY: ""
  TOKEN_OTP_FEATURE_KEY: ""
  PAYMENT_TOKEN: ""
  MERCHANT_RSA_KEY:
    PRIVATE_KEY_FILE: "/path/to/private_key"
    PUBLIC_KEY_FILE: "/path/to/public_key"
DATABASE:
  DB_NAME: "backend_portal"
  USERNAME: "root"
  PASSWORD: "myrootpassword"
REDIS:
  PASSWORD: "1550"
RABBITMQ:
  USERNAME: "myusername"
  PASSWORD: "mypassword"
RABBITMQ_STREAM:
  USERNAME: "myusername"
  PASSWORD: "mypassword"
PAYMENT:
  KEY_ENCRYPTION_KEY: "ab3033ee369b4b85b4cca68ee3d904b9"
SECURITY:
  RESPONSE_ENCRYPT_KEY: ""
  CARD_SECRET_KEY: "your_card_secret_key"
  CARD_IV: "your_card_iv"
NEW_RELIC_LICENSE_KEY: ""
STATSD_HOST: ""
STATSD_PORT: 0
CONSUL:
  TOKEN: ""
XB_CORE_PROCESSOR:
  INTERNAL_SERVICE_KEY: ""
FLIP_PAYMENT_GATEWAY:
  API_KEY: ""
  TOKEN_VALIDATION_KEY: ""
  IP_ADDRESS: []
VAULT:
  TOKEN: "token"
WALLET_BACKEND:
INTERNAL_SERVICE_KEY: "K72zPTA_PEqKzKjXc7cZ1kDgQXAnrSvbA4r4o2GpX6fQo5WWyABH_Q"
CIMB:
  RSA_PRIVATE_KEY: ""
  CLIENT_ID: ""
  CLIENT_SECRET: ""
  CHANNEL_ID: ""
  DIVISION_ID: ""
GOOGLE_KMS_KEY: ""
GOOGLE_APPLICATION_CREDENTIALS: "/input/your/path/service-account.json"
FRAUD_NET:
  ACCESS_KEY: ""
  ACCESS_SECRET: ""
SOKRATECH:
  ACCESS_SECRET: ""
CREDIT_CARD_CORE:
  INTERNAL_SERVICE_KEY: ""
  ENCRYPTION_PUBLIC_KEY_SECRET: ""
  ENCRYPTION_PUBLIC_KEY_IV: ""
ADVANCE_AI:
  API_KEY: ""
DUKCAPIL:
  USER_ID: ""
  PASSWORD: ""
  IP: ""
