sonar.projectKey=backend-portal
sonar.projectName=backend-portal
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=.github/**,.husky/**,cmd/**,deployments/**,docs/**,migration/**,mocks/**,observability/**,test/**,scripts/**,templates/**,scanner-config/**,**/*_test.go,internal/model/proto/**,main.go,port/http/route.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.activate=true
sonar.go.file.suffixes=.go
sonar.go.exclusions=**/vendor/**,**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.go.golangci-lint.reportPaths=golangci-lint.xml

sonar.coverage.exclusions=mocks/**,pkg/**,cmd/**,config/**,docs/**,constant/**,test/**,port/cron/cron.go,internal/model/proto/**,main.go,**/type.go,**/*_test.go,port/http/route.go,templates/**
sonar.cpd.exclusions=mocks/**,cmd/**,config/**,docs/**,internal/model/proto/**,main.go,**/*_test.go,port/http/route.go,templates/**
