// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/amount.proto

package common

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_common_amount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_common_amount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_common_amount_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Amount) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AmountDouble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmountDouble) Reset() {
	*x = AmountDouble{}
	mi := &file_common_amount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmountDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmountDouble) ProtoMessage() {}

func (x *AmountDouble) ProtoReflect() protoreflect.Message {
	mi := &file_common_amount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmountDouble.ProtoReflect.Descriptor instead.
func (*AmountDouble) Descriptor() ([]byte, []int) {
	return file_common_amount_proto_rawDescGZIP(), []int{1}
}

func (x *AmountDouble) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AmountDouble) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_common_amount_proto protoreflect.FileDescriptor

const file_common_amount_proto_rawDesc = "" +
	"\n" +
	"\x13common/amount.proto\x12\x06common\":\n" +
	"\x06Amount\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"@\n" +
	"\fAmountDouble\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05valueBHZFgithub.com/paper-indonesia/proto/payment-gateway/backend-portal/commonb\x06proto3"

var (
	file_common_amount_proto_rawDescOnce sync.Once
	file_common_amount_proto_rawDescData []byte
)

func file_common_amount_proto_rawDescGZIP() []byte {
	file_common_amount_proto_rawDescOnce.Do(func() {
		file_common_amount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_amount_proto_rawDesc), len(file_common_amount_proto_rawDesc)))
	})
	return file_common_amount_proto_rawDescData
}

var file_common_amount_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_amount_proto_goTypes = []any{
	(*Amount)(nil),       // 0: common.Amount
	(*AmountDouble)(nil), // 1: common.AmountDouble
}
var file_common_amount_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_amount_proto_init() }
func file_common_amount_proto_init() {
	if File_common_amount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_amount_proto_rawDesc), len(file_common_amount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_amount_proto_goTypes,
		DependencyIndexes: file_common_amount_proto_depIdxs,
		MessageInfos:      file_common_amount_proto_msgTypes,
	}.Build()
	File_common_amount_proto = out.File
	file_common_amount_proto_goTypes = nil
	file_common_amount_proto_depIdxs = nil
}
