// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	vault "github.com/paper-indonesia/pivot-backoffice/pkg/vault"
	mock "github.com/stretchr/testify/mock"
)

// IVaultTransit is an autogenerated mock type for the IVaultTransit type
type IVaultTransit struct {
	mock.Mock
}

// BatchEncrypt provides a mock function with given fields: ctx, request
func (_m *IVaultTransit) BatchEncrypt(ctx context.Context, request vault.BatchEncryptRequest) ([]vault.EncryptResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for BatchEncrypt")
	}

	var r0 []vault.EncryptResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vault.BatchEncryptRequest) ([]vault.EncryptResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vault.BatchEncryptRequest) []vault.EncryptResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vault.EncryptResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vault.BatchEncryptRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Decrypt provides a mock function with given fields: ctx, request
func (_m *IVaultTransit) Decrypt(ctx context.Context, request vault.DecryptRequest) (*vault.DecryptResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 *vault.DecryptResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vault.DecryptRequest) (*vault.DecryptResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vault.DecryptRequest) *vault.DecryptResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.DecryptResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vault.DecryptRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encrypt provides a mock function with given fields: ctx, request
func (_m *IVaultTransit) Encrypt(ctx context.Context, request vault.EncryptRequest) (*vault.EncryptResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 *vault.EncryptResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vault.EncryptRequest) (*vault.EncryptResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vault.EncryptRequest) *vault.EncryptResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.EncryptResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vault.EncryptRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIVaultTransit creates a new instance of IVaultTransit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIVaultTransit(t interface {
	mock.TestingT
	Cleanup(func())
}) *IVaultTransit {
	mock := &IVaultTransit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
