// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: payment-gateway/backend-portal/messages/callback/callback.proto

package callback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessCallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Event      string     `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	MerchantId string     `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Request    *anypb.Any `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	IsSnap     bool       `protobuf:"varint,5,opt,name=is_snap,json=isSnap,proto3" json:"is_snap,omitempty"`
}

func (x *ProcessCallbackRequest) Reset() {
	*x = ProcessCallbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_gateway_backend_portal_messages_callback_callback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCallbackRequest) ProtoMessage() {}

func (x *ProcessCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_gateway_backend_portal_messages_callback_callback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCallbackRequest.ProtoReflect.Descriptor instead.
func (*ProcessCallbackRequest) Descriptor() ([]byte, []int) {
	return file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessCallbackRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessCallbackRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ProcessCallbackRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ProcessCallbackRequest) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ProcessCallbackRequest) GetIsSnap() bool {
	if x != nil {
		return x.IsSnap
	}
	return false
}

var File_payment_gateway_backend_portal_messages_callback_callback_proto protoreflect.FileDescriptor

var file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x53, 0x6e, 0x61, 0x70, 0x42, 0x53, 0x5a, 0x51, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2d, 0x69, 0x6e, 0x64, 0x6f, 0x6e, 0x65,
	0x73, 0x69, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDescOnce sync.Once
	file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDescData = file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDesc
)

func file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDescGZIP() []byte {
	file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDescOnce.Do(func() {
		file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDescData = protoimpl.X.CompressGZIP(file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDescData)
	})
	return file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDescData
}

var file_payment_gateway_backend_portal_messages_callback_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_payment_gateway_backend_portal_messages_callback_callback_proto_goTypes = []any{
	(*ProcessCallbackRequest)(nil), // 0: callback.ProcessCallbackRequest
	(*anypb.Any)(nil),              // 1: google.protobuf.Any
}
var file_payment_gateway_backend_portal_messages_callback_callback_proto_depIdxs = []int32{
	1, // 0: callback.ProcessCallbackRequest.request:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_gateway_backend_portal_messages_callback_callback_proto_init() }
func file_payment_gateway_backend_portal_messages_callback_callback_proto_init() {
	if File_payment_gateway_backend_portal_messages_callback_callback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_payment_gateway_backend_portal_messages_callback_callback_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProcessCallbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_gateway_backend_portal_messages_callback_callback_proto_goTypes,
		DependencyIndexes: file_payment_gateway_backend_portal_messages_callback_callback_proto_depIdxs,
		MessageInfos:      file_payment_gateway_backend_portal_messages_callback_callback_proto_msgTypes,
	}.Build()
	File_payment_gateway_backend_portal_messages_callback_callback_proto = out.File
	file_payment_gateway_backend_portal_messages_callback_callback_proto_rawDesc = nil
	file_payment_gateway_backend_portal_messages_callback_callback_proto_goTypes = nil
	file_payment_gateway_backend_portal_messages_callback_callback_proto_depIdxs = nil
}
