// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// V1BeneficiaryAccountController is an autogenerated mock type for the V1BeneficiaryAccountController type
type V1BeneficiaryAccountController struct {
	mock.Mock
}

// CheckBeneficiary provides a mock function with given fields: w, r
func (_m *V1BeneficiaryAccountController) CheckBeneficiary(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetList provides a mock function with given fields: w, r
func (_m *V1BeneficiaryAccountController) GetList(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewV1BeneficiaryAccountController creates a new instance of V1BeneficiaryAccountController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV1BeneficiaryAccountController(t interface {
	mock.TestingT
	Cleanup(func())
}) *V1BeneficiaryAccountController {
	mock := &V1BeneficiaryAccountController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
