// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// V1CallbackController is an autogenerated mock type for the V1CallbackController type
type V1CallbackController struct {
	mock.Mock
}

// GetCallbackList provides a mock function with given fields: w, r
func (_m *V1CallbackController) GetCallbackList(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// RegisterCallback provides a mock function with given fields: w, r
func (_m *V1CallbackController) RegisterCallback(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewV1CallbackController creates a new instance of V1CallbackController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV1CallbackController(t interface {
	mock.TestingT
	Cleanup(func())
}) *V1CallbackController {
	mock := &V1CallbackController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
