// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// V1OrchestratorController is an autogenerated mock type for the V1OrchestratorController type
type V1OrchestratorController struct {
	mock.Mock
}

// ExportToExcelTransactionHistory provides a mock function with given fields: w, r
func (_m *V1OrchestratorController) ExportToExcelTransactionHistory(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetList provides a mock function with given fields: w, r
func (_m *V1OrchestratorController) GetList(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewV1OrchestratorController creates a new instance of V1OrchestratorController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV1OrchestratorController(t interface {
	mock.TestingT
	Cleanup(func())
}) *V1OrchestratorController {
	mock := &V1OrchestratorController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
