// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// V1PaymentController is an autogenerated mock type for the V1PaymentController type
type V1PaymentController struct {
	mock.Mock
}

// FindPaymentMethodByCategory provides a mock function with given fields: w, r
func (_m *V1PaymentController) FindPaymentMethodByCategory(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewV1PaymentController creates a new instance of V1PaymentController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV1PaymentController(t interface {
	mock.TestingT
	Cleanup(func())
}) *V1PaymentController {
	mock := &V1PaymentController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
