// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// V1XbPayoutController is an autogenerated mock type for the V1XbPayoutController type
type V1XbPayoutController struct {
	mock.Mock
}

// Confirm provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) Confirm(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CreateSession provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) CreateSession(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ExportToExcel provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) ExportToExcel(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetDetail provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetDetail(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetFeeConfig provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetFeeConfig(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetFxRate provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetFxRate(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetList provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetList(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterAccountType provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterAccountType(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterCity provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterCity(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterCountry provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterCountry(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterCurrency provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterCurrency(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterCurrencyMapping provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterCurrencyMapping(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterIdentificationType provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterIdentificationType(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterPurpose provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterPurpose(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterSourceOfIncome provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterSourceOfIncome(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterState provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterState(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetListMasterTransferMethod provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetListMasterTransferMethod(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetXbPayoutDashboardInsights provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) GetXbPayoutDashboardInsights(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UploadUnderlyingDocument provides a mock function with given fields: w, r
func (_m *V1XbPayoutController) UploadUnderlyingDocument(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewV1XbPayoutController creates a new instance of V1XbPayoutController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV1XbPayoutController(t interface {
	mock.TestingT
	Cleanup(func())
}) *V1XbPayoutController {
	mock := &V1XbPayoutController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
