// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	httpRequestExt "github.com/paper-indonesia/pivot-backoffice/pkg/httpRequestExt"
	mock "github.com/stretchr/testify/mock"
)

// HTTPRequestFunc is an autogenerated mock type for the HTTPRequestFunc type
type HTTPRequestFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *HTTPRequestFunc) Execute(_a0 *httpRequestExt.HTTPRequest) {
	_m.Called(_a0)
}

// NewHTTPRequestFunc creates a new instance of HTTPRequestFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPRequestFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPRequestFunc {
	mock := &HTTPRequestFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
