// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	io "io"

	excelize "github.com/xuri/excelize/v2"

	mock "github.com/stretchr/testify/mock"

	xlsx "github.com/paper-indonesia/pivot-backoffice/pkg/xlsx"
)

// Exceler is an autogenerated mock type for the Exceler type
type Exceler struct {
	mock.Mock
}

// OpenReader provides a mock function with given fields: r, opts
func (_m *Exceler) OpenReader(r io.Reader, opts ...excelize.Options) (xlsx.Filer, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, r)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OpenReader")
	}

	var r0 xlsx.Filer
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader, ...excelize.Options) (xlsx.Filer, error)); ok {
		return rf(r, opts...)
	}
	if rf, ok := ret.Get(0).(func(io.Reader, ...excelize.Options) xlsx.Filer); ok {
		r0 = rf(r, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(xlsx.Filer)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader, ...excelize.Options) error); ok {
		r1 = rf(r, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExceler creates a new instance of Exceler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExceler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Exceler {
	mock := &Exceler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
