// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/payment-gateway/snap-core-processor/messages/bankTransfer/cutoffReportTrigger.proto

package bankTransfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CutOffReportTrigger struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PartnerCode         string                 `protobuf:"bytes,1,opt,name=partnerCode,proto3" json:"partnerCode,omitempty"`
	PartnerName         string                 `protobuf:"bytes,2,opt,name=partnerName,proto3" json:"partnerName,omitempty"`
	CutoffWindowStartAt string                 `protobuf:"bytes,3,opt,name=cutoffWindowStartAt,proto3" json:"cutoffWindowStartAt,omitempty"`
	CutoffWindowEndAt   string                 `protobuf:"bytes,4,opt,name=cutoffWindowEndAt,proto3" json:"cutoffWindowEndAt,omitempty"`
	ExternalID          string                 `protobuf:"bytes,5,opt,name=externalID,proto3" json:"externalID,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CutOffReportTrigger) Reset() {
	*x = CutOffReportTrigger{}
	mi := &file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutOffReportTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutOffReportTrigger) ProtoMessage() {}

func (x *CutOffReportTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutOffReportTrigger.ProtoReflect.Descriptor instead.
func (*CutOffReportTrigger) Descriptor() ([]byte, []int) {
	return file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDescGZIP(), []int{0}
}

func (x *CutOffReportTrigger) GetPartnerCode() string {
	if x != nil {
		return x.PartnerCode
	}
	return ""
}

func (x *CutOffReportTrigger) GetPartnerName() string {
	if x != nil {
		return x.PartnerName
	}
	return ""
}

func (x *CutOffReportTrigger) GetCutoffWindowStartAt() string {
	if x != nil {
		return x.CutoffWindowStartAt
	}
	return ""
}

func (x *CutOffReportTrigger) GetCutoffWindowEndAt() string {
	if x != nil {
		return x.CutoffWindowEndAt
	}
	return ""
}

func (x *CutOffReportTrigger) GetExternalID() string {
	if x != nil {
		return x.ExternalID
	}
	return ""
}

var File_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto protoreflect.FileDescriptor

const file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDesc = "" +
	"\n" +
	"Yproto/payment-gateway/snap-core-processor/messages/bankTransfer/cutoffReportTrigger.proto\x12\fbankTransfer\"\xd9\x01\n" +
	"\x13CutOffReportTrigger\x12 \n" +
	"\vpartnerCode\x18\x01 \x01(\tR\vpartnerCode\x12 \n" +
	"\vpartnerName\x18\x02 \x01(\tR\vpartnerName\x120\n" +
	"\x13cutoffWindowStartAt\x18\x03 \x01(\tR\x13cutoffWindowStartAt\x12,\n" +
	"\x11cutoffWindowEndAt\x18\x04 \x01(\tR\x11cutoffWindowEndAt\x12\x1e\n" +
	"\n" +
	"externalID\x18\x05 \x01(\tR\n" +
	"externalIDBRZPgithub.com/paper-indonesia/snap-core-processor/internal/model/proto/bankTransferb\x06proto3"

var (
	file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDescOnce sync.Once
	file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDescData []byte
)

func file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDescGZIP() []byte {
	file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDescOnce.Do(func() {
		file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDesc), len(file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDesc)))
	})
	return file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDescData
}

var file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_goTypes = []any{
	(*CutOffReportTrigger)(nil), // 0: bankTransfer.CutOffReportTrigger
}
var file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_init()
}
func file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_init() {
	if File_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDesc), len(file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_goTypes,
		DependencyIndexes: file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_depIdxs,
		MessageInfos:      file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_msgTypes,
	}.Build()
	File_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto = out.File
	file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_goTypes = nil
	file_proto_payment_gateway_snap_core_processor_messages_bankTransfer_cutoffReportTrigger_proto_depIdxs = nil
}
