package constant

const AML_PROCESSOR = "AML_PROCESSOR"

const PROVIDER_ADVANCE_AI = "ADVANCE_AI"

const (
	AML_STATUS_APPROVED    = "APPROVED"
	AML_STATUS_REVIEW      = "REVIEW"
	AML_STATUS_NEED_REVIEW = "NEED_REVIEW"
)

const (
	AML_SUBJECT_TYPE_PERSON = "PERSON"
	AML_SUBJECT_TYPE_ENTITY = "ENTITY"
)
