// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	creditcard "github.com/paper-indonesia/pivot-backoffice/internal/service/v1/creditcard"
	mock "github.com/stretchr/testify/mock"
)

// CreditCardServiceFunc is an autogenerated mock type for the CreditCardServiceFunc type
type CreditCardServiceFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CreditCardServiceFunc) Execute(_a0 *creditcard.CreditCardService) {
	_m.Called(_a0)
}

// NewCreditCardServiceFunc creates a new instance of CreditCardServiceFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreditCardServiceFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreditCardServiceFunc {
	mock := &CreditCardServiceFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
