// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	account_model "github.com/paper-indonesia/pivot-backoffice/internal/model/account"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// IAccountService is an autogenerated mock type for the IAccountService type
type IAccountService struct {
	mock.Mock
}

// BulkCreateAccount provides a mock function with given fields: ctx, request
func (_m *IAccountService) BulkCreateAccount(ctx context.Context, request *account_model.BulkCreateAccountRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account_model.BulkCreateAccountRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CalculateAccountEodBalance provides a mock function with given fields: ctx
func (_m *IAccountService) CalculateAccountEodBalance(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CalculateAccountEodBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CalculateDailyAccountTransaction provides a mock function with given fields: ctx, location
func (_m *IAccountService) CalculateDailyAccountTransaction(ctx context.Context, location *time.Location) error {
	ret := _m.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for CalculateDailyAccountTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Location) error); ok {
		r0 = rf(ctx, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAccount provides a mock function with given fields: ctx, request
func (_m *IAccountService) CreateAccount(ctx context.Context, request *account_model.NewAccountRequest) (*account_model.AccountResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *account_model.AccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *account_model.NewAccountRequest) (*account_model.AccountResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *account_model.NewAccountRequest) *account_model.AccountResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account_model.AccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *account_model.NewAccountRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMerchantAccount provides a mock function with given fields: ctx, merchantId, userType
func (_m *IAccountService) CreateMerchantAccount(ctx context.Context, merchantId string, userType string) error {
	ret := _m.Called(ctx, merchantId, userType)

	if len(ret) == 0 {
		panic("no return value specified for CreateMerchantAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, merchantId, userType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccount provides a mock function with given fields: ctx, accountId
func (_m *IAccountService) GetAccount(ctx context.Context, accountId uuid.UUID) (*account_model.Account, error) {
	ret := _m.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*account_model.Account, error)); ok {
		return rf(ctx, accountId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *account_model.Account); ok {
		r0 = rf(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByReferenceIDAndUsecase provides a mock function with given fields: ctx, referenceID, usecase, userType
func (_m *IAccountService) GetAccountByReferenceIDAndUsecase(ctx context.Context, referenceID uuid.UUID, usecase string, userType string) (*account_model.Account, error) {
	ret := _m.Called(ctx, referenceID, usecase, userType)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByReferenceIDAndUsecase")
	}

	var r0 *account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*account_model.Account, error)); ok {
		return rf(ctx, referenceID, usecase, userType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *account_model.Account); ok {
		r0 = rf(ctx, referenceID, usecase, userType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, referenceID, usecase, userType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantAccounts provides a mock function with given fields: ctx, merchantIDs, usecase
func (_m *IAccountService) GetMerchantAccounts(ctx context.Context, merchantIDs []uuid.UUID, usecase string) (map[uuid.UUID]*account_model.Account, error) {
	ret := _m.Called(ctx, merchantIDs, usecase)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantAccounts")
	}

	var r0 map[uuid.UUID]*account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID, string) (map[uuid.UUID]*account_model.Account, error)); ok {
		return rf(ctx, merchantIDs, usecase)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID, string) map[uuid.UUID]*account_model.Account); ok {
		r0 = rf(ctx, merchantIDs, usecase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID, string) error); ok {
		r1 = rf(ctx, merchantIDs, usecase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletCustomerAccount provides a mock function with given fields: ctx, req
func (_m *IAccountService) GetWalletCustomerAccount(ctx context.Context, req *account_model.GetCustomerAccountRequest) (*account_model.Account, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletCustomerAccount")
	}

	var r0 *account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *account_model.GetCustomerAccountRequest) (*account_model.Account, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *account_model.GetCustomerAccountRequest) *account_model.Account); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *account_model.GetCustomerAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletMerchantAccount provides a mock function with given fields: ctx, parentMerchantId, merchantId
func (_m *IAccountService) GetWalletMerchantAccount(ctx context.Context, parentMerchantId uuid.UUID, merchantId uuid.UUID) (*account_model.Account, error) {
	ret := _m.Called(ctx, parentMerchantId, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletMerchantAccount")
	}

	var r0 *account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*account_model.Account, error)); ok {
		return rf(ctx, parentMerchantId, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *account_model.Account); ok {
		r0 = rf(ctx, parentMerchantId, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, parentMerchantId, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAccountService creates a new instance of IAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAccountService {
	mock := &IAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
