// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	adjustment "github.com/paper-indonesia/pivot-backoffice/internal/model/adjustment"

	mock "github.com/stretchr/testify/mock"
)

// IAdjustmentService is an autogenerated mock type for the IAdjustmentService type
type IAdjustmentService struct {
	mock.Mock
}

// CreateBalanceAdjustmentFromManualTopUp provides a mock function with given fields: ctx, req
func (_m *IAdjustmentService) CreateBalanceAdjustmentFromManualTopUp(ctx context.Context, req *adjustment.BalanceAdjustmentRequest) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateBalanceAdjustmentFromManualTopUp")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.BalanceAdjustmentRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.BalanceAdjustmentRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *adjustment.BalanceAdjustmentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateManualTopup provides a mock function with given fields: ctx, req
func (_m *IAdjustmentService) CreateManualTopup(ctx context.Context, req *adjustment.ManualTopupRequest) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateManualTopup")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.ManualTopupRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.ManualTopupRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *adjustment.ManualTopupRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMerchantBalanceAdjustment provides a mock function with given fields: ctx, req
func (_m *IAdjustmentService) CreateMerchantBalanceAdjustment(ctx context.Context, req *adjustment.MerchantBalanceAdjustmentRequest) (*adjustment.ManualAdjustmentHistory, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMerchantBalanceAdjustment")
	}

	var r0 *adjustment.ManualAdjustmentHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.MerchantBalanceAdjustmentRequest) (*adjustment.ManualAdjustmentHistory, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.MerchantBalanceAdjustmentRequest) *adjustment.ManualAdjustmentHistory); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adjustment.ManualAdjustmentHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *adjustment.MerchantBalanceAdjustmentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHoldedMerchantBalance provides a mock function with given fields: ctx, req
func (_m *IAdjustmentService) GetHoldedMerchantBalance(ctx context.Context, req *adjustment.GetHoldedMerchantBalanceRequest) (*adjustment.GetHoldedMerchantBalanceResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetHoldedMerchantBalance")
	}

	var r0 *adjustment.GetHoldedMerchantBalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.GetHoldedMerchantBalanceRequest) (*adjustment.GetHoldedMerchantBalanceResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.GetHoldedMerchantBalanceRequest) *adjustment.GetHoldedMerchantBalanceResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adjustment.GetHoldedMerchantBalanceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *adjustment.GetHoldedMerchantBalanceRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HoldMerchantBalance provides a mock function with given fields: ctx, req
func (_m *IAdjustmentService) HoldMerchantBalance(ctx context.Context, req *adjustment.HoldMerchantBalanceRequest) (*adjustment.HoldMerchantBalanceResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HoldMerchantBalance")
	}

	var r0 *adjustment.HoldMerchantBalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.HoldMerchantBalanceRequest) (*adjustment.HoldMerchantBalanceResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.HoldMerchantBalanceRequest) *adjustment.HoldMerchantBalanceResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adjustment.HoldMerchantBalanceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *adjustment.HoldMerchantBalanceRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseHoldedMerchantBalance provides a mock function with given fields: ctx, req
func (_m *IAdjustmentService) ReleaseHoldedMerchantBalance(ctx context.Context, req *adjustment.HoldMerchantBalanceRequest) (*adjustment.HoldMerchantBalanceResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseHoldedMerchantBalance")
	}

	var r0 *adjustment.HoldMerchantBalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.HoldMerchantBalanceRequest) (*adjustment.HoldMerchantBalanceResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *adjustment.HoldMerchantBalanceRequest) *adjustment.HoldMerchantBalanceResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adjustment.HoldMerchantBalanceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *adjustment.HoldMerchantBalanceRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAdjustmentService creates a new instance of IAdjustmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdjustmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdjustmentService {
	mock := &IAdjustmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
