// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	amlcommon "github.com/paper-indonesia/pivot-backoffice/internal/model/amlProcessor"

	mock "github.com/stretchr/testify/mock"
)

// IAmlService is an autogenerated mock type for the IAmlService type
type IAmlService struct {
	mock.Mock
}

// Profile provides a mock function with given fields: ctx, request, provider, merchantID, profileID
func (_m *IAmlService) Profile(ctx context.Context, request *amlcommon.CheckRequest, provider string, merchantID string, profileID string) (*amlcommon.ProfileDetailResponse, error) {
	ret := _m.Called(ctx, request, provider, merchantID, profileID)

	if len(ret) == 0 {
		panic("no return value specified for Profile")
	}

	var r0 *amlcommon.ProfileDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *amlcommon.CheckRequest, string, string, string) (*amlcommon.ProfileDetailResponse, error)); ok {
		return rf(ctx, request, provider, merchantID, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *amlcommon.CheckRequest, string, string, string) *amlcommon.ProfileDetailResponse); ok {
		r0 = rf(ctx, request, provider, merchantID, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amlcommon.ProfileDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *amlcommon.CheckRequest, string, string, string) error); ok {
		r1 = rf(ctx, request, provider, merchantID, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Screening provides a mock function with given fields: ctx, request, provider, merchantID
func (_m *IAmlService) Screening(ctx context.Context, request *amlcommon.CheckRequest, provider string, merchantID string) (*amlcommon.ScreeningResponse, error) {
	ret := _m.Called(ctx, request, provider, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for Screening")
	}

	var r0 *amlcommon.ScreeningResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *amlcommon.CheckRequest, string, string) (*amlcommon.ScreeningResponse, error)); ok {
		return rf(ctx, request, provider, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *amlcommon.CheckRequest, string, string) *amlcommon.ScreeningResponse); ok {
		r0 = rf(ctx, request, provider, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amlcommon.ScreeningResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *amlcommon.CheckRequest, string, string) error); ok {
		r1 = rf(ctx, request, provider, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDetailStatusByProfileId provides a mock function with given fields: ctx, profileID, merchantID, request
func (_m *IAmlService) UpdateDetailStatusByProfileId(ctx context.Context, profileID string, merchantID string, request *amlcommon.UpdateDetailStatusRequest) error {
	ret := _m.Called(ctx, profileID, merchantID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDetailStatusByProfileId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *amlcommon.UpdateDetailStatusRequest) error); ok {
		r0 = rf(ctx, profileID, merchantID, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAmlService creates a new instance of IAmlService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAmlService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAmlService {
	mock := &IAmlService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
