// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	bankAccount "github.com/paper-indonesia/pivot-backoffice/internal/model/bankAccount"

	mock "github.com/stretchr/testify/mock"
)

// IBankAccountService is an autogenerated mock type for the IBankAccountService type
type IBankAccountService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *IBankAccountService) Create(ctx context.Context, request *bankAccount.CreateBankAccountRequest) (*bankAccount.BankAccountResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *bankAccount.BankAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *bankAccount.CreateBankAccountRequest) (*bankAccount.BankAccountResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *bankAccount.CreateBankAccountRequest) *bankAccount.BankAccountResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bankAccount.BankAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *bankAccount.CreateBankAccountRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByMerchantID provides a mock function with given fields: ctx, request
func (_m *IBankAccountService) GetByMerchantID(ctx context.Context, request *bankAccount.GetMerchantBankAccountRequest) (*bankAccount.BankAccount, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetByMerchantID")
	}

	var r0 *bankAccount.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *bankAccount.GetMerchantBankAccountRequest) (*bankAccount.BankAccount, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *bankAccount.GetMerchantBankAccountRequest) *bankAccount.BankAccount); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bankAccount.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *bankAccount.GetMerchantBankAccountRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request
func (_m *IBankAccountService) Update(ctx context.Context, request *bankAccount.UpdateBankAccountRequest) (*bankAccount.BankAccountResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *bankAccount.BankAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *bankAccount.UpdateBankAccountRequest) (*bankAccount.BankAccountResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *bankAccount.UpdateBankAccountRequest) *bankAccount.BankAccountResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bankAccount.BankAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *bankAccount.UpdateBankAccountRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIBankAccountService creates a new instance of IBankAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBankAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBankAccountService {
	mock := &IBankAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
