// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	beneficiaryAccountModel "github.com/paper-indonesia/pivot-backoffice/internal/model/beneficiaryAccount"
	commonModel "github.com/paper-indonesia/pivot-backoffice/internal/model/common"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IBeneficiaryAccountService is an autogenerated mock type for the IBeneficiaryAccountService type
type IBeneficiaryAccountService struct {
	mock.Mock
}

// FindByBankCodeAndAccountNo provides a mock function with given fields: ctx, req
func (_m *IBeneficiaryAccountService) FindByBankCodeAndAccountNo(ctx context.Context, req *beneficiaryAccountModel.CheckAccountRequest) (*beneficiaryAccountModel.Account, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindByBankCodeAndAccountNo")
	}

	var r0 *beneficiaryAccountModel.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *beneficiaryAccountModel.CheckAccountRequest) (*beneficiaryAccountModel.Account, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *beneficiaryAccountModel.CheckAccountRequest) *beneficiaryAccountModel.Account); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*beneficiaryAccountModel.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *beneficiaryAccountModel.CheckAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, filter, page, perPage
func (_m *IBeneficiaryAccountService) GetList(ctx context.Context, filter *beneficiaryAccountModel.GetBeneficiaryAccountFilterRequest, page int64, perPage int64) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *beneficiaryAccountModel.GetBeneficiaryAccountFilterRequest, int64, int64) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *beneficiaryAccountModel.GetBeneficiaryAccountFilterRequest, int64, int64) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *beneficiaryAccountModel.GetBeneficiaryAccountFilterRequest, int64, int64) error); ok {
		r1 = rf(ctx, filter, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIBeneficiaryAccountService creates a new instance of IBeneficiaryAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBeneficiaryAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBeneficiaryAccountService {
	mock := &IBeneficiaryAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
