// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	callback_model "github.com/paper-indonesia/pivot-backoffice/internal/model/callback"
	commonModel "github.com/paper-indonesia/pivot-backoffice/internal/model/common"

	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ICallbackService is an autogenerated mock type for the ICallbackService type
type ICallbackService struct {
	mock.Mock
}

// FindCallbackByMerchantIdAndCallbackName provides a mock function with given fields: ctx, merchantId, callbackName
func (_m *ICallbackService) FindCallbackByMerchantIdAndCallbackName(ctx context.Context, merchantId uuid.UUID, callbackName string) (*callback_model.Callback, error) {
	ret := _m.Called(ctx, merchantId, callbackName)

	if len(ret) == 0 {
		panic("no return value specified for FindCallbackByMerchantIdAndCallbackName")
	}

	var r0 *callback_model.Callback
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*callback_model.Callback, error)); ok {
		return rf(ctx, merchantId, callbackName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *callback_model.Callback); ok {
		r0 = rf(ctx, merchantId, callbackName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*callback_model.Callback)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, merchantId, callbackName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCallbackAPIKeyByMerchantId provides a mock function with given fields: ctx, request
func (_m *ICallbackService) GetCallbackAPIKeyByMerchantId(ctx context.Context, request *callback_model.CallbackURLSettingReq) (interface{}, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetCallbackAPIKeyByMerchantId")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.CallbackURLSettingReq) (interface{}, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.CallbackURLSettingReq) interface{}); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *callback_model.CallbackURLSettingReq) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCallbackLogDetail provides a mock function with given fields: ctx, id, merchantID
func (_m *ICallbackService) GetCallbackLogDetail(ctx context.Context, id string, merchantID string) (*callback_model.CallbackLogWithMaster, error) {
	ret := _m.Called(ctx, id, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetCallbackLogDetail")
	}

	var r0 *callback_model.CallbackLogWithMaster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*callback_model.CallbackLogWithMaster, error)); ok {
		return rf(ctx, id, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *callback_model.CallbackLogWithMaster); ok {
		r0 = rf(ctx, id, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*callback_model.CallbackLogWithMaster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCallbackLogList provides a mock function with given fields: ctx, filter, page, perPage
func (_m *ICallbackService) GetCallbackLogList(ctx context.Context, filter *callback_model.GetListCallbackLogFilterRequest, page int64, perPage int64) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetCallbackLogList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.GetListCallbackLogFilterRequest, int64, int64) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.GetListCallbackLogFilterRequest, int64, int64) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *callback_model.GetListCallbackLogFilterRequest, int64, int64) error); ok {
		r1 = rf(ctx, filter, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCallbackURLByMerchantId provides a mock function with given fields: ctx, request
func (_m *ICallbackService) GetCallbackURLByMerchantId(ctx context.Context, request *callback_model.CallbackURLSettingReq) (interface{}, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetCallbackURLByMerchantId")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.CallbackURLSettingReq) (interface{}, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.CallbackURLSettingReq) interface{}); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *callback_model.CallbackURLSettingReq) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, filter, page, perPage
func (_m *ICallbackService) GetList(ctx context.Context, filter *callback_model.GetListCallbackFilterRequest, page int64, perPage int64) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.GetListCallbackFilterRequest, int64, int64) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.GetListCallbackFilterRequest, int64, int64) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *callback_model.GetListCallbackFilterRequest, int64, int64) error); ok {
		r1 = rf(ctx, filter, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessCallback provides a mock function with given fields: ctx, request
func (_m *ICallbackService) ProcessCallback(ctx context.Context, request *callback_model.ProcessCallbackRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ProcessCallback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.ProcessCallbackRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterCallback provides a mock function with given fields: ctx, request
func (_m *ICallbackService) RegisterCallback(ctx context.Context, request *callback_model.RegisterCallbackRequest) (*callback_model.RegisterCallbackResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCallback")
	}

	var r0 *callback_model.RegisterCallbackResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.RegisterCallbackRequest) (*callback_model.RegisterCallbackResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.RegisterCallbackRequest) *callback_model.RegisterCallbackResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*callback_model.RegisterCallbackResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *callback_model.RegisterCallbackRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResendCallback provides a mock function with given fields: ctx, id, merchantID
func (_m *ICallbackService) ResendCallback(ctx context.Context, id string, merchantID string) error {
	ret := _m.Called(ctx, id, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for ResendCallback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, merchantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResendSNAPCallback provides a mock function with given fields: ctx, id, merchantID
func (_m *ICallbackService) ResendSNAPCallback(ctx context.Context, id string, merchantID string) error {
	ret := _m.Called(ctx, id, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for ResendSNAPCallback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, merchantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMerchantCallback provides a mock function with given fields: ctx, request
func (_m *ICallbackService) SendMerchantCallback(ctx context.Context, request callback_model.SendMerchantCallbackRequest) (*callback_model.SendMerchantCallbackResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SendMerchantCallback")
	}

	var r0 *callback_model.SendMerchantCallbackResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, callback_model.SendMerchantCallbackRequest) (*callback_model.SendMerchantCallbackResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, callback_model.SendMerchantCallbackRequest) *callback_model.SendMerchantCallbackResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*callback_model.SendMerchantCallbackResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, callback_model.SendMerchantCallbackRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TestAndSaveB2b provides a mock function with given fields: ctx, request
func (_m *ICallbackService) TestAndSaveB2b(ctx context.Context, request *callback_model.TestAndSaveCallbackURLReq) (*callback_model.TestAndSaveCallbackURLResp, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for TestAndSaveB2b")
	}

	var r0 *callback_model.TestAndSaveCallbackURLResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.TestAndSaveCallbackURLReq) (*callback_model.TestAndSaveCallbackURLResp, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.TestAndSaveCallbackURLReq) *callback_model.TestAndSaveCallbackURLResp); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*callback_model.TestAndSaveCallbackURLResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *callback_model.TestAndSaveCallbackURLReq) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TestAndSaveCallbackURL provides a mock function with given fields: ctx, request
func (_m *ICallbackService) TestAndSaveCallbackURL(ctx context.Context, request *callback_model.TestAndSaveCallbackURLReq) (*callback_model.TestAndSaveCallbackURLResp, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for TestAndSaveCallbackURL")
	}

	var r0 *callback_model.TestAndSaveCallbackURLResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.TestAndSaveCallbackURLReq) (*callback_model.TestAndSaveCallbackURLResp, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.TestAndSaveCallbackURLReq) *callback_model.TestAndSaveCallbackURLResp); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*callback_model.TestAndSaveCallbackURLResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *callback_model.TestAndSaveCallbackURLReq) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TestAndSaveSnapPayment provides a mock function with given fields: ctx, request
func (_m *ICallbackService) TestAndSaveSnapPayment(ctx context.Context, request *callback_model.TestAndSaveCallbackURLReq) (*callback_model.TestAndSaveCallbackURLResp, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for TestAndSaveSnapPayment")
	}

	var r0 *callback_model.TestAndSaveCallbackURLResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.TestAndSaveCallbackURLReq) (*callback_model.TestAndSaveCallbackURLResp, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *callback_model.TestAndSaveCallbackURLReq) *callback_model.TestAndSaveCallbackURLResp); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*callback_model.TestAndSaveCallbackURLResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *callback_model.TestAndSaveCallbackURLReq) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteCallbackLogFromWorkflowTask provides a mock function with given fields: ctx, log
func (_m *ICallbackService) WriteCallbackLogFromWorkflowTask(ctx context.Context, log callback_model.WorkflowWriteLogRequest) (*callback_model.WorkflowWriteLogResponse, error) {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for WriteCallbackLogFromWorkflowTask")
	}

	var r0 *callback_model.WorkflowWriteLogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, callback_model.WorkflowWriteLogRequest) (*callback_model.WorkflowWriteLogResponse, error)); ok {
		return rf(ctx, log)
	}
	if rf, ok := ret.Get(0).(func(context.Context, callback_model.WorkflowWriteLogRequest) *callback_model.WorkflowWriteLogResponse); ok {
		r0 = rf(ctx, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*callback_model.WorkflowWriteLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, callback_model.WorkflowWriteLogRequest) error); ok {
		r1 = rf(ctx, log)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCallbackEvents provides a mock function with given fields: ctx
func (_m *ICallbackService) GetCallbackEvents(ctx context.Context) ([]callback_model.CallbackEvent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCallbackEvents")
	}

	var r0 []callback_model.CallbackEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]callback_model.CallbackEvent, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []callback_model.CallbackEvent); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]callback_model.CallbackEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICallbackService creates a new instance of ICallbackService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICallbackService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICallbackService {
	mock := &ICallbackService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
