// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	credential "github.com/paper-indonesia/pivot-backoffice/internal/model/credential"
	mock "github.com/stretchr/testify/mock"
)

// ICredentialService is an autogenerated mock type for the ICredentialService type
type ICredentialService struct {
	mock.Mock
}

// ClientSecretById provides a mock function with given fields: ctx, request
func (_m *ICredentialService) ClientSecretById(ctx context.Context, request *credential.ClientSecretReq) (*credential.ClientSecretResp, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ClientSecretById")
	}

	var r0 *credential.ClientSecretResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *credential.ClientSecretReq) (*credential.ClientSecretResp, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *credential.ClientSecretReq) *credential.ClientSecretResp); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credential.ClientSecretResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *credential.ClientSecretReq) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, request
func (_m *ICredentialService) Get(ctx context.Context, request *credential.CredentialDashboardReq) (*credential.CredentialDashboardResp, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *credential.CredentialDashboardResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *credential.CredentialDashboardReq) (*credential.CredentialDashboardResp, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *credential.CredentialDashboardReq) *credential.CredentialDashboardResp); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credential.CredentialDashboardResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *credential.CredentialDashboardReq) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICredentialService creates a new instance of ICredentialService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICredentialService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICredentialService {
	mock := &ICredentialService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
