// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/paper-indonesia/pivot-backoffice/config"

	disbursementModel "github.com/paper-indonesia/pivot-backoffice/internal/model/disbursement"

	mock "github.com/stretchr/testify/mock"

	orchestrator_model "github.com/paper-indonesia/pivot-backoffice/internal/model/orchestrator"

	service "github.com/paper-indonesia/pivot-backoffice/internal/service"

	time "time"
)

// IDisbursementInternalService is an autogenerated mock type for the IDisbursementInternalService type
type IDisbursementInternalService struct {
	mock.Mock
}

// Approve provides a mock function with given fields: ctx, request
func (_m *IDisbursementInternalService) Approve(ctx context.Context, request *disbursementModel.ApproveRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Approve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.ApproveRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBankTransfer provides a mock function with given fields: ctx, disbursement
func (_m *IDisbursementInternalService) CreateBankTransfer(ctx context.Context, disbursement *disbursementModel.DisbursementWithTransaction) error {
	ret := _m.Called(ctx, disbursement)

	if len(ret) == 0 {
		panic("no return value specified for CreateBankTransfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.DisbursementWithTransaction) error); ok {
		r0 = rf(ctx, disbursement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePendingOrchestratorTransaction provides a mock function with given fields: ctx, disbursement
func (_m *IDisbursementInternalService) CreatePendingOrchestratorTransaction(ctx context.Context, disbursement *disbursementModel.DisbursementWithTransaction) (string, string, error) {
	ret := _m.Called(ctx, disbursement)

	if len(ret) == 0 {
		panic("no return value specified for CreatePendingOrchestratorTransaction")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.DisbursementWithTransaction) (string, string, error)); ok {
		return rf(ctx, disbursement)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.DisbursementWithTransaction) string); ok {
		r0 = rf(ctx, disbursement)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *disbursementModel.DisbursementWithTransaction) string); ok {
		r1 = rf(ctx, disbursement)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *disbursementModel.DisbursementWithTransaction) error); ok {
		r2 = rf(ctx, disbursement)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DecrBeneficiaryPayoutLimit provides a mock function with given fields: ctx, merchantID, bankCode, accountNo, totalAmount
func (_m *IDisbursementInternalService) DecrBeneficiaryPayoutLimit(ctx context.Context, merchantID string, bankCode string, accountNo string, totalAmount float64) error {
	ret := _m.Called(ctx, merchantID, bankCode, accountNo, totalAmount)

	if len(ret) == 0 {
		panic("no return value specified for DecrBeneficiaryPayoutLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, float64) error); ok {
		r0 = rf(ctx, merchantID, bankCode, accountNo, totalAmount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrDailyTransactionLimit provides a mock function with given fields: ctx, merchantId, totalAmount
func (_m *IDisbursementInternalService) DecrDailyTransactionLimit(ctx context.Context, merchantId string, totalAmount float64) error {
	ret := _m.Called(ctx, merchantId, totalAmount)

	if len(ret) == 0 {
		panic("no return value specified for DecrDailyTransactionLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = rf(ctx, merchantId, totalAmount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDailyTransactionLimit provides a mock function with given fields: ctx, merchantId
func (_m *IDisbursementInternalService) DeleteDailyTransactionLimit(ctx context.Context, merchantId string) error {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDailyTransactionLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, merchantId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExternalFDS provides a mock function with given fields: ctx, payout, ledger
func (_m *IDisbursementInternalService) ExternalFDS(ctx context.Context, payout *disbursementModel.DisbursementWithTransaction, ledger *orchestrator_model.TransactionAndFeeObject) error {
	ret := _m.Called(ctx, payout, ledger)

	if len(ret) == 0 {
		panic("no return value specified for ExternalFDS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.DisbursementWithTransaction, *orchestrator_model.TransactionAndFeeObject) error); ok {
		r0 = rf(ctx, payout, ledger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FailTransactionByFDSResult provides a mock function with given fields: ctx, payoutID, ledger
func (_m *IDisbursementInternalService) FailTransactionByFDSResult(ctx context.Context, payoutID string, ledger *orchestrator_model.TransactionAndFeeObject) error {
	ret := _m.Called(ctx, payoutID, ledger)

	if len(ret) == 0 {
		panic("no return value specified for FailTransactionByFDSResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *orchestrator_model.TransactionAndFeeObject) error); ok {
		r0 = rf(ctx, payoutID, ledger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCutOffTimeStatus provides a mock function with given fields: ctx, now, merchantId, windowConfig
func (_m *IDisbursementInternalService) GetCutOffTimeStatus(ctx context.Context, now time.Time, merchantId string, windowConfig *config.DisbursementCutOffTimeWindow) (*disbursementModel.CutOffTimeStatusResponse, error) {
	ret := _m.Called(ctx, now, merchantId, windowConfig)

	if len(ret) == 0 {
		panic("no return value specified for GetCutOffTimeStatus")
	}

	var r0 *disbursementModel.CutOffTimeStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, string, *config.DisbursementCutOffTimeWindow) (*disbursementModel.CutOffTimeStatusResponse, error)); ok {
		return rf(ctx, now, merchantId, windowConfig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, string, *config.DisbursementCutOffTimeWindow) *disbursementModel.CutOffTimeStatusResponse); ok {
		r0 = rf(ctx, now, merchantId, windowConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.CutOffTimeStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, string, *config.DisbursementCutOffTimeWindow) error); ok {
		r1 = rf(ctx, now, merchantId, windowConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessBankTransferAndUpdateTransaction provides a mock function with given fields: ctx, disbursement, orchestratorTransaction
func (_m *IDisbursementInternalService) ProcessBankTransferAndUpdateTransaction(ctx context.Context, disbursement *disbursementModel.DisbursementWithTransaction, orchestratorTransaction *orchestrator_model.TransactionAndFeeObject) error {
	ret := _m.Called(ctx, disbursement, orchestratorTransaction)

	if len(ret) == 0 {
		panic("no return value specified for ProcessBankTransferAndUpdateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.DisbursementWithTransaction, *orchestrator_model.TransactionAndFeeObject) error); ok {
		r0 = rf(ctx, disbursement, orchestratorTransaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateBankAccountAndUpdateTransaction provides a mock function with given fields: ctx, disbursement, orchestratorTransaction
func (_m *IDisbursementInternalService) ValidateBankAccountAndUpdateTransaction(ctx context.Context, disbursement *disbursementModel.DisbursementWithTransaction, orchestratorTransaction *orchestrator_model.TransactionAndFeeObject) error {
	ret := _m.Called(ctx, disbursement, orchestratorTransaction)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBankAccountAndUpdateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.DisbursementWithTransaction, *orchestrator_model.TransactionAndFeeObject) error); ok {
		r0 = rf(ctx, disbursement, orchestratorTransaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateBeneficiaryPayoutCustomRule provides a mock function with given fields: ctx, merchantId, bankCode, accountNo, accountName, amount, rule
func (_m *IDisbursementInternalService) ValidateBeneficiaryPayoutCustomRule(ctx context.Context, merchantId string, bankCode string, accountNo string, accountName string, amount float64, rule *disbursementModel.BeneficiaryPayoutLimitRuleConfig) error {
	ret := _m.Called(ctx, merchantId, bankCode, accountNo, accountName, amount, rule)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBeneficiaryPayoutCustomRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, float64, *disbursementModel.BeneficiaryPayoutLimitRuleConfig) error); ok {
		r0 = rf(ctx, merchantId, bankCode, accountNo, accountName, amount, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateBeneficiaryPayoutDefaultRule provides a mock function with given fields: ctx, merchantId, bankCode, accountNo, accountName, amount, rule
func (_m *IDisbursementInternalService) ValidateBeneficiaryPayoutDefaultRule(ctx context.Context, merchantId string, bankCode string, accountNo string, accountName string, amount float64, rule *disbursementModel.BeneficiaryPayoutLimitRuleConfig) error {
	ret := _m.Called(ctx, merchantId, bankCode, accountNo, accountName, amount, rule)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBeneficiaryPayoutDefaultRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, float64, *disbursementModel.BeneficiaryPayoutLimitRuleConfig) error); ok {
		r0 = rf(ctx, merchantId, bankCode, accountNo, accountName, amount, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateBeneficiaryPayoutMerchantPolicyRule provides a mock function with given fields: ctx, merchantId, bankCode, accountNo, accountName, amount, rule
func (_m *IDisbursementInternalService) ValidateBeneficiaryPayoutMerchantPolicyRule(ctx context.Context, merchantId string, bankCode string, accountNo string, accountName string, amount float64, rule *disbursementModel.BeneficiaryPayoutLimitRuleConfig) error {
	ret := _m.Called(ctx, merchantId, bankCode, accountNo, accountName, amount, rule)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBeneficiaryPayoutMerchantPolicyRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, float64, *disbursementModel.BeneficiaryPayoutLimitRuleConfig) error); ok {
		r0 = rf(ctx, merchantId, bankCode, accountNo, accountName, amount, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateDailyTransactionLimit provides a mock function with given fields: ctx, merchantId, totalAmount
func (_m *IDisbursementInternalService) ValidateDailyTransactionLimit(ctx context.Context, merchantId string, totalAmount float64) (service.ITransactionCloser, error) {
	ret := _m.Called(ctx, merchantId, totalAmount)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDailyTransactionLimit")
	}

	var r0 service.ITransactionCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) (service.ITransactionCloser, error)); ok {
		return rf(ctx, merchantId, totalAmount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) service.ITransactionCloser); ok {
		r0 = rf(ctx, merchantId, totalAmount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.ITransactionCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64) error); ok {
		r1 = rf(ctx, merchantId, totalAmount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDisbursementInternalService creates a new instance of IDisbursementInternalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDisbursementInternalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDisbursementInternalService {
	mock := &IDisbursementInternalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
