// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	installmentPlanModel "github.com/paper-indonesia/pivot-backoffice/internal/model/installmentPlan"
	mock "github.com/stretchr/testify/mock"
)

// IInstallmentPlanService is an autogenerated mock type for the IInstallmentPlanService type
type IInstallmentPlanService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *IInstallmentPlanService) Create(ctx context.Context, request *installmentPlanModel.CreateInstallmentPlanRequest) (*installmentPlanModel.InstallmentPlan, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *installmentPlanModel.InstallmentPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *installmentPlanModel.CreateInstallmentPlanRequest) (*installmentPlanModel.InstallmentPlan, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *installmentPlanModel.CreateInstallmentPlanRequest) *installmentPlanModel.InstallmentPlan); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*installmentPlanModel.InstallmentPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *installmentPlanModel.CreateInstallmentPlanRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, req
func (_m *IInstallmentPlanService) List(ctx context.Context, req *installmentPlanModel.FilterRequest) ([]*installmentPlanModel.InstallmentPlan, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*installmentPlanModel.InstallmentPlan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *installmentPlanModel.FilterRequest) ([]*installmentPlanModel.InstallmentPlan, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *installmentPlanModel.FilterRequest) []*installmentPlanModel.InstallmentPlan); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*installmentPlanModel.InstallmentPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *installmentPlanModel.FilterRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *installmentPlanModel.FilterRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, request
func (_m *IInstallmentPlanService) Update(ctx context.Context, request *installmentPlanModel.UpdateInstallmentPlanRequest) (*installmentPlanModel.InstallmentPlan, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *installmentPlanModel.InstallmentPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *installmentPlanModel.UpdateInstallmentPlanRequest) (*installmentPlanModel.InstallmentPlan, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *installmentPlanModel.UpdateInstallmentPlanRequest) *installmentPlanModel.InstallmentPlan); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*installmentPlanModel.InstallmentPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *installmentPlanModel.UpdateInstallmentPlanRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIInstallmentPlanService creates a new instance of IInstallmentPlanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInstallmentPlanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInstallmentPlanService {
	mock := &IInstallmentPlanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
