// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	ledger_model "github.com/paper-indonesia/pivot-backoffice/internal/model/ledger"
	mock "github.com/stretchr/testify/mock"
)

// ILedgerMoneyFlowService is an autogenerated mock type for the ILedgerMoneyFlowService type
type ILedgerMoneyFlowService struct {
	mock.Mock
}

// CreateTransactions provides a mock function with given fields: ctx, request
func (_m *ILedgerMoneyFlowService) CreateTransactions(ctx context.Context, request *ledger_model.CreateNewLedgerEntryRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ledger_model.CreateNewLedgerEntryRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewILedgerMoneyFlowService creates a new instance of ILedgerMoneyFlowService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILedgerMoneyFlowService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILedgerMoneyFlowService {
	mock := &ILedgerMoneyFlowService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
