// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	merchantForbiddenUsecase "github.com/paper-indonesia/pivot-backoffice/internal/model/merchantForbiddenUsecase"
	mock "github.com/stretchr/testify/mock"
)

// IMerchantForbiddenUseCaseService is an autogenerated mock type for the IMerchantForbiddenUseCaseService type
type IMerchantForbiddenUseCaseService struct {
	mock.Mock
}

// BlockUseCase provides a mock function with given fields: ctx, request
func (_m *IMerchantForbiddenUseCaseService) BlockUseCase(ctx context.Context, request *merchantForbiddenUsecase.MerchantForbiddenUseCaseRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for BlockUseCase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchantForbiddenUsecase.MerchantForbiddenUseCaseRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckUseCase provides a mock function with given fields: ctx, merchantId, useCase
func (_m *IMerchantForbiddenUseCaseService) CheckUseCase(ctx context.Context, merchantId string, useCase string) error {
	ret := _m.Called(ctx, merchantId, useCase)

	if len(ret) == 0 {
		panic("no return value specified for CheckUseCase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, merchantId, useCase)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnblockUseCase provides a mock function with given fields: ctx, request
func (_m *IMerchantForbiddenUseCaseService) UnblockUseCase(ctx context.Context, request *merchantForbiddenUsecase.MerchantForbiddenUseCaseRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UnblockUseCase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchantForbiddenUsecase.MerchantForbiddenUseCaseRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMerchantForbiddenUseCaseService creates a new instance of IMerchantForbiddenUseCaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMerchantForbiddenUseCaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMerchantForbiddenUseCaseService {
	mock := &IMerchantForbiddenUseCaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
