// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	constant "github.com/paper-indonesia/pivot-backoffice/constant"

	mock "github.com/stretchr/testify/mock"

	otp "github.com/paper-indonesia/pivot-backoffice/internal/model/otp"
)

// IOTPGenerator is an autogenerated mock type for the IOTPGenerator type
type IOTPGenerator struct {
	mock.Mock
}

// GenerateOTPCode provides a mock function with given fields: ctx, id, email, feature
func (_m *IOTPGenerator) GenerateOTPCode(ctx context.Context, id string, email string, feature constant.OTPIdentifier) (string, error) {
	ret := _m.Called(ctx, id, email, feature)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTPCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, constant.OTPIdentifier) (string, error)); ok {
		return rf(ctx, id, email, feature)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, constant.OTPIdentifier) string); ok {
		r0 = rf(ctx, id, email, feature)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, constant.OTPIdentifier) error); ok {
		r1 = rf(ctx, id, email, feature)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateTOTPVerifyToken provides a mock function with given fields: ctx, request
func (_m *IOTPGenerator) GenerateTOTPVerifyToken(ctx context.Context, request otp.GenerateTOTPVerifyTokenRequest) (string, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTOTPVerifyToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, otp.GenerateTOTPVerifyTokenRequest) (string, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, otp.GenerateTOTPVerifyTokenRequest) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, otp.GenerateTOTPVerifyTokenRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOTPGenerator creates a new instance of IOTPGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOTPGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOTPGenerator {
	mock := &IOTPGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
