// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	permissionModel "github.com/paper-indonesia/pivot-backoffice/internal/model/permission"
	mock "github.com/stretchr/testify/mock"
)

// IPermissionService is an autogenerated mock type for the IPermissionService type
type IPermissionService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, permission
func (_m *IPermissionService) Create(ctx context.Context, permission *permissionModel.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *permissionModel.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByRoleId provides a mock function with given fields: ctx, roleId
func (_m *IPermissionService) FindByRoleId(ctx context.Context, roleId string) ([]*permissionModel.Permission, error) {
	ret := _m.Called(ctx, roleId)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoleId")
	}

	var r0 []*permissionModel.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*permissionModel.Permission, error)); ok {
		return rf(ctx, roleId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*permissionModel.Permission); ok {
		r0 = rf(ctx, roleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*permissionModel.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySlug provides a mock function with given fields: ctx, slug
func (_m *IPermissionService) FindBySlug(ctx context.Context, slug string) (*permissionModel.Permission, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *permissionModel.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*permissionModel.Permission, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *permissionModel.Permission); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*permissionModel.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCachedPermissionsByRoleId provides a mock function with given fields: ctx, roleId
func (_m *IPermissionService) GetCachedPermissionsByRoleId(ctx context.Context, roleId string) ([]string, error) {
	ret := _m.Called(ctx, roleId)

	if len(ret) == 0 {
		panic("no return value specified for GetCachedPermissionsByRoleId")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, roleId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, roleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, permission
func (_m *IPermissionService) Update(ctx context.Context, permission *permissionModel.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *permissionModel.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIPermissionService creates a new instance of IPermissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPermissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPermissionService {
	mock := &IPermissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
