// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	requestAccountInquiries "github.com/paper-indonesia/pivot-backoffice/internal/model/requestAccountInquiry"
	mock "github.com/stretchr/testify/mock"
)

// IRequestAccountInquiryService is an autogenerated mock type for the IRequestAccountInquiryService type
type IRequestAccountInquiryService struct {
	mock.Mock
}

// FindLatestByInquiryID provides a mock function with given fields: ctx, inquiryID, merchantID
func (_m *IRequestAccountInquiryService) FindLatestByInquiryID(ctx context.Context, inquiryID string, merchantID string) (*requestAccountInquiries.RequestAccountInquiryWithMaster, error) {
	ret := _m.Called(ctx, inquiryID, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestByInquiryID")
	}

	var r0 *requestAccountInquiries.RequestAccountInquiryWithMaster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*requestAccountInquiries.RequestAccountInquiryWithMaster, error)); ok {
		return rf(ctx, inquiryID, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *requestAccountInquiries.RequestAccountInquiryWithMaster); ok {
		r0 = rf(ctx, inquiryID, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*requestAccountInquiries.RequestAccountInquiryWithMaster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, inquiryID, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestAccountInquiry provides a mock function with given fields: ctx, req
func (_m *IRequestAccountInquiryService) RequestAccountInquiry(ctx context.Context, req requestAccountInquiries.RequestAccountInquiriesHttpRequest) (*requestAccountInquiries.RequestAccountInquiriesHttpResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RequestAccountInquiry")
	}

	var r0 *requestAccountInquiries.RequestAccountInquiriesHttpResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requestAccountInquiries.RequestAccountInquiriesHttpRequest) (*requestAccountInquiries.RequestAccountInquiriesHttpResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requestAccountInquiries.RequestAccountInquiriesHttpRequest) *requestAccountInquiries.RequestAccountInquiriesHttpResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*requestAccountInquiries.RequestAccountInquiriesHttpResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, requestAccountInquiries.RequestAccountInquiriesHttpRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIRequestAccountInquiryService creates a new instance of IRequestAccountInquiryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRequestAccountInquiryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRequestAccountInquiryService {
	mock := &IRequestAccountInquiryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
