// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	commonModel "github.com/paper-indonesia/pivot-backoffice/internal/model/common"

	mock "github.com/stretchr/testify/mock"

	user "github.com/paper-indonesia/pivot-backoffice/internal/model/user"
)

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

// ActivateUser provides a mock function with given fields: ctx, request
func (_m *IUserService) ActivateUser(ctx context.Context, request *user.ActivateUserRequest) (*user.UserLoggedInResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ActivateUser")
	}

	var r0 *user.UserLoggedInResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.ActivateUserRequest) (*user.UserLoggedInResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.ActivateUserRequest) *user.UserLoggedInResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserLoggedInResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.ActivateUserRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangePassword provides a mock function with given fields: ctx, userID, OldPassword, NewPassword
func (_m *IUserService) ChangePassword(ctx context.Context, userID string, OldPassword string, NewPassword string) (*user.ChangePasswordResponse, error) {
	ret := _m.Called(ctx, userID, OldPassword, NewPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 *user.ChangePasswordResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*user.ChangePasswordResponse, error)); ok {
		return rf(ctx, userID, OldPassword, NewPassword)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *user.ChangePasswordResponse); ok {
		r0 = rf(ctx, userID, OldPassword, NewPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.ChangePasswordResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, OldPassword, NewPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangePin provides a mock function with given fields: ctx, userID, pin, newPin
func (_m *IUserService) ChangePin(ctx context.Context, userID string, pin string, newPin string) error {
	ret := _m.Called(ctx, userID, pin, newPin)

	if len(ret) == 0 {
		panic("no return value specified for ChangePin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, pin, newPin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckCurrentPassword provides a mock function with given fields: ctx, userID, password
func (_m *IUserService) CheckCurrentPassword(ctx context.Context, userID string, password string) error {
	ret := _m.Called(ctx, userID, password)

	if len(ret) == 0 {
		panic("no return value specified for CheckCurrentPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckCurrentPin provides a mock function with given fields: ctx, userID, pin
func (_m *IUserService) CheckCurrentPin(ctx context.Context, userID string, pin string) error {
	ret := _m.Called(ctx, userID, pin)

	if len(ret) == 0 {
		panic("no return value specified for CheckCurrentPin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, pin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmTOTP provides a mock function with given fields: ctx, request
func (_m *IUserService) ConfirmTOTP(ctx context.Context, request user.ConfirmTOTPRequest) (bool, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmTOTP")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.ConfirmTOTPRequest) (bool, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.ConfirmTOTPRequest) bool); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.ConfirmTOTPRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *IUserService) Create(ctx context.Context, _a1 *user.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMerchantUser provides a mock function with given fields: ctx, req
func (_m *IUserService) CreateMerchantUser(ctx context.Context, req *user.MerchantUserRequest) (*user.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMerchantUser")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.MerchantUserRequest) (*user.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.MerchantUserRequest) *user.User); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.MerchantUserRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePin provides a mock function with given fields: ctx, userID, pin
func (_m *IUserService) CreatePin(ctx context.Context, userID string, pin string) error {
	ret := _m.Called(ctx, userID, pin)

	if len(ret) == 0 {
		panic("no return value specified for CreatePin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, pin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnrollTOTP provides a mock function with given fields: ctx, request
func (_m *IUserService) EnrollTOTP(ctx context.Context, request user.EnrollTOTPRequest) (*user.EnrollTOTPResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for EnrollTOTP")
	}

	var r0 *user.EnrollTOTPResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.EnrollTOTPRequest) (*user.EnrollTOTPResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.EnrollTOTPRequest) *user.EnrollTOTPResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.EnrollTOTPResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.EnrollTOTPRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *IUserService) FindUserByEmail(ctx context.Context, email string) (*user.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByID provides a mock function with given fields: ctx, id
func (_m *IUserService) FindUserByID(ctx context.Context, id string) (*user.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserTOTPDataByID provides a mock function with given fields: ctx, userId
func (_m *IUserService) FindUserTOTPDataByID(ctx context.Context, userId string) (*user.UserTOTPData, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for FindUserTOTPDataByID")
	}

	var r0 *user.UserTOTPData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.UserTOTPData, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.UserTOTPData); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserTOTPData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ForgotPassword provides a mock function with given fields: ctx, email
func (_m *IUserService) ForgotPassword(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateRandomPassword provides a mock function with given fields: ctx, userData
func (_m *IUserService) GenerateRandomPassword(ctx context.Context, userData *user.User) (*user.GenerateRandomPasswordResponse, error) {
	ret := _m.Called(ctx, userData)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRandomPassword")
	}

	var r0 *user.GenerateRandomPasswordResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) (*user.GenerateRandomPasswordResponse, error)); ok {
		return rf(ctx, userData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) *user.GenerateRandomPasswordResponse); ok {
		r0 = rf(ctx, userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.GenerateRandomPasswordResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.User) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateTokenFromLogin2FA provides a mock function with given fields: ctx, id
func (_m *IUserService) GenerateTokenFromLogin2FA(ctx context.Context, id string) (*user.User, string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenFromLogin2FA")
	}

	var r0 *user.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetInvitationURL provides a mock function with given fields: ctx, merchantId, email
func (_m *IUserService) GetInvitationURL(ctx context.Context, merchantId string, email string) (string, error) {
	ret := _m.Called(ctx, merchantId, email)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitationURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, merchantId, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, merchantId, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx, limit, offset
func (_m *IUserService) ListUsers(ctx context.Context, limit int, offset int) ([]*user.User, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*user.User, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*user.User); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsersByMerchantID provides a mock function with given fields: ctx, filter, page, perPage
func (_m *IUserService) ListUsersByMerchantID(ctx context.Context, filter *user.ListUsersByMerchantIDRequest, page int64, perPage int64) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersByMerchantID")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.ListUsersByMerchantIDRequest, int64, int64) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.ListUsersByMerchantIDRequest, int64, int64) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.ListUsersByMerchantIDRequest, int64, int64) error); ok {
		r1 = rf(ctx, filter, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, request
func (_m *IUserService) Login(ctx context.Context, request *user.UserLoginRequest) (*user.User, string, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *user.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserLoginRequest) (*user.User, string, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserLoginRequest) *user.User); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.UserLoginRequest) string); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *user.UserLoginRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LoginWithOTP provides a mock function with given fields: ctx, email, password
func (_m *IUserService) LoginWithOTP(ctx context.Context, email string, password string) (string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithOTP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, email
func (_m *IUserService) Logout(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Refresh provides a mock function with given fields: ctx, email, refreshToken
func (_m *IUserService) Refresh(ctx context.Context, email string, refreshToken string) (*user.User, string, error) {
	ret := _m.Called(ctx, email, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *user.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*user.User, string, error)); ok {
		return rf(ctx, email, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *user.User); ok {
		r0 = rf(ctx, email, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, refreshToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ResetPIN provides a mock function with given fields: ctx, id, pin
func (_m *IUserService) ResetPIN(ctx context.Context, id string, pin string) error {
	ret := _m.Called(ctx, id, pin)

	if len(ret) == 0 {
		panic("no return value specified for ResetPIN")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, pin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetPassword provides a mock function with given fields: ctx, id, password
func (_m *IUserService) ResetPassword(ctx context.Context, id string, password string) error {
	ret := _m.Called(ctx, id, password)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendGeneratedInvitationURL provides a mock function with given fields: ctx, request
func (_m *IUserService) SendGeneratedInvitationURL(ctx context.Context, request *user.SendGeneratedInvitationRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SendGeneratedInvitationURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.SendGeneratedInvitationRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPreferred2FAMethod provides a mock function with given fields: ctx, request
func (_m *IUserService) SetPreferred2FAMethod(ctx context.Context, request user.SetPreferred2FAMethodRequest) (*user.SetPreferred2FAMethodResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SetPreferred2FAMethod")
	}

	var r0 *user.SetPreferred2FAMethodResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.SetPreferred2FAMethodRequest) (*user.SetPreferred2FAMethodResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.SetPreferred2FAMethodRequest) *user.SetPreferred2FAMethodResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.SetPreferred2FAMethodResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.SetPreferred2FAMethodRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnblockUser provides a mock function with given fields: ctx, email
func (_m *IUserService) UnblockUser(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UnblockUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *IUserService) Update(ctx context.Context, _a1 *user.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserDetail provides a mock function with given fields: ctx, id
func (_m *IUserService) UserDetail(ctx context.Context, id string) (*user.UserResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserDetail")
	}

	var r0 *user.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.UserResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.UserResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateInvitationToken provides a mock function with given fields: ctx, token
func (_m *IUserService) ValidateInvitationToken(ctx context.Context, token string) (*user.ValidateInvitationResponse, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateInvitationToken")
	}

	var r0 *user.ValidateInvitationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.ValidateInvitationResponse, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.ValidateInvitationResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.ValidateInvitationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserService {
	mock := &IUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
