package schemas

func Merchant() string {
	return `CREATE TABLE merchants (
		uuid varchar(255) NOT NULL,
		external_id varchar(26) NOT NULL,
		name varchar(255) NOT NULL,
		short_name varchar(30) NOT NULL,
		description text,
		website varchar(255) DEFAULT '',
		address varchar(254) NOT NULL,
		district_id smallint NOT NULL,
		postcode varchar(20) NOT NULL,
		logo varchar(255) NOT NULL,
		merchant_email varchar(255) NOT NULL,
		merchant_phone varchar(255) NOT NULL,
		pic_email varchar(255) NOT NULL,
		pic_phone varchar(255) NOT NULL,
		mid varchar(4) DEFAULT NULL,
		callback_api_key varchar(255) DEFAULT NULL,
		callback_api_key_version smallint unsigned NOT NULL DEFAULT '0',
		jit_api_key varchar(255) DEFAULT NULL,
		jit_api_key_version smallint unsigned NOT NULL DEFAULT '0',
		transaction_configs json NOT NULL DEFAULT (_utf8mb3'{"autoWithdrawal":"ON"}'),
		fds_configs json DEFAULT NULL,
		status varchar(20) NOT NULL DEFAULT 'ACTIVE',
		risk_level varchar(60) DEFAULT NULL,
		reason_status varchar(255) NOT NULL DEFAULT '',
		created_at timestamp NOT NULL,
		updated_at timestamp NULL DEFAULT NULL,
		deleted_at timestamp NULL DEFAULT NULL,
		parent_id varchar(36) DEFAULT NULL,
		business_country varchar(20) DEFAULT NULL,
		business_structure varchar(20) DEFAULT NULL,
		business_type varchar(20) DEFAULT NULL,
		pic_job_title varchar(20) DEFAULT NULL,
		pic_name varchar(32) DEFAULT NULL,
		kyc_status varchar(50) DEFAULT NULL,
		parent_industry varchar(255) DEFAULT NULL,
		child_industry varchar(255) DEFAULT NULL,
		mcc varchar(255) DEFAULT NULL,
		country_of_entity varchar(255) DEFAULT NULL,
		digital_status varchar(255) DEFAULT NULL,
		third_party_screening_data json DEFAULT NULL,
		metadata json DEFAULT NULL,
		PRIMARY KEY (uuid),
		UNIQUE KEY merchant_unique_mid (mid),
		KEY idx_merchants_parent_id (parent_id),
		KEY merchants_external_id_idx (external_id),
		KEY merchants_status_idx (status) USING BTREE
	);`
}
