// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	encrypt "github.com/paper-indonesia/pdk/v2/encrypt"
	mock "github.com/stretchr/testify/mock"
)

// Encrypter is an autogenerated mock type for the Encrypter type
type Encrypter struct {
	mock.Mock
}

// Base64 provides a mock function with no fields
func (_m *Encrypter) Base64() encrypt.Base64Encrypter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Base64")
	}

	var r0 encrypt.Base64Encrypter
	if rf, ok := ret.Get(0).(func() encrypt.Base64Encrypter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(encrypt.Base64Encrypter)
		}
	}

	return r0
}

// Decrypt provides a mock function with given fields: ciphertext
func (_m *Encrypter) Decrypt(ciphertext string) ([]byte, error) {
	ret := _m.Called(ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(ciphertext)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(ciphertext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ciphertext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encrypt provides a mock function with given fields: plaintext
func (_m *Encrypter) Encrypt(plaintext string) ([]byte, error) {
	ret := _m.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(plaintext)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEncrypter creates a new instance of Encrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Encrypter {
	mock := &Encrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
