package constant

const (
	PAYMENT_METHOD_VIRTUAL_ACCOUNT  = "VIRTUAL_ACCOUNT"
	PAYMENT_METHOD_BANK_TRANSFER    = "BANK_TRANSFER"
	PAYMENT_METHOD_CREDIT_CARD      = "CREDIT_CARD"
	PAYMENT_METHOD_QRIS             = "QRIS"
	PAYMENT_METHOD_EWALLET          = "EWALLET"
	PAYMENT_METHOD_INSTALLMENT      = "INSTALLMENT"
	PAYMENT_METHOD_VIRTUAL_TERMINAL = "VIRTUAL_TERMINAL"

	PAYMENT_METHOD_CARD_FUNDED_PAYOUT        = "CARD_FUNDED_PAYOUT"
	PAYMENT_METHOD_CREDIT_CARD_SPLIT_PAYMENT = "SPLIT_PAYMENT"

	PAYMENT_METHOD_EWALLET_CHANNEL_SHOPEEPAY = "SHOPEEPAY"
	PAYMENT_METHOD_EWALLET_CHANNEL_DANA      = "DANA"

	PAYMENT_METHOD_QRIS_ACQUIRER_BNC = "BNC"
	PAYMENT_METHOD_QRIS_ACQUIRER_BRI = "BRI"
	PAYMENT_METHOD_QRIS_ACQUIRER_BNI = "BNI"

	PAYMENT_METHOD_CATEGORY_DISBURSEMENT_TOPUP = "DISBURSEMENT_TOP_UP"
	PAYMENT_METHOD_CATEGORY_MERCHANT_TOPUP     = "MERCHANT_TOP_UP"
	PAYMENT_METHOD_CATEGORY_PAYMENT            = "PAYMENT"
)

// virtual account trx type
const (
	VIRTUAL_ACCOUNT_TRX_TYPE_CLOSED_STATIC  = "CLOSED_STATIC"
	VIRTUAL_ACCOUNT_TRX_TYPE_OPEN_STATIC    = "OPEN_STATIC"
	VIRTUAL_ACCOUNT_TRX_TYPE_CLOSED_DYNAMIC = "CLOSED_DYNAMIC"

	VIRTUAL_ACCOUNT_TRX_PURPOSE_TOPUP_BALANCE = "topup-balance"
)

const (
	VIRTUAL_ACCOUNT_MINIMUM_AMOUNT = 10000

	VIRTUAL_ACCOUNT_NUMBER_MERCHANT_LENGTH = 8
)

const (
	UnifiedPaymentExpiryModePartial = "PARTIAL"
	UnifiedPaymentExpiryModeFull    = "FULL"
	UnifiedPaymentExpiryModeOff     = "OFF"
	UnifiedPaymentExpiryUnitMinutes = "MINUTES"
	UnifiedPaymentExpiryUnitHours   = "HOURS"
	UnifiedPaymentExpiryUnitDays    = "DAYS"
)
