// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	commonModel "github.com/paper-indonesia/pivot-backoffice/internal/model/common"

	fdscommon "github.com/paper-indonesia/pivot-backoffice/internal/model/fdsProcessor/fdsCommon"

	ledger_model "github.com/paper-indonesia/pivot-backoffice/internal/model/ledger"

	mock "github.com/stretchr/testify/mock"

	orchestrator_model "github.com/paper-indonesia/pivot-backoffice/internal/model/orchestrator"

	reconciliation "github.com/paper-indonesia/pivot-backoffice/internal/model/reconciliation"

	time "time"

	types "github.com/jmoiron/sqlx/types"
)

// IAccountTransactionRepository is an autogenerated mock type for the IAccountTransactionRepository type
type IAccountTransactionRepository struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields: ctx
func (_m *IAccountTransactionRepository) BeginTransaction(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BulkInsert provides a mock function with given fields: ctx, accountTransactions
func (_m *IAccountTransactionRepository) BulkInsert(ctx context.Context, accountTransactions []*orchestrator_model.AccountTransaction) error {
	ret := _m.Called(ctx, accountTransactions)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*orchestrator_model.AccountTransaction) error); ok {
		r0 = rf(ctx, accountTransactions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkUpdateTransactions provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) BulkUpdateTransactions(ctx context.Context, request []*orchestrator_model.AccountTransaction) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdateTransactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*orchestrator_model.AccountTransaction) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CalculatePendingBalance provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) CalculatePendingBalance(ctx context.Context, request *orchestrator_model.GetAggregateRequest) (float64, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CalculatePendingBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetAggregateRequest) (float64, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetAggregateRequest) float64); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orchestrator_model.GetAggregateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculatingMerchantTPVForLadderTiering provides a mock function with given fields: ctx, merchantId, startDate, endDate
func (_m *IAccountTransactionRepository) CalculatingMerchantTPVForLadderTiering(ctx context.Context, merchantId string, startDate time.Time, endDate time.Time) (map[string]orchestrator_model.CalculatingMerchantTPVSummary, error) {
	ret := _m.Called(ctx, merchantId, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for CalculatingMerchantTPVForLadderTiering")
	}

	var r0 map[string]orchestrator_model.CalculatingMerchantTPVSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (map[string]orchestrator_model.CalculatingMerchantTPVSummary, error)); ok {
		return rf(ctx, merchantId, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) map[string]orchestrator_model.CalculatingMerchantTPVSummary); ok {
		r0 = rf(ctx, merchantId, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]orchestrator_model.CalculatingMerchantTPVSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, merchantId, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculatingMerchantTPVToDetermineFeeTierLevel provides a mock function with given fields: ctx, merchantId, startDate, endDate
func (_m *IAccountTransactionRepository) CalculatingMerchantTPVToDetermineFeeTierLevel(ctx context.Context, merchantId string, startDate time.Time, endDate time.Time) (map[string]orchestrator_model.CalculatingMerchantTPVSummary, error) {
	ret := _m.Called(ctx, merchantId, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for CalculatingMerchantTPVToDetermineFeeTierLevel")
	}

	var r0 map[string]orchestrator_model.CalculatingMerchantTPVSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (map[string]orchestrator_model.CalculatingMerchantTPVSummary, error)); ok {
		return rf(ctx, merchantId, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) map[string]orchestrator_model.CalculatingMerchantTPVSummary); ok {
		r0 = rf(ctx, merchantId, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]orchestrator_model.CalculatingMerchantTPVSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, merchantId, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculatingTPVForPlatformActivitiesToDetermineFeeTierLevel provides a mock function with given fields: ctx, merchantIds, startDate, endDate
func (_m *IAccountTransactionRepository) CalculatingTPVForPlatformActivitiesToDetermineFeeTierLevel(ctx context.Context, merchantIds []string, startDate time.Time, endDate time.Time) (map[string]orchestrator_model.CalculatingMerchantTPVSummary, error) {
	ret := _m.Called(ctx, merchantIds, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for CalculatingTPVForPlatformActivitiesToDetermineFeeTierLevel")
	}

	var r0 map[string]orchestrator_model.CalculatingMerchantTPVSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time) (map[string]orchestrator_model.CalculatingMerchantTPVSummary, error)); ok {
		return rf(ctx, merchantIds, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time) map[string]orchestrator_model.CalculatingMerchantTPVSummary); ok {
		r0 = rf(ctx, merchantIds, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]orchestrator_model.CalculatingMerchantTPVSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, merchantIds, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelIndirectTransactionFee provides a mock function with given fields: ctx, id, date
func (_m *IAccountTransactionRepository) CancelIndirectTransactionFee(ctx context.Context, id string, date time.Time) error {
	ret := _m.Called(ctx, id, date)

	if len(ret) == 0 {
		panic("no return value specified for CancelIndirectTransactionFee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommitTransaction provides a mock function with given fields: ctx
func (_m *IAccountTransactionRepository) CommitTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, accountTransaction
func (_m *IAccountTransactionRepository) Create(ctx context.Context, accountTransaction *orchestrator_model.AccountTransaction) error {
	ret := _m.Called(ctx, accountTransaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.AccountTransaction) error); ok {
		r0 = rf(ctx, accountTransaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeductBalanceForIndirectFeeType provides a mock function with given fields: ctx, merchantId, ids
func (_m *IAccountTransactionRepository) DeductBalanceForIndirectFeeType(ctx context.Context, merchantId string, ids []string) error {
	ret := _m.Called(ctx, merchantId, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeductBalanceForIndirectFeeType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, merchantId, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *IAccountTransactionRepository) FindByID(ctx context.Context, id string) (*orchestrator_model.AccountTransactionWithUseCase, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *orchestrator_model.AccountTransactionWithUseCase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*orchestrator_model.AccountTransactionWithUseCase, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *orchestrator_model.AccountTransactionWithUseCase); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orchestrator_model.AccountTransactionWithUseCase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByReference provides a mock function with given fields: ctx, referenceID, referenceType
func (_m *IAccountTransactionRepository) FindByReference(ctx context.Context, referenceID string, referenceType string) (*orchestrator_model.AccountTransactionWithUseCase, error) {
	ret := _m.Called(ctx, referenceID, referenceType)

	if len(ret) == 0 {
		panic("no return value specified for FindByReference")
	}

	var r0 *orchestrator_model.AccountTransactionWithUseCase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*orchestrator_model.AccountTransactionWithUseCase, error)); ok {
		return rf(ctx, referenceID, referenceType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *orchestrator_model.AccountTransactionWithUseCase); ok {
		r0 = rf(ctx, referenceID, referenceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orchestrator_model.AccountTransactionWithUseCase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, referenceID, referenceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLastMerchantTransactionDate provides a mock function with given fields: ctx, merchantID
func (_m *IAccountTransactionRepository) FindLastMerchantTransactionDate(ctx context.Context, merchantID string) (*time.Time, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for FindLastMerchantTransactionDate")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*time.Time, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *time.Time); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccumulateTransactionFees provides a mock function with given fields: ctx, merchantId, reference, method, startDate, endDate
func (_m *IAccountTransactionRepository) GetAccumulateTransactionFees(ctx context.Context, merchantId string, reference string, method string, startDate time.Time, endDate time.Time) (*orchestrator_model.AccumulateTransactionFees, error) {
	ret := _m.Called(ctx, merchantId, reference, method, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAccumulateTransactionFees")
	}

	var r0 *orchestrator_model.AccumulateTransactionFees
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) (*orchestrator_model.AccumulateTransactionFees, error)); ok {
		return rf(ctx, merchantId, reference, method, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) *orchestrator_model.AccumulateTransactionFees); ok {
		r0 = rf(ctx, merchantId, reference, method, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orchestrator_model.AccumulateTransactionFees)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, merchantId, reference, method, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAggregateTransactionByReference provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) GetAggregateTransactionByReference(ctx context.Context, request *orchestrator_model.GetSummaryTransactionByReferenceRequest) (*orchestrator_model.AggregateResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregateTransactionByReference")
	}

	var r0 *orchestrator_model.AggregateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetSummaryTransactionByReferenceRequest) (*orchestrator_model.AggregateResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetSummaryTransactionByReferenceRequest) *orchestrator_model.AggregateResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orchestrator_model.AggregateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orchestrator_model.GetSummaryTransactionByReferenceRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAggregateTransactions provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) GetAggregateTransactions(ctx context.Context, request *orchestrator_model.GetAggregateRequest) (*orchestrator_model.AggregateResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregateTransactions")
	}

	var r0 *orchestrator_model.AggregateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetAggregateRequest) (*orchestrator_model.AggregateResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetAggregateRequest) *orchestrator_model.AggregateResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orchestrator_model.AggregateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orchestrator_model.GetAggregateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBulkAggregateTransactions provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) GetBulkAggregateTransactions(ctx context.Context, request *orchestrator_model.BulkGetAggregateRequest) ([]*orchestrator_model.BulkAggregateResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBulkAggregateTransactions")
	}

	var r0 []*orchestrator_model.BulkAggregateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.BulkGetAggregateRequest) ([]*orchestrator_model.BulkAggregateResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.BulkGetAggregateRequest) []*orchestrator_model.BulkAggregateResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*orchestrator_model.BulkAggregateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orchestrator_model.BulkGetAggregateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailById provides a mock function with given fields: ctx, merchantId, id
func (_m *IAccountTransactionRepository) GetDetailById(ctx context.Context, merchantId string, id string) (*orchestrator_model.TransactionHistoryDetailResp, error) {
	ret := _m.Called(ctx, merchantId, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailById")
	}

	var r0 *orchestrator_model.TransactionHistoryDetailResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*orchestrator_model.TransactionHistoryDetailResp, error)); ok {
		return rf(ctx, merchantId, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *orchestrator_model.TransactionHistoryDetailResp); ok {
		r0 = rf(ctx, merchantId, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orchestrator_model.TransactionHistoryDetailResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEarliestUpdatedAt provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) GetEarliestUpdatedAt(ctx context.Context, request *orchestrator_model.GetAggregateRequest) (time.Time, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetEarliestUpdatedAt")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetAggregateRequest) (time.Time, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetAggregateRequest) time.Time); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orchestrator_model.GetAggregateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastTransactionByAccountName provides a mock function with given fields: ctx, merchantId, accountName
func (_m *IAccountTransactionRepository) GetLastTransactionByAccountName(ctx context.Context, merchantId string, accountName string) (*time.Time, error) {
	ret := _m.Called(ctx, merchantId, accountName)

	if len(ret) == 0 {
		panic("no return value specified for GetLastTransactionByAccountName")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*time.Time, error)); ok {
		return rf(ctx, merchantId, accountName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *time.Time); ok {
		r0 = rf(ctx, merchantId, accountName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, accountName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLedgerDetail provides a mock function with given fields: ctx, referenceId
func (_m *IAccountTransactionRepository) GetLedgerDetail(ctx context.Context, referenceId string) ([]orchestrator_model.AccountTransaction, error) {
	ret := _m.Called(ctx, referenceId)

	if len(ret) == 0 {
		panic("no return value specified for GetLedgerDetail")
	}

	var r0 []orchestrator_model.AccountTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]orchestrator_model.AccountTransaction, error)); ok {
		return rf(ctx, referenceId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []orchestrator_model.AccountTransaction); ok {
		r0 = rf(ctx, referenceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]orchestrator_model.AccountTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, referenceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLedgerRecords provides a mock function with given fields: ctx, filter, pagination
func (_m *IAccountTransactionRepository) GetLedgerRecords(ctx context.Context, filter *ledger_model.GetLedgerTransactionRequest, pagination *commonModel.Meta) ([]*ledger_model.GetLedgerTransactionData, int, error) {
	ret := _m.Called(ctx, filter, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetLedgerRecords")
	}

	var r0 []*ledger_model.GetLedgerTransactionData
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *ledger_model.GetLedgerTransactionRequest, *commonModel.Meta) ([]*ledger_model.GetLedgerTransactionData, int, error)); ok {
		return rf(ctx, filter, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ledger_model.GetLedgerTransactionRequest, *commonModel.Meta) []*ledger_model.GetLedgerTransactionData); ok {
		r0 = rf(ctx, filter, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ledger_model.GetLedgerTransactionData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ledger_model.GetLedgerTransactionRequest, *commonModel.Meta) int); ok {
		r1 = rf(ctx, filter, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *ledger_model.GetLedgerTransactionRequest, *commonModel.Meta) error); ok {
		r2 = rf(ctx, filter, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetList provides a mock function with given fields: ctx, filter, page, perPage
func (_m *IAccountTransactionRepository) GetList(ctx context.Context, filter *orchestrator_model.TransactionHistoryFilterRequest, page int64, perPage int64) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.TransactionHistoryFilterRequest, int64, int64) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.TransactionHistoryFilterRequest, int64, int64) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orchestrator_model.TransactionHistoryFilterRequest, int64, int64) error); ok {
		r1 = rf(ctx, filter, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListOfTransactionReferenceIdsWithPendingStatus provides a mock function with given fields: ctx, merchantId, accountId, startTime, endTime
func (_m *IAccountTransactionRepository) GetListOfTransactionReferenceIdsWithPendingStatus(ctx context.Context, merchantId string, accountId string, startTime time.Time, endTime time.Time) ([]string, error) {
	ret := _m.Called(ctx, merchantId, accountId, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetListOfTransactionReferenceIdsWithPendingStatus")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) ([]string, error)); ok {
		return rf(ctx, merchantId, accountId, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) []string); ok {
		r0 = rf(ctx, merchantId, accountId, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, merchantId, accountId, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListTransactionHistories provides a mock function with given fields: ctx, filter
func (_m *IAccountTransactionRepository) GetListTransactionHistories(ctx context.Context, filter *orchestrator_model.TransactionHistoryFilterRequest) ([]orchestrator_model.TransactionHistory, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetListTransactionHistories")
	}

	var r0 []orchestrator_model.TransactionHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.TransactionHistoryFilterRequest) ([]orchestrator_model.TransactionHistory, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.TransactionHistoryFilterRequest) []orchestrator_model.TransactionHistory); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]orchestrator_model.TransactionHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orchestrator_model.TransactionHistoryFilterRequest) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPastDueSettlementTransactions provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) GetPastDueSettlementTransactions(ctx context.Context, request *orchestrator_model.GetPastDueSettlementTransactionsRequest) ([]*orchestrator_model.AccountTransaction, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetPastDueSettlementTransactions")
	}

	var r0 []*orchestrator_model.AccountTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetPastDueSettlementTransactionsRequest) ([]*orchestrator_model.AccountTransaction, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetPastDueSettlementTransactionsRequest) []*orchestrator_model.AccountTransaction); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*orchestrator_model.AccountTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orchestrator_model.GetPastDueSettlementTransactionsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlatformTransactionActivities provides a mock function with given fields: ctx, ids, startDate, endDate
func (_m *IAccountTransactionRepository) GetPlatformTransactionActivities(ctx context.Context, ids []string, startDate time.Time, endDate time.Time) ([]orchestrator_model.TransactionActivity, error) {
	ret := _m.Called(ctx, ids, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetPlatformTransactionActivities")
	}

	var r0 []orchestrator_model.TransactionActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time) ([]orchestrator_model.TransactionActivity, error)); ok {
		return rf(ctx, ids, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time) []orchestrator_model.TransactionActivity); ok {
		r0 = rf(ctx, ids, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]orchestrator_model.TransactionActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, ids, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReferenceIdByTransactionIdAndType provides a mock function with given fields: ctx, transactionId, transactionType
func (_m *IAccountTransactionRepository) GetReferenceIdByTransactionIdAndType(ctx context.Context, transactionId string, transactionType string) (string, error) {
	ret := _m.Called(ctx, transactionId, transactionType)

	if len(ret) == 0 {
		panic("no return value specified for GetReferenceIdByTransactionIdAndType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, transactionId, transactionType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, transactionId, transactionType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, transactionId, transactionType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalPaymentAmount provides a mock function with given fields: ctx, params
func (_m *IAccountTransactionRepository) GetTotalPaymentAmount(ctx context.Context, params *reconciliation.PaymentTotalAmountQuery) (*reconciliation.PaymentTotalAmountResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalPaymentAmount")
	}

	var r0 *reconciliation.PaymentTotalAmountResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconciliation.PaymentTotalAmountQuery) (*reconciliation.PaymentTotalAmountResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reconciliation.PaymentTotalAmountQuery) *reconciliation.PaymentTotalAmountResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reconciliation.PaymentTotalAmountResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reconciliation.PaymentTotalAmountQuery) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByProcessorID provides a mock function with given fields: ctx, trxType, processor, processorID
func (_m *IAccountTransactionRepository) GetTransactionByProcessorID(ctx context.Context, trxType string, processor string, processorID string) (*reconciliation.ReconTransactionModel, error) {
	ret := _m.Called(ctx, trxType, processor, processorID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByProcessorID")
	}

	var r0 *reconciliation.ReconTransactionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*reconciliation.ReconTransactionModel, error)); ok {
		return rf(ctx, trxType, processor, processorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *reconciliation.ReconTransactionModel); ok {
		r0 = rf(ctx, trxType, processor, processorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reconciliation.ReconTransactionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, trxType, processor, processorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByReferenceIdAndProcessorId provides a mock function with given fields: ctx, referenceId, processorId
func (_m *IAccountTransactionRepository) GetTransactionByReferenceIdAndProcessorId(ctx context.Context, referenceId string, processorId string) (*orchestrator_model.AccountTransaction, error) {
	ret := _m.Called(ctx, referenceId, processorId)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByReferenceIdAndProcessorId")
	}

	var r0 *orchestrator_model.AccountTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*orchestrator_model.AccountTransaction, error)); ok {
		return rf(ctx, referenceId, processorId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *orchestrator_model.AccountTransaction); ok {
		r0 = rf(ctx, referenceId, processorId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orchestrator_model.AccountTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, referenceId, processorId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionForRecon provides a mock function with given fields: ctx, params
func (_m *IAccountTransactionRepository) GetTransactionForRecon(ctx context.Context, params *reconciliation.ReconTransactionQuery) (*reconciliation.ReconTransactionModel, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionForRecon")
	}

	var r0 *reconciliation.ReconTransactionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconciliation.ReconTransactionQuery) (*reconciliation.ReconTransactionModel, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reconciliation.ReconTransactionQuery) *reconciliation.ReconTransactionModel); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reconciliation.ReconTransactionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reconciliation.ReconTransactionQuery) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletCustomersTotalBalance provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) GetWalletCustomersTotalBalance(ctx context.Context, request *orchestrator_model.GetWalletTotalBalanceRequest) (float64, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletCustomersTotalBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetWalletTotalBalanceRequest) (float64, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.GetWalletTotalBalanceRequest) float64); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orchestrator_model.GetWalletTotalBalanceRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RearrangeUpdatedAtForTransactionWithPendingStatus provides a mock function with given fields: ctx, referenceIds, updatedAt
func (_m *IAccountTransactionRepository) RearrangeUpdatedAtForTransactionWithPendingStatus(ctx context.Context, referenceIds []string, updatedAt time.Time) error {
	ret := _m.Called(ctx, referenceIds, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for RearrangeUpdatedAtForTransactionWithPendingStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time) error); ok {
		r0 = rf(ctx, referenceIds, updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollbackTransaction provides a mock function with given fields: ctx
func (_m *IAccountTransactionRepository) RollbackTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAdditionalInfoReconciliation provides a mock function with given fields: ctx, id, params
func (_m *IAccountTransactionRepository) SetAdditionalInfoReconciliation(ctx context.Context, id string, params *reconciliation.ReconDetail) error {
	ret := _m.Called(ctx, id, params)

	if len(ret) == 0 {
		panic("no return value specified for SetAdditionalInfoReconciliation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *reconciliation.ReconDetail) error); ok {
		r0 = rf(ctx, id, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAdditionalInfoByID provides a mock function with given fields: ctx, id, additionalInfo
func (_m *IAccountTransactionRepository) UpdateAdditionalInfoByID(ctx context.Context, id string, additionalInfo types.NullJSONText) error {
	ret := _m.Called(ctx, id, additionalInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAdditionalInfoByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.NullJSONText) error); ok {
		r0 = rf(ctx, id, additionalInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBulkReconStatus provides a mock function with given fields: ctx, params
func (_m *IAccountTransactionRepository) UpdateBulkReconStatus(ctx context.Context, params *reconciliation.BulkUpatedStatus) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulkReconStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconciliation.BulkUpatedStatus) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCreditDebitByID provides a mock function with given fields: ctx, id, credit, debit
func (_m *IAccountTransactionRepository) UpdateCreditDebitByID(ctx context.Context, id string, credit *float64, debit *float64) error {
	ret := _m.Called(ctx, id, credit, debit)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCreditDebitByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *float64, *float64) error); ok {
		r0 = rf(ctx, id, credit, debit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateFDSRiskAssessmentResultByID provides a mock function with given fields: ctx, id, data
func (_m *IAccountTransactionRepository) UpdateFDSRiskAssessmentResultByID(ctx context.Context, id string, data fdscommon.RiskAssessmentResult) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFDSRiskAssessmentResultByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, fdscommon.RiskAssessmentResult) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentTransactionStatusAndMetadataByID provides a mock function with given fields: ctx, request, metadata
func (_m *IAccountTransactionRepository) UpdatePaymentTransactionStatusAndMetadataByID(ctx context.Context, request orchestrator_model.UpdatePaymentTransactionRequest, metadata orchestrator_model.MetadataPayment[interface{}]) error {
	ret := _m.Called(ctx, request, metadata)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentTransactionStatusAndMetadataByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, orchestrator_model.UpdatePaymentTransactionRequest, orchestrator_model.MetadataPayment[interface{}]) error); ok {
		r0 = rf(ctx, request, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProcessorAndReconReference provides a mock function with given fields: ctx, id, processorReferenceName, processorReferenceId, reconReferenceNo
func (_m *IAccountTransactionRepository) UpdateProcessorAndReconReference(ctx context.Context, id string, processorReferenceName string, processorReferenceId string, reconReferenceNo string) error {
	ret := _m.Called(ctx, id, processorReferenceName, processorReferenceId, reconReferenceNo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcessorAndReconReference")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, id, processorReferenceName, processorReferenceId, reconReferenceNo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateReasonOnly provides a mock function with given fields: ctx, id, reasonType, reasonDescription
func (_m *IAccountTransactionRepository) UpdateReasonOnly(ctx context.Context, id string, reasonType *string, reasonDescription *string) error {
	ret := _m.Called(ctx, id, reasonType, reasonDescription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReasonOnly")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) error); ok {
		r0 = rf(ctx, id, reasonType, reasonDescription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateReconDetail provides a mock function with given fields: ctx, id, params
func (_m *IAccountTransactionRepository) UpdateReconDetail(ctx context.Context, id string, params *reconciliation.ReconDetail) error {
	ret := _m.Called(ctx, id, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReconDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *reconciliation.ReconDetail) error); ok {
		r0 = rf(ctx, id, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSettlementDetailByIDs provides a mock function with given fields: ctx, ids, request
func (_m *IAccountTransactionRepository) UpdateSettlementDetailByIDs(ctx context.Context, ids []string, request orchestrator_model.UpdateSettlementDetailRequest) error {
	ret := _m.Called(ctx, ids, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettlementDetailByIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, orchestrator_model.UpdateSettlementDetailRequest) error); ok {
		r0 = rf(ctx, ids, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSettlementHoldByReferenceID provides a mock function with given fields: ctx, referenceId, flag
func (_m *IAccountTransactionRepository) UpdateSettlementHoldByReferenceID(ctx context.Context, referenceId string, flag bool) error {
	ret := _m.Called(ctx, referenceId, flag)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettlementHoldByReferenceID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, referenceId, flag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSettlementStatusAndSettlementAtByID provides a mock function with given fields: ctx, id, settlementStatus, settlementAt
func (_m *IAccountTransactionRepository) UpdateSettlementStatusAndSettlementAtByID(ctx context.Context, id string, settlementStatus string, settlementAt time.Time) error {
	ret := _m.Called(ctx, id, settlementStatus, settlementAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettlementStatusAndSettlementAtByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, id, settlementStatus, settlementAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusAccountTransaction provides a mock function with given fields: ctx, id, status, reasonType, reasonDescription
func (_m *IAccountTransactionRepository) UpdateStatusAccountTransaction(ctx context.Context, id string, status string, reasonType *string, reasonDescription *string) error {
	ret := _m.Called(ctx, id, status, reasonType, reasonDescription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusAccountTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, *string) error); ok {
		r0 = rf(ctx, id, status, reasonType, reasonDescription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusAccountTransactionByReferenceID provides a mock function with given fields: ctx, id, status, reasonType, reasonDescription
func (_m *IAccountTransactionRepository) UpdateStatusAccountTransactionByReferenceID(ctx context.Context, id string, status string, reasonType *string, reasonDescription *string) error {
	ret := _m.Called(ctx, id, status, reasonType, reasonDescription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusAccountTransactionByReferenceID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, *string) error); ok {
		r0 = rf(ctx, id, status, reasonType, reasonDescription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionDetail provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) UpdateTransactionDetail(ctx context.Context, request orchestrator_model.UpdateTransactionRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, orchestrator_model.UpdateTransactionRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionTimestamp provides a mock function with given fields: ctx, id, transactionTimestamp
func (_m *IAccountTransactionRepository) UpdateTransactionTimestamp(ctx context.Context, id string, transactionTimestamp time.Time) error {
	ret := _m.Called(ctx, id, transactionTimestamp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionTimestamp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, transactionTimestamp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionWithPendingStatusByReferenceIdTypeAndChannel provides a mock function with given fields: ctx, referenceId, typ, channel, data
func (_m *IAccountTransactionRepository) UpdateTransactionWithPendingStatusByReferenceIdTypeAndChannel(ctx context.Context, referenceId string, typ string, channel string, data orchestrator_model.UpdateTransactionWithPendingStatus) error {
	ret := _m.Called(ctx, referenceId, typ, channel, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionWithPendingStatusByReferenceIdTypeAndChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, orchestrator_model.UpdateTransactionWithPendingStatus) error); ok {
		r0 = rf(ctx, referenceId, typ, channel, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionsStatus provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) UpdateTransactionsStatus(ctx context.Context, request *ledger_model.UpdateLedgerEntryRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionsStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ledger_model.UpdateLedgerEntryRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionsStatusAndAdditionalInfoByID provides a mock function with given fields: ctx, id, status, reasonType, reasonDescription, additionalInfo
func (_m *IAccountTransactionRepository) UpdateTransactionsStatusAndAdditionalInfoByID(ctx context.Context, id string, status string, reasonType string, reasonDescription string, additionalInfo types.NullJSONText) error {
	ret := _m.Called(ctx, id, status, reasonType, reasonDescription, additionalInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionsStatusAndAdditionalInfoByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, types.NullJSONText) error); ok {
		r0 = rf(ctx, id, status, reasonType, reasonDescription, additionalInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VoidTransaction provides a mock function with given fields: ctx, request
func (_m *IAccountTransactionRepository) VoidTransaction(ctx context.Context, request *orchestrator_model.VoidTransactionRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for VoidTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *orchestrator_model.VoidTransactionRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAccountTransactionRepository creates a new instance of IAccountTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAccountTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAccountTransactionRepository {
	mock := &IAccountTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
