// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	account_model "github.com/paper-indonesia/pivot-backoffice/internal/model/account"

	customerModel "github.com/paper-indonesia/pivot-backoffice/internal/model/customer"

	merchant "github.com/paper-indonesia/pivot-backoffice/internal/model/merchant"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IAccountRepository is an autogenerated mock type for the IAccountRepository type
type IAccountRepository struct {
	mock.Mock
}

// BulkInsert provides a mock function with given fields: ctx, accounts
func (_m *IAccountRepository) BulkInsert(ctx context.Context, accounts []*account_model.Account) error {
	ret := _m.Called(ctx, accounts)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*account_model.Account) error); ok {
		r0 = rf(ctx, accounts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, account
func (_m *IAccountRepository) Create(ctx context.Context, account *account_model.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account_model.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *IAccountRepository) FindAll(ctx context.Context) ([]*account_model.Account, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*account_model.Account, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*account_model.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMerchantAccountByName provides a mock function with given fields: ctx, merchantID, balanceType
func (_m *IAccountRepository) FindMerchantAccountByName(ctx context.Context, merchantID uuid.UUID, balanceType string) (*account_model.Account, error) {
	ret := _m.Called(ctx, merchantID, balanceType)

	if len(ret) == 0 {
		panic("no return value specified for FindMerchantAccountByName")
	}

	var r0 *account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*account_model.Account, error)); ok {
		return rf(ctx, merchantID, balanceType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *account_model.Account); ok {
		r0 = rf(ctx, merchantID, balanceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, merchantID, balanceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDs provides a mock function with given fields: ctx, accountId
func (_m *IAccountRepository) GetByIDs(ctx context.Context, accountId []string) ([]*account_model.Account, error) {
	ret := _m.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*account_model.Account, error)); ok {
		return rf(ctx, accountId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*account_model.Account); ok {
		r0 = rf(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByReferenceIDAndUsecase provides a mock function with given fields: ctx, referenceID, usecase, userType
func (_m *IAccountRepository) GetByReferenceIDAndUsecase(ctx context.Context, referenceID uuid.UUID, usecase string, userType string) (*account_model.Account, error) {
	ret := _m.Called(ctx, referenceID, usecase, userType)

	if len(ret) == 0 {
		panic("no return value specified for GetByReferenceIDAndUsecase")
	}

	var r0 *account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*account_model.Account, error)); ok {
		return rf(ctx, referenceID, usecase, userType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *account_model.Account); ok {
		r0 = rf(ctx, referenceID, usecase, userType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, referenceID, usecase, userType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUUID provides a mock function with given fields: ctx, accountId
func (_m *IAccountRepository) GetByUUID(ctx context.Context, accountId uuid.UUID) (*account_model.Account, error) {
	ret := _m.Called(ctx, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*account_model.Account, error)); ok {
		return rf(ctx, accountId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *account_model.Account); ok {
		r0 = rf(ctx, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomersWithoutAccount provides a mock function with given fields: ctx, request
func (_m *IAccountRepository) GetCustomersWithoutAccount(ctx context.Context, request account_model.GetEntityWithoutAccountRequest) ([]*customerModel.Customer, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomersWithoutAccount")
	}

	var r0 []*customerModel.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, account_model.GetEntityWithoutAccountRequest) ([]*customerModel.Customer, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, account_model.GetEntityWithoutAccountRequest) []*customerModel.Customer); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*customerModel.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, account_model.GetEntityWithoutAccountRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEntityAccounts provides a mock function with given fields: ctx, entityIDs, userType, name
func (_m *IAccountRepository) GetEntityAccounts(ctx context.Context, entityIDs []uuid.UUID, userType string, name string) (map[uuid.UUID]*account_model.Account, error) {
	ret := _m.Called(ctx, entityIDs, userType, name)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityAccounts")
	}

	var r0 map[uuid.UUID]*account_model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID, string, string) (map[uuid.UUID]*account_model.Account, error)); ok {
		return rf(ctx, entityIDs, userType, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID, string, string) map[uuid.UUID]*account_model.Account); ok {
		r0 = rf(ctx, entityIDs, userType, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]*account_model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, entityIDs, userType, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantsWithoutAccount provides a mock function with given fields: ctx, request
func (_m *IAccountRepository) GetMerchantsWithoutAccount(ctx context.Context, request account_model.GetEntityWithoutAccountRequest) ([]*merchant.Merchant, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantsWithoutAccount")
	}

	var r0 []*merchant.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, account_model.GetEntityWithoutAccountRequest) ([]*merchant.Merchant, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, account_model.GetEntityWithoutAccountRequest) []*merchant.Merchant); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*merchant.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, account_model.GetEntityWithoutAccountRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAccount provides a mock function with given fields: ctx, account
func (_m *IAccountRepository) UpdateAccount(ctx context.Context, account *account_model.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account_model.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateHoldedBalance provides a mock function with given fields: ctx, account
func (_m *IAccountRepository) UpdateHoldedBalance(ctx context.Context, account *account_model.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHoldedBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account_model.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAccountRepository creates a new instance of IAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAccountRepository {
	mock := &IAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
