// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	bankAccount "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/bankAccount"

	mock "github.com/stretchr/testify/mock"
)

// IBankAccountRepository is an autogenerated mock type for the IBankAccountRepository type
type IBankAccountRepository struct {
	mock.Mock
}

// BankAccountHasBeenPrepared provides a mock function with given fields: ctx, merchantId
func (_m *IBankAccountRepository) BankAccountHasBeenPrepared(ctx context.Context, merchantId string) (bool, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for BankAccountHasBeenPrepared")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, merchantId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, data
func (_m *IBankAccountRepository) Create(ctx context.Context, data *bankAccount.BankAccount) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bankAccount.BankAccount) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBankAccountValidation provides a mock function with given fields: ctx, merchantId, bankCode, accountNo
func (_m *IBankAccountRepository) GetBankAccountValidation(ctx context.Context, merchantId string, bankCode string, accountNo string) (*bankAccount.BankAccountResponse, error) {
	ret := _m.Called(ctx, merchantId, bankCode, accountNo)

	if len(ret) == 0 {
		panic("no return value specified for GetBankAccountValidation")
	}

	var r0 *bankAccount.BankAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*bankAccount.BankAccountResponse, error)); ok {
		return rf(ctx, merchantId, bankCode, accountNo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *bankAccount.BankAccountResponse); ok {
		r0 = rf(ctx, merchantId, bankCode, accountNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bankAccount.BankAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, merchantId, bankCode, accountNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByMerchantID provides a mock function with given fields: ctx, merchantID
func (_m *IBankAccountRepository) GetByMerchantID(ctx context.Context, merchantID string) (*bankAccount.BankAccount, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetByMerchantID")
	}

	var r0 *bankAccount.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*bankAccount.BankAccount, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *bankAccount.BankAccount); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bankAccount.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListBankAccount provides a mock function with given fields: ctx, merchantId
func (_m *IBankAccountRepository) GetListBankAccount(ctx context.Context, merchantId string) ([]bankAccount.BankAccountResponse, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetListBankAccount")
	}

	var r0 []bankAccount.BankAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]bankAccount.BankAccountResponse, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []bankAccount.BankAccountResponse); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bankAccount.BankAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, bk
func (_m *IBankAccountRepository) Update(ctx context.Context, bk *bankAccount.BankAccount) error {
	ret := _m.Called(ctx, bk)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bankAccount.BankAccount) error); ok {
		r0 = rf(ctx, bk)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIBankAccountRepository creates a new instance of IBankAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBankAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBankAccountRepository {
	mock := &IBankAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
