// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	cimbProcessorModel "github.com/paper-indonesia/pivot-backoffice/internal/model/cimbProcessor"

	mock "github.com/stretchr/testify/mock"

	vccSettlement "github.com/paper-indonesia/pivot-backoffice/internal/model/vccSettlement"
)

// ICimbProcessorRepository is an autogenerated mock type for the ICimbProcessorRepository type
type ICimbProcessorRepository struct {
	mock.Mock
}

// InquiryCorporateCreditCard provides a mock function with given fields: ctx, request
func (_m *ICimbProcessorRepository) InquiryCorporateCreditCard(ctx context.Context, request *cimbProcessorModel.InquiryCorporateCreditCardRequest) (*cimbProcessorModel.InquiryCorporateCreditCardResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for InquiryCorporateCreditCard")
	}

	var r0 *cimbProcessorModel.InquiryCorporateCreditCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *cimbProcessorModel.InquiryCorporateCreditCardRequest) (*cimbProcessorModel.InquiryCorporateCreditCardResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *cimbProcessorModel.InquiryCorporateCreditCardRequest) *cimbProcessorModel.InquiryCorporateCreditCardResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cimbProcessorModel.InquiryCorporateCreditCardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *cimbProcessorModel.InquiryCorporateCreditCardRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InquiryTransactionCorporateCreditCard provides a mock function with given fields: ctx, request
func (_m *ICimbProcessorRepository) InquiryTransactionCorporateCreditCard(ctx context.Context, request *cimbProcessorModel.InquiryTransactionCorporateCreditCardRequest) (*vccSettlement.ProcessorVccTransactionInquiryResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for InquiryTransactionCorporateCreditCard")
	}

	var r0 *vccSettlement.ProcessorVccTransactionInquiryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *cimbProcessorModel.InquiryTransactionCorporateCreditCardRequest) (*vccSettlement.ProcessorVccTransactionInquiryResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *cimbProcessorModel.InquiryTransactionCorporateCreditCardRequest) *vccSettlement.ProcessorVccTransactionInquiryResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vccSettlement.ProcessorVccTransactionInquiryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *cimbProcessorModel.InquiryTransactionCorporateCreditCardRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICimbProcessorRepository creates a new instance of ICimbProcessorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICimbProcessorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICimbProcessorRepository {
	mock := &ICimbProcessorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
