// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	cardFundedPayoutModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/cardFundedPayout"
	commonModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/common"

	context "context"

	disbursementModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/disbursement"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IDisbursementRepository is an autogenerated mock type for the IDisbursementRepository type
type IDisbursementRepository struct {
	mock.Mock
}

// ApproveInBulk provides a mock function with given fields: ctx, ids, approvedBy
func (_m *IDisbursementRepository) ApproveInBulk(ctx context.Context, ids []string, approvedBy string) error {
	ret := _m.Called(ctx, ids, approvedBy)

	if len(ret) == 0 {
		panic("no return value specified for ApproveInBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = rf(ctx, ids, approvedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BeginTransaction provides a mock function with given fields: ctx
func (_m *IDisbursementRepository) BeginTransaction(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitTransaction provides a mock function with given fields: ctx
func (_m *IDisbursementRepository) CommitTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountByBulkID provides a mock function with given fields: ctx, bulkID
func (_m *IDisbursementRepository) CountByBulkID(ctx context.Context, bulkID string) int {
	ret := _m.Called(ctx, bulkID)

	if len(ret) == 0 {
		panic("no return value specified for CountByBulkID")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, bulkID)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// CountByIDsAndMerchantID provides a mock function with given fields: ctx, ids, merchantID
func (_m *IDisbursementRepository) CountByIDsAndMerchantID(ctx context.Context, ids []string, merchantID string) int {
	ret := _m.Called(ctx, ids, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for CountByIDsAndMerchantID")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) int); ok {
		r0 = rf(ctx, ids, merchantID)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// CountByMerchantAndReference provides a mock function with given fields: ctx, merchantID, referenceID
func (_m *IDisbursementRepository) CountByMerchantAndReference(ctx context.Context, merchantID string, referenceID string) int {
	ret := _m.Called(ctx, merchantID, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for CountByMerchantAndReference")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, merchantID, referenceID)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// FindBulkDisbursementByID provides a mock function with given fields: ctx, id
func (_m *IDisbursementRepository) FindBulkDisbursementByID(ctx context.Context, id string) (*disbursementModel.BulkDisbursement, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindBulkDisbursementByID")
	}

	var r0 *disbursementModel.BulkDisbursement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*disbursementModel.BulkDisbursement, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *disbursementModel.BulkDisbursement); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.BulkDisbursement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *IDisbursementRepository) FindByID(ctx context.Context, id string) (*disbursementModel.DisbursementWithTransaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *disbursementModel.DisbursementWithTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*disbursementModel.DisbursementWithTransaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *disbursementModel.DisbursementWithTransaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.DisbursementWithTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMerchantAndReference provides a mock function with given fields: ctx, merchantID, referenceID
func (_m *IDisbursementRepository) FindByMerchantAndReference(ctx context.Context, merchantID string, referenceID string) (*disbursementModel.DisbursementWithTransaction, error) {
	ret := _m.Called(ctx, merchantID, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMerchantAndReference")
	}

	var r0 *disbursementModel.DisbursementWithTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*disbursementModel.DisbursementWithTransaction, error)); ok {
		return rf(ctx, merchantID, referenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *disbursementModel.DisbursementWithTransaction); ok {
		r0 = rf(ctx, merchantID, referenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.DisbursementWithTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantID, referenceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByProcessorReferenceID provides a mock function with given fields: ctx, processorReferenceID
func (_m *IDisbursementRepository) FindByProcessorReferenceID(ctx context.Context, processorReferenceID string) (*disbursementModel.DisbursementWithTransaction, error) {
	ret := _m.Called(ctx, processorReferenceID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProcessorReferenceID")
	}

	var r0 *disbursementModel.DisbursementWithTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*disbursementModel.DisbursementWithTransaction, error)); ok {
		return rf(ctx, processorReferenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *disbursementModel.DisbursementWithTransaction); ok {
		r0 = rf(ctx, processorReferenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.DisbursementWithTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, processorReferenceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByReference provides a mock function with given fields: ctx, referenceID
func (_m *IDisbursementRepository) FindByReference(ctx context.Context, referenceID string) (*disbursementModel.DisbursementWithTransaction, error) {
	ret := _m.Called(ctx, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for FindByReference")
	}

	var r0 *disbursementModel.DisbursementWithTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*disbursementModel.DisbursementWithTransaction, error)); ok {
		return rf(ctx, referenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *disbursementModel.DisbursementWithTransaction); ok {
		r0 = rf(ctx, referenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.DisbursementWithTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, referenceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindForReversalDisbursementById provides a mock function with given fields: ctx, merchantId, id
func (_m *IDisbursementRepository) FindForReversalDisbursementById(ctx context.Context, merchantId string, id string) (*disbursementModel.DisbursementForReversal, error) {
	ret := _m.Called(ctx, merchantId, id)

	if len(ret) == 0 {
		panic("no return value specified for FindForReversalDisbursementById")
	}

	var r0 *disbursementModel.DisbursementForReversal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*disbursementModel.DisbursementForReversal, error)); ok {
		return rf(ctx, merchantId, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *disbursementModel.DisbursementForReversal); ok {
		r0 = rf(ctx, merchantId, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.DisbursementForReversal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActionTransactionSummary provides a mock function with given fields: ctx, merchantId, disbursementIds
func (_m *IDisbursementRepository) GetActionTransactionSummary(ctx context.Context, merchantId string, disbursementIds []string) (*disbursementModel.ActionTransactionSummary, error) {
	ret := _m.Called(ctx, merchantId, disbursementIds)

	if len(ret) == 0 {
		panic("no return value specified for GetActionTransactionSummary")
	}

	var r0 *disbursementModel.ActionTransactionSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (*disbursementModel.ActionTransactionSummary, error)); ok {
		return rf(ctx, merchantId, disbursementIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) *disbursementModel.ActionTransactionSummary); ok {
		r0 = rf(ctx, merchantId, disbursementIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.ActionTransactionSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, merchantId, disbursementIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllDisbursementByBulkID provides a mock function with given fields: ctx, bulkID
func (_m *IDisbursementRepository) GetAllDisbursementByBulkID(ctx context.Context, bulkID string) ([]*disbursementModel.DisbursementWithTransaction, error) {
	ret := _m.Called(ctx, bulkID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDisbursementByBulkID")
	}

	var r0 []*disbursementModel.DisbursementWithTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*disbursementModel.DisbursementWithTransaction, error)); ok {
		return rf(ctx, bulkID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*disbursementModel.DisbursementWithTransaction); ok {
		r0 = rf(ctx, bulkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*disbursementModel.DisbursementWithTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bulkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvgDurationOfBankTransferProcessInMs provides a mock function with given fields: ctx, startTime, endTime
func (_m *IDisbursementRepository) GetAvgDurationOfBankTransferProcessInMs(ctx context.Context, startTime time.Time, endTime time.Time) (float64, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetAvgDurationOfBankTransferProcessInMs")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (float64, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBeneficiaryTransactionLimit provides a mock function with given fields: ctx, merchantId, bankCode, accountNo, startAt, endAt
func (_m *IDisbursementRepository) GetBeneficiaryTransactionLimit(ctx context.Context, merchantId string, bankCode string, accountNo string, startAt time.Time, endAt time.Time) (*disbursementModel.BeneficiaryPayoutLimitRuleLimit, error) {
	ret := _m.Called(ctx, merchantId, bankCode, accountNo, startAt, endAt)

	if len(ret) == 0 {
		panic("no return value specified for GetBeneficiaryTransactionLimit")
	}

	var r0 *disbursementModel.BeneficiaryPayoutLimitRuleLimit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) (*disbursementModel.BeneficiaryPayoutLimitRuleLimit, error)); ok {
		return rf(ctx, merchantId, bankCode, accountNo, startAt, endAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) *disbursementModel.BeneficiaryPayoutLimitRuleLimit); ok {
		r0 = rf(ctx, merchantId, bankCode, accountNo, startAt, endAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.BeneficiaryPayoutLimitRuleLimit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, merchantId, bankCode, accountNo, startAt, endAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBulkDisbursementDetailByID provides a mock function with given fields: ctx, id
func (_m *IDisbursementRepository) GetBulkDisbursementDetailByID(ctx context.Context, id string) (*disbursementModel.BulkDisbursementDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBulkDisbursementDetailByID")
	}

	var r0 *disbursementModel.BulkDisbursementDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*disbursementModel.BulkDisbursementDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *disbursementModel.BulkDisbursementDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.BulkDisbursementDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDs provides a mock function with given fields: ctx, ids
func (_m *IDisbursementRepository) GetByIDs(ctx context.Context, ids []string) ([]*disbursementModel.Disbursement, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*disbursementModel.Disbursement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*disbursementModel.Disbursement, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*disbursementModel.Disbursement); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*disbursementModel.Disbursement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardFundedPayoutDetail provides a mock function with given fields: ctx, request
func (_m *IDisbursementRepository) GetCardFundedPayoutDetail(ctx context.Context, request *cardFundedPayoutModel.GetPayoutDetailRequest) (*cardFundedPayoutModel.GetPayoutDetailResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetCardFundedPayoutDetail")
	}

	var r0 *cardFundedPayoutModel.GetPayoutDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *cardFundedPayoutModel.GetPayoutDetailRequest) (*cardFundedPayoutModel.GetPayoutDetailResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *cardFundedPayoutModel.GetPayoutDetailRequest) *cardFundedPayoutModel.GetPayoutDetailResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cardFundedPayoutModel.GetPayoutDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *cardFundedPayoutModel.GetPayoutDetailRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardFundedPayoutInsights provides a mock function with given fields: ctx, filter
func (_m *IDisbursementRepository) GetCardFundedPayoutInsights(ctx context.Context, filter *cardFundedPayoutModel.FilterGetPayoutInsights) (*cardFundedPayoutModel.GetPayoutInsightsDTO, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCardFundedPayoutInsights")
	}

	var r0 *cardFundedPayoutModel.GetPayoutInsightsDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *cardFundedPayoutModel.FilterGetPayoutInsights) (*cardFundedPayoutModel.GetPayoutInsightsDTO, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *cardFundedPayoutModel.FilterGetPayoutInsights) *cardFundedPayoutModel.GetPayoutInsightsDTO); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cardFundedPayoutModel.GetPayoutInsightsDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *cardFundedPayoutModel.FilterGetPayoutInsights) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardFundedPayoutList provides a mock function with given fields: ctx, filter
func (_m *IDisbursementRepository) GetCardFundedPayoutList(ctx context.Context, filter *cardFundedPayoutModel.FilterGetPayoutList) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCardFundedPayoutList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *cardFundedPayoutModel.FilterGetPayoutList) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *cardFundedPayoutModel.FilterGetPayoutList) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *cardFundedPayoutModel.FilterGetPayoutList) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardFundedPayoutTransactionList provides a mock function with given fields: ctx, request
func (_m *IDisbursementRepository) GetCardFundedPayoutTransactionList(ctx context.Context, request cardFundedPayoutModel.GetPayoutTransactionListRequest) ([]cardFundedPayoutModel.GetPayoutTransactionListResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetCardFundedPayoutTransactionList")
	}

	var r0 []cardFundedPayoutModel.GetPayoutTransactionListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, cardFundedPayoutModel.GetPayoutTransactionListRequest) ([]cardFundedPayoutModel.GetPayoutTransactionListResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, cardFundedPayoutModel.GetPayoutTransactionListRequest) []cardFundedPayoutModel.GetPayoutTransactionListResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cardFundedPayoutModel.GetPayoutTransactionListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, cardFundedPayoutModel.GetPayoutTransactionListRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDailyTransactionLimit provides a mock function with given fields: ctx, merchantId, merchantType
func (_m *IDisbursementRepository) GetDailyTransactionLimit(ctx context.Context, merchantId string, merchantType string) (*disbursementModel.DailyTransactionLimitResponse, error) {
	ret := _m.Called(ctx, merchantId, merchantType)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyTransactionLimit")
	}

	var r0 *disbursementModel.DailyTransactionLimitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*disbursementModel.DailyTransactionLimitResponse, error)); ok {
		return rf(ctx, merchantId, merchantType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *disbursementModel.DailyTransactionLimitResponse); ok {
		r0 = rf(ctx, merchantId, merchantType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.DailyTransactionLimitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, merchantType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailForCardFundedPayoutByID provides a mock function with given fields: ctx, id
func (_m *IDisbursementRepository) GetDetailForCardFundedPayoutByID(ctx context.Context, id string) (*disbursementModel.Disbursement, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailForCardFundedPayoutByID")
	}

	var r0 *disbursementModel.Disbursement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*disbursementModel.Disbursement, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *disbursementModel.Disbursement); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.Disbursement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, filter, page, perPage
func (_m *IDisbursementRepository) GetList(ctx context.Context, filter *disbursementModel.GetDisbursementFilterRequest, page int64, perPage int64) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.GetDisbursementFilterRequest, int64, int64) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.GetDisbursementFilterRequest, int64, int64) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *disbursementModel.GetDisbursementFilterRequest, int64, int64) error); ok {
		r1 = rf(ctx, filter, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListBulk provides a mock function with given fields: ctx, filter, page, perPage
func (_m *IDisbursementRepository) GetListBulk(ctx context.Context, filter *disbursementModel.GetBulkDisbursementFilterRequest, page int64, perPage int64) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetListBulk")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.GetBulkDisbursementFilterRequest, int64, int64) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.GetBulkDisbursementFilterRequest, int64, int64) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *disbursementModel.GetBulkDisbursementFilterRequest, int64, int64) error); ok {
		r1 = rf(ctx, filter, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantIDsForPayoutCallback provides a mock function with given fields: ctx, bulkId
func (_m *IDisbursementRepository) GetMerchantIDsForPayoutCallback(ctx context.Context, bulkId string) ([]string, error) {
	ret := _m.Called(ctx, bulkId)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantIDsForPayoutCallback")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, bulkId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, bulkId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bulkId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingTransactionsBetweenTimeForInquiryTransaction provides a mock function with given fields: ctx, from, to
func (_m *IDisbursementRepository) GetPendingTransactionsBetweenTimeForInquiryTransaction(ctx context.Context, from time.Time, to time.Time) ([]*disbursementModel.DisbursementWithTransaction, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingTransactionsBetweenTimeForInquiryTransaction")
	}

	var r0 []*disbursementModel.DisbursementWithTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]*disbursementModel.DisbursementWithTransaction, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []*disbursementModel.DisbursementWithTransaction); ok {
		r0 = rf(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*disbursementModel.DisbursementWithTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSummaryOfDelayedTransactionBeforeProcessed provides a mock function with given fields: ctx, startTime, endTime
func (_m *IDisbursementRepository) GetSummaryOfDelayedTransactionBeforeProcessed(ctx context.Context, startTime time.Time, endTime time.Time) (disbursementModel.AfterPayoutCutOffTimeSummary, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaryOfDelayedTransactionBeforeProcessed")
	}

	var r0 disbursementModel.AfterPayoutCutOffTimeSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (disbursementModel.AfterPayoutCutOffTimeSummary, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) disbursementModel.AfterPayoutCutOffTimeSummary); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		r0 = ret.Get(0).(disbursementModel.AfterPayoutCutOffTimeSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionConfig provides a mock function with given fields: ctx, merchantId
func (_m *IDisbursementRepository) GetTransactionConfig(ctx context.Context, merchantId string) (*disbursementModel.TransactionConfig, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionConfig")
	}

	var r0 *disbursementModel.TransactionConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*disbursementModel.TransactionConfig, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *disbursementModel.TransactionConfig); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.TransactionConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetXbPayoutDashboardInsights provides a mock function with given fields: ctx, request
func (_m *IDisbursementRepository) GetXbPayoutDashboardInsights(ctx context.Context, request disbursementModel.GetXbPayoutDashboardInsightRequest) (*disbursementModel.XbPayoutDashboardInsights, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetXbPayoutDashboardInsights")
	}

	var r0 *disbursementModel.XbPayoutDashboardInsights
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, disbursementModel.GetXbPayoutDashboardInsightRequest) (*disbursementModel.XbPayoutDashboardInsights, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, disbursementModel.GetXbPayoutDashboardInsightRequest) *disbursementModel.XbPayoutDashboardInsights); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.XbPayoutDashboardInsights)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, disbursementModel.GetXbPayoutDashboardInsightRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, request
func (_m *IDisbursementRepository) Insert(ctx context.Context, request *disbursementModel.Disbursement) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.Disbursement) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertBulkDisbursement provides a mock function with given fields: ctx, request
func (_m *IDisbursementRepository) InsertBulkDisbursement(ctx context.Context, request *disbursementModel.BulkDisbursement) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for InsertBulkDisbursement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.BulkDisbursement) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReconfirmXB provides a mock function with given fields: ctx, request
func (_m *IDisbursementRepository) ReconfirmXB(ctx context.Context, request *disbursementModel.ReconfirmXBRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ReconfirmXB")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.ReconfirmXBRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reject provides a mock function with given fields: ctx, id, reasonType, reasonDescription, rejectedBy
func (_m *IDisbursementRepository) Reject(ctx context.Context, id string, reasonType string, reasonDescription string, rejectedBy string) error {
	ret := _m.Called(ctx, id, reasonType, reasonDescription, rejectedBy)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, id, reasonType, reasonDescription, rejectedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollbackTransaction provides a mock function with given fields: ctx
func (_m *IDisbursementRepository) RollbackTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SumAmountByIDs provides a mock function with given fields: ctx, ids
func (_m *IDisbursementRepository) SumAmountByIDs(ctx context.Context, ids []string) (*disbursementModel.SumAmountResponse, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for SumAmountByIDs")
	}

	var r0 *disbursementModel.SumAmountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (*disbursementModel.SumAmountResponse, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) *disbursementModel.SumAmountResponse); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*disbursementModel.SumAmountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBankReferenceNo provides a mock function with given fields: ctx, id, bankReferenceNo
func (_m *IDisbursementRepository) UpdateBankReferenceNo(ctx context.Context, id string, bankReferenceNo string) error {
	ret := _m.Called(ctx, id, bankReferenceNo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBankReferenceNo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, bankReferenceNo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBulkDisbursementFailedFileByID provides a mock function with given fields: ctx, id, failedFilePath
func (_m *IDisbursementRepository) UpdateBulkDisbursementFailedFileByID(ctx context.Context, id string, failedFilePath string) error {
	ret := _m.Called(ctx, id, failedFilePath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulkDisbursementFailedFileByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, failedFilePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBulkDisbursementRejectedFileByID provides a mock function with given fields: ctx, id, rejectedFilePath
func (_m *IDisbursementRepository) UpdateBulkDisbursementRejectedFileByID(ctx context.Context, id string, rejectedFilePath string) error {
	ret := _m.Called(ctx, id, rejectedFilePath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulkDisbursementRejectedFileByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, rejectedFilePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBulkDisbursementStatusByID provides a mock function with given fields: ctx, id, status
func (_m *IDisbursementRepository) UpdateBulkDisbursementStatusByID(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulkDisbursementStatusByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProcessorReferenceByID provides a mock function with given fields: ctx, request
func (_m *IDisbursementRepository) UpdateProcessorReferenceByID(ctx context.Context, request *disbursementModel.Disbursement) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcessorReferenceByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *disbursementModel.Disbursement) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProcessorReferenceIdAndBankReferenceNo provides a mock function with given fields: ctx, id, processorReferenceId, bankReferenceNo
func (_m *IDisbursementRepository) UpdateProcessorReferenceIdAndBankReferenceNo(ctx context.Context, id string, processorReferenceId string, bankReferenceNo string) error {
	ret := _m.Called(ctx, id, processorReferenceId, bankReferenceNo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcessorReferenceIdAndBankReferenceNo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, id, processorReferenceId, bankReferenceNo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateReasonByIDs provides a mock function with given fields: ctx, ids, reasonType, reasonDescription
func (_m *IDisbursementRepository) UpdateReasonByIDs(ctx context.Context, ids []string, reasonType string, reasonDescription string) error {
	ret := _m.Called(ctx, ids, reasonType, reasonDescription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReasonByIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, string) error); ok {
		r0 = rf(ctx, ids, reasonType, reasonDescription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateReversalTransaction provides a mock function with given fields: ctx, id, reasonType, reasonDescription, createdBy
func (_m *IDisbursementRepository) UpdateReversalTransaction(ctx context.Context, id string, reasonType string, reasonDescription string, createdBy string) error {
	ret := _m.Called(ctx, id, reasonType, reasonDescription, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReversalTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, id, reasonType, reasonDescription, createdBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusAndReasonByID provides a mock function with given fields: ctx, id, status, reasonType, reasonDescription
func (_m *IDisbursementRepository) UpdateStatusAndReasonByID(ctx context.Context, id string, status string, reasonType *string, reasonDescription *string) error {
	ret := _m.Called(ctx, id, status, reasonType, reasonDescription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusAndReasonByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, *string) error); ok {
		r0 = rf(ctx, id, status, reasonType, reasonDescription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIDisbursementRepository creates a new instance of IDisbursementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDisbursementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDisbursementRepository {
	mock := &IDisbursementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
