// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	fraudrulesmodel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/fraudRules"
	mock "github.com/stretchr/testify/mock"
)

// IFraudRulesRepository is an autogenerated mock type for the IFraudRulesRepository type
type IFraudRulesRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, rule
func (_m *IFraudRulesRepository) Create(ctx context.Context, rule *fraudrulesmodel.FraudRules) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fraudrulesmodel.FraudRules) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, uuid
func (_m *IFraudRulesRepository) Delete(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *IFraudRulesRepository) GetByID(ctx context.Context, id string) (*fraudrulesmodel.FraudRules, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *fraudrulesmodel.FraudRules
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*fraudrulesmodel.FraudRules, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *fraudrulesmodel.FraudRules); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fraudrulesmodel.FraudRules)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, q
func (_m *IFraudRulesRepository) List(ctx context.Context, q *fraudrulesmodel.FraudRulesQuery) ([]*fraudrulesmodel.FraudRules, int, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*fraudrulesmodel.FraudRules
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *fraudrulesmodel.FraudRulesQuery) ([]*fraudrulesmodel.FraudRules, int, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *fraudrulesmodel.FraudRulesQuery) []*fraudrulesmodel.FraudRules); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*fraudrulesmodel.FraudRules)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *fraudrulesmodel.FraudRulesQuery) int); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *fraudrulesmodel.FraudRulesQuery) error); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, rule
func (_m *IFraudRulesRepository) Update(ctx context.Context, rule *fraudrulesmodel.FraudRules) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fraudrulesmodel.FraudRules) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIFraudRulesRepository creates a new instance of IFraudRulesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFraudRulesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFraudRulesRepository {
	mock := &IFraudRulesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
