// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	commonModel "github.com/paper-indonesia/pivot-backoffice/internal/model/common"

	inboundModel "github.com/paper-indonesia/pivot-backoffice/internal/model/inbound"

	mock "github.com/stretchr/testify/mock"
)

// IInboundRepository is an autogenerated mock type for the IInboundRepository type
type IInboundRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *IInboundRepository) GetByID(ctx context.Context, id string) (*inboundModel.InboundResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *inboundModel.InboundResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*inboundModel.InboundResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *inboundModel.InboundResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inboundModel.InboundResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, filter
func (_m *IInboundRepository) GetList(ctx context.Context, filter *inboundModel.GetInboundFilterRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inboundModel.GetInboundFilterRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inboundModel.GetInboundFilterRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inboundModel.GetInboundFilterRequest) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, data
func (_m *IInboundRepository) Insert(ctx context.Context, data *inboundModel.InboundRequest) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *inboundModel.InboundRequest) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIInboundRepository creates a new instance of IInboundRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInboundRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInboundRepository {
	mock := &IInboundRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
