// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	industry "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/industry"
	mock "github.com/stretchr/testify/mock"
)

// IIndustryRepository is an autogenerated mock type for the IIndustryRepository type
type IIndustryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *IIndustryRepository) Create(ctx context.Context, _a1 *industry.Industry) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *industry.Industry) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, uuid
func (_m *IIndustryRepository) Delete(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllIndustries provides a mock function with given fields: ctx, request
func (_m *IIndustryRepository) GetAllIndustries(ctx context.Context, request *industry.SearchIndustryRequest) ([]*industry.Industry, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetAllIndustries")
	}

	var r0 []*industry.Industry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *industry.SearchIndustryRequest) ([]*industry.Industry, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *industry.SearchIndustryRequest) []*industry.Industry); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*industry.Industry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *industry.SearchIndustryRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByParentChildIndustry provides a mock function with given fields: ctx, parent, child
func (_m *IIndustryRepository) GetByParentChildIndustry(ctx context.Context, parent string, child string) (*industry.Industry, error) {
	ret := _m.Called(ctx, parent, child)

	if len(ret) == 0 {
		panic("no return value specified for GetByParentChildIndustry")
	}

	var r0 *industry.Industry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*industry.Industry, error)); ok {
		return rf(ctx, parent, child)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *industry.Industry); ok {
		r0 = rf(ctx, parent, child)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*industry.Industry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, parent, child)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChildIndustries provides a mock function with given fields: ctx, parentIndustry
func (_m *IIndustryRepository) GetChildIndustries(ctx context.Context, parentIndustry string) ([]string, error) {
	ret := _m.Called(ctx, parentIndustry)

	if len(ret) == 0 {
		panic("no return value specified for GetChildIndustries")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, parentIndustry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, parentIndustry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, parentIndustry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIndustryByID provides a mock function with given fields: ctx, id
func (_m *IIndustryRepository) GetIndustryByID(ctx context.Context, id string) (*industry.Industry, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetIndustryByID")
	}

	var r0 *industry.Industry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*industry.Industry, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *industry.Industry); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*industry.Industry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMCCForIndustry provides a mock function with given fields: ctx, parentIndustry, childIndustry
func (_m *IIndustryRepository) GetMCCForIndustry(ctx context.Context, parentIndustry string, childIndustry string) (string, error) {
	ret := _m.Called(ctx, parentIndustry, childIndustry)

	if len(ret) == 0 {
		panic("no return value specified for GetMCCForIndustry")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, parentIndustry, childIndustry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, parentIndustry, childIndustry)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, parentIndustry, childIndustry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUniqueParentIndustries provides a mock function with given fields: ctx
func (_m *IIndustryRepository) GetUniqueParentIndustries(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUniqueParentIndustries")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsIndustryUsedByMerchants provides a mock function with given fields: ctx, parent, child
func (_m *IIndustryRepository) IsIndustryUsedByMerchants(ctx context.Context, parent string, child string) (bool, error) {
	ret := _m.Called(ctx, parent, child)

	if len(ret) == 0 {
		panic("no return value specified for IsIndustryUsedByMerchants")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, parent, child)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, parent, child)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, parent, child)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsValidMCC provides a mock function with given fields: ctx, mcc
func (_m *IIndustryRepository) IsValidMCC(ctx context.Context, mcc string) (bool, error) {
	ret := _m.Called(ctx, mcc)

	if len(ret) == 0 {
		panic("no return value specified for IsValidMCC")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, mcc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, mcc)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mcc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *IIndustryRepository) Update(ctx context.Context, _a1 *industry.Industry) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *industry.Industry) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIIndustryRepository creates a new instance of IIndustryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIIndustryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IIndustryRepository {
	mock := &IIndustryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
