// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/paper-indonesia/pivot-backoffice/config"

	liveFeature "github.com/paper-indonesia/pivot-backoffice/internal/model/liveFeature"

	mock "github.com/stretchr/testify/mock"
)

// ILiveFeatureRepository is an autogenerated mock type for the ILiveFeatureRepository type
type ILiveFeatureRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *ILiveFeatureRepository) GetAll(ctx context.Context) ([]liveFeature.LiveFeature, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []liveFeature.LiveFeature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]liveFeature.LiveFeature, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []liveFeature.LiveFeature); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]liveFeature.LiveFeature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveAppVersion provides a mock function with given fields: ctx
func (_m *ILiveFeatureRepository) RetrieveAppVersion(ctx context.Context) (liveFeature.AppVersion, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAppVersion")
	}

	var r0 liveFeature.AppVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (liveFeature.AppVersion, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) liveFeature.AppVersion); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(liveFeature.AppVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithConfig provides a mock function with given fields: _a0
func (_m *ILiveFeatureRepository) WithConfig(_a0 *config.Config) {
	_m.Called(_a0)
}

// WithSecret provides a mock function with given fields: secret
func (_m *ILiveFeatureRepository) WithSecret(secret *config.Secret) {
	_m.Called(secret)
}

// NewILiveFeatureRepository creates a new instance of ILiveFeatureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILiveFeatureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILiveFeatureRepository {
	mock := &ILiveFeatureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
