// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	commonModel "github.com/paper-indonesia/pivot-backoffice/internal/model/common"

	feeModel "github.com/paper-indonesia/pivot-backoffice/internal/model/fee"

	merchant "github.com/paper-indonesia/pivot-backoffice/internal/model/merchant"

	mock "github.com/stretchr/testify/mock"

	time "time"

	types "github.com/jmoiron/sqlx/types"
)

// IMerchantRepository is an autogenerated mock type for the IMerchantRepository type
type IMerchantRepository struct {
	mock.Mock
}

// AppliedFeeFromTiers provides a mock function with given fields: ctx, feeId, appliedFee
func (_m *IMerchantRepository) AppliedFeeFromTiers(ctx context.Context, feeId string, appliedFee *merchant.FeeTieringConfig) error {
	ret := _m.Called(ctx, feeId, appliedFee)

	if len(ret) == 0 {
		panic("no return value specified for AppliedFeeFromTiers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *merchant.FeeTieringConfig) error); ok {
		r0 = rf(ctx, feeId, appliedFee)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BeginTransaction provides a mock function with given fields: ctx
func (_m *IMerchantRepository) BeginTransaction(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitTransaction provides a mock function with given fields: ctx
func (_m *IMerchantRepository) CommitTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *IMerchantRepository) Create(ctx context.Context, _a1 *merchant.Merchant) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.Merchant) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateDocument provides a mock function with given fields: ctx, document
func (_m *IMerchantRepository) CreateDocument(ctx context.Context, document *merchant.Document) error {
	ret := _m.Called(ctx, document)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.Document) error); ok {
		r0 = rf(ctx, document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateFeeConfigOnBehalf provides a mock function with given fields: ctx, data
func (_m *IMerchantRepository) CreateFeeConfigOnBehalf(ctx context.Context, data *merchant.OnBehalfFeeConfig) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateFeeConfigOnBehalf")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.OnBehalfFeeConfig) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMerchantAuth provides a mock function with given fields: ctx, merchantAuth
func (_m *IMerchantRepository) CreateMerchantAuth(ctx context.Context, merchantAuth *merchant.MerchantAuth) error {
	ret := _m.Called(ctx, merchantAuth)

	if len(ret) == 0 {
		panic("no return value specified for CreateMerchantAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.MerchantAuth) error); ok {
		r0 = rf(ctx, merchantAuth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMerchantFee provides a mock function with given fields: ctx, merchantFee
func (_m *IMerchantRepository) CreateMerchantFee(ctx context.Context, merchantFee *merchant.MerchantFee) error {
	ret := _m.Called(ctx, merchantFee)

	if len(ret) == 0 {
		panic("no return value specified for CreateMerchantFee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.MerchantFee) error); ok {
		r0 = rf(ctx, merchantFee)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeterminePaymentFeeByMerchantIdMethodAndChannel provides a mock function with given fields: ctx, request
func (_m *IMerchantRepository) DeterminePaymentFeeByMerchantIdMethodAndChannel(ctx context.Context, request *feeModel.GetFeeRequest) (*merchant.MerchantFee, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeterminePaymentFeeByMerchantIdMethodAndChannel")
	}

	var r0 *merchant.MerchantFee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *feeModel.GetFeeRequest) (*merchant.MerchantFee, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *feeModel.GetFeeRequest) *merchant.MerchantFee); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantFee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *feeModel.GetFeeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeterminePaymentFundedPayoutFeeByMerchantIdMethodAndChannel provides a mock function with given fields: ctx, merchantId, method, channel, settlementType
func (_m *IMerchantRepository) DeterminePaymentFundedPayoutFeeByMerchantIdMethodAndChannel(ctx context.Context, merchantId string, method string, channel string, settlementType string) (*merchant.MerchantFee, error) {
	ret := _m.Called(ctx, merchantId, method, channel, settlementType)

	if len(ret) == 0 {
		panic("no return value specified for DeterminePaymentFundedPayoutFeeByMerchantIdMethodAndChannel")
	}

	var r0 *merchant.MerchantFee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*merchant.MerchantFee, error)); ok {
		return rf(ctx, merchantId, method, channel, settlementType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *merchant.MerchantFee); ok {
		r0 = rf(ctx, merchantId, method, channel, settlementType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantFee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, merchantId, method, channel, settlementType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeterminePayoutFeeByMerchantIdAndChannel provides a mock function with given fields: ctx, merchantId, channel, reference
func (_m *IMerchantRepository) DeterminePayoutFeeByMerchantIdAndChannel(ctx context.Context, merchantId string, channel string, reference string) (*merchant.MerchantFee, error) {
	ret := _m.Called(ctx, merchantId, channel, reference)

	if len(ret) == 0 {
		panic("no return value specified for DeterminePayoutFeeByMerchantIdAndChannel")
	}

	var r0 *merchant.MerchantFee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*merchant.MerchantFee, error)); ok {
		return rf(ctx, merchantId, channel, reference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *merchant.MerchantFee); ok {
		r0 = rf(ctx, merchantId, channel, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantFee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, merchantId, channel, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetermineRefundFeeByMerchantIdAndReferenceType provides a mock function with given fields: ctx, merchantId, referenceType
func (_m *IMerchantRepository) DetermineRefundFeeByMerchantIdAndReferenceType(ctx context.Context, merchantId string, referenceType string) (*merchant.MerchantFee, error) {
	ret := _m.Called(ctx, merchantId, referenceType)

	if len(ret) == 0 {
		panic("no return value specified for DetermineRefundFeeByMerchantIdAndReferenceType")
	}

	var r0 *merchant.MerchantFee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*merchant.MerchantFee, error)); ok {
		return rf(ctx, merchantId, referenceType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *merchant.MerchantFee); ok {
		r0 = rf(ctx, merchantId, referenceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantFee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, referenceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetermineTopupFeeByMerchantIdMethodAndChannel provides a mock function with given fields: ctx, merchantId, method, channel
func (_m *IMerchantRepository) DetermineTopupFeeByMerchantIdMethodAndChannel(ctx context.Context, merchantId string, method string, channel string) (*merchant.MerchantFee, error) {
	ret := _m.Called(ctx, merchantId, method, channel)

	if len(ret) == 0 {
		panic("no return value specified for DetermineTopupFeeByMerchantIdMethodAndChannel")
	}

	var r0 *merchant.MerchantFee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*merchant.MerchantFee, error)); ok {
		return rf(ctx, merchantId, method, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *merchant.MerchantFee); ok {
		r0 = rf(ctx, merchantId, method, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantFee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, merchantId, method, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDocumentByType provides a mock function with given fields: ctx, merchantId, docType
func (_m *IMerchantRepository) FindDocumentByType(ctx context.Context, merchantId string, docType string) (*merchant.Document, error) {
	ret := _m.Called(ctx, merchantId, docType)

	if len(ret) == 0 {
		panic("no return value specified for FindDocumentByType")
	}

	var r0 *merchant.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*merchant.Document, error)); ok {
		return rf(ctx, merchantId, docType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *merchant.Document); ok {
		r0 = rf(ctx, merchantId, docType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, docType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDocumentIdByType provides a mock function with given fields: ctx, merchantId, docType
func (_m *IMerchantRepository) FindDocumentIdByType(ctx context.Context, merchantId string, docType string) (string, error) {
	ret := _m.Called(ctx, merchantId, docType)

	if len(ret) == 0 {
		panic("no return value specified for FindDocumentIdByType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, merchantId, docType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, merchantId, docType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, docType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMerchantByID provides a mock function with given fields: ctx, id
func (_m *IMerchantRepository) FindMerchantByID(ctx context.Context, id string) (*merchant.Merchant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindMerchantByID")
	}

	var r0 *merchant.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*merchant.Merchant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *merchant.Merchant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMerchantForQrRegistration provides a mock function with given fields: ctx, merchantId, acquirer
func (_m *IMerchantRepository) FindMerchantForQrRegistration(ctx context.Context, merchantId string, acquirer string) (*merchant.QrisMerchant, error) {
	ret := _m.Called(ctx, merchantId, acquirer)

	if len(ret) == 0 {
		panic("no return value specified for FindMerchantForQrRegistration")
	}

	var r0 *merchant.QrisMerchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*merchant.QrisMerchant, error)); ok {
		return rf(ctx, merchantId, acquirer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *merchant.QrisMerchant); ok {
		r0 = rf(ctx, merchantId, acquirer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.QrisMerchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, acquirer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStatusByID provides a mock function with given fields: ctx, id
func (_m *IMerchantRepository) FindStatusByID(ctx context.Context, id string) (*merchant.MerchantStatusResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindStatusByID")
	}

	var r0 *merchant.MerchantStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*merchant.MerchantStatusResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *merchant.MerchantStatusResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateNewMID provides a mock function with given fields: ctx
func (_m *IMerchantRepository) GenerateNewMID(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateNewMID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllActiveMerchantIDs provides a mock function with given fields: ctx
func (_m *IMerchantRepository) GetAllActiveMerchantIDs(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllActiveMerchantIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBillingFees provides a mock function with given fields: ctx, request
func (_m *IMerchantRepository) GetBillingFees(ctx context.Context, request merchant.BillingFeeRequest) (*merchant.BillingFeeResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBillingFees")
	}

	var r0 *merchant.BillingFeeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, merchant.BillingFeeRequest) (*merchant.BillingFeeResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, merchant.BillingFeeRequest) *merchant.BillingFeeResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.BillingFeeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, merchant.BillingFeeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDepositSetting provides a mock function with given fields: ctx, merchantId
func (_m *IMerchantRepository) GetDepositSetting(ctx context.Context, merchantId string) (*merchant.DepositSettingResponse, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetDepositSetting")
	}

	var r0 *merchant.DepositSettingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*merchant.DepositSettingResponse, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *merchant.DepositSettingResponse); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.DepositSettingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDisbursementMerchantConfig provides a mock function with given fields: ctx, merchantId
func (_m *IMerchantRepository) GetDisbursementMerchantConfig(ctx context.Context, merchantId string) (*merchant.DisbursementMerchantConfig, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetDisbursementMerchantConfig")
	}

	var r0 *merchant.DisbursementMerchantConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*merchant.DisbursementMerchantConfig, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *merchant.DisbursementMerchantConfig); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.DisbursementMerchantConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDocuments provides a mock function with given fields: ctx, req
func (_m *IMerchantRepository) GetDocuments(ctx context.Context, req *merchant.MerchantDocumentFilterRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetDocuments")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.MerchantDocumentFilterRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.MerchantDocumentFilterRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *merchant.MerchantDocumentFilterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFDSConfig provides a mock function with given fields: ctx, merchantID
func (_m *IMerchantRepository) GetFDSConfig(ctx context.Context, merchantID string) (*merchant.GetFDSConfigResponse, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetFDSConfig")
	}

	var r0 *merchant.GetFDSConfigResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*merchant.GetFDSConfigResponse, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *merchant.GetFDSConfigResponse); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.GetFDSConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFeeConfigOnBehalf provides a mock function with given fields: ctx, request
func (_m *IMerchantRepository) GetFeeConfigOnBehalf(ctx context.Context, request *merchant.GetFeeConfigOnBehalfRequest) ([]merchant.FeeConfigOnBehalfResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetFeeConfigOnBehalf")
	}

	var r0 []merchant.FeeConfigOnBehalfResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.GetFeeConfigOnBehalfRequest) ([]merchant.FeeConfigOnBehalfResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.GetFeeConfigOnBehalfRequest) []merchant.FeeConfigOnBehalfResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]merchant.FeeConfigOnBehalfResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *merchant.GetFeeConfigOnBehalfRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListMerchantBODs provides a mock function with given fields: ctx, merchantId
func (_m *IMerchantRepository) GetListMerchantBODs(ctx context.Context, merchantId string) ([]merchant.BoardOfDirectorResp, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetListMerchantBODs")
	}

	var r0 []merchant.BoardOfDirectorResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]merchant.BoardOfDirectorResp, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []merchant.BoardOfDirectorResp); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]merchant.BoardOfDirectorResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListMerchantFeeThatUseTiers provides a mock function with given fields: ctx
func (_m *IMerchantRepository) GetListMerchantFeeThatUseTiers(ctx context.Context) (map[string][]merchant.MerchantFeeThatUseTier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetListMerchantFeeThatUseTiers")
	}

	var r0 map[string][]merchant.MerchantFeeThatUseTier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string][]merchant.MerchantFeeThatUseTier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string][]merchant.MerchantFeeThatUseTier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]merchant.MerchantFeeThatUseTier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListOfMerchantsToForceTheAutoWithdrawalProcess provides a mock function with given fields: ctx
func (_m *IMerchantRepository) GetListOfMerchantsToForceTheAutoWithdrawalProcess(ctx context.Context) ([]merchant.MerchantWithdrawalDetails, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetListOfMerchantsToForceTheAutoWithdrawalProcess")
	}

	var r0 []merchant.MerchantWithdrawalDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]merchant.MerchantWithdrawalDetails, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []merchant.MerchantWithdrawalDetails); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]merchant.MerchantWithdrawalDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListOfMerchantsWhoHaveSubMerchant provides a mock function with given fields: ctx
func (_m *IMerchantRepository) GetListOfMerchantsWhoHaveSubMerchant(ctx context.Context) ([]merchant.MerchantWithSubMerchantList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetListOfMerchantsWhoHaveSubMerchant")
	}

	var r0 []merchant.MerchantWithSubMerchantList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]merchant.MerchantWithSubMerchantList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []merchant.MerchantWithSubMerchantList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]merchant.MerchantWithSubMerchantList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListOfMerchantsWithActiveAutoWithdrawalStatus provides a mock function with given fields: ctx
func (_m *IMerchantRepository) GetListOfMerchantsWithActiveAutoWithdrawalStatus(ctx context.Context) ([]merchant.MerchantWithActiveAutoWithdrawalStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetListOfMerchantsWithActiveAutoWithdrawalStatus")
	}

	var r0 []merchant.MerchantWithActiveAutoWithdrawalStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]merchant.MerchantWithActiveAutoWithdrawalStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []merchant.MerchantWithActiveAutoWithdrawalStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]merchant.MerchantWithActiveAutoWithdrawalStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantAuthByMerchantId provides a mock function with given fields: ctx, merchantID
func (_m *IMerchantRepository) GetMerchantAuthByMerchantId(ctx context.Context, merchantID string) (*merchant.MerchantAuth, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantAuthByMerchantId")
	}

	var r0 *merchant.MerchantAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*merchant.MerchantAuth, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *merchant.MerchantAuth); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantAuth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantFeeByID provides a mock function with given fields: ctx, id
func (_m *IMerchantRepository) GetMerchantFeeByID(ctx context.Context, id string) (*merchant.MerchantFee, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantFeeByID")
	}

	var r0 *merchant.MerchantFee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*merchant.MerchantFee, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *merchant.MerchantFee); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantFee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantFeeByMerchantIDAndType provides a mock function with given fields: ctx, merchantID, feeType
func (_m *IMerchantRepository) GetMerchantFeeByMerchantIDAndType(ctx context.Context, merchantID string, feeType string) (*merchant.MerchantFee, error) {
	ret := _m.Called(ctx, merchantID, feeType)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantFeeByMerchantIDAndType")
	}

	var r0 *merchant.MerchantFee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*merchant.MerchantFee, error)); ok {
		return rf(ctx, merchantID, feeType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *merchant.MerchantFee); ok {
		r0 = rf(ctx, merchantID, feeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantFee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantID, feeType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantFeeByRequest provides a mock function with given fields: ctx, request
func (_m *IMerchantRepository) GetMerchantFeeByRequest(ctx context.Context, request *merchant.GetMerchantFeeRequest) (*merchant.MerchantFee, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantFeeByRequest")
	}

	var r0 *merchant.MerchantFee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.GetMerchantFeeRequest) (*merchant.MerchantFee, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.GetMerchantFeeRequest) *merchant.MerchantFee); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantFee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *merchant.GetMerchantFeeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantFeeListForBalanceDeduction provides a mock function with given fields: ctx
func (_m *IMerchantRepository) GetMerchantFeeListForBalanceDeduction(ctx context.Context) ([]merchant.MerchantFeeForBalanceDeduction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantFeeListForBalanceDeduction")
	}

	var r0 []merchant.MerchantFeeForBalanceDeduction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]merchant.MerchantFeeForBalanceDeduction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []merchant.MerchantFeeForBalanceDeduction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]merchant.MerchantFeeForBalanceDeduction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantFeeXB provides a mock function with given fields: ctx, q
func (_m *IMerchantRepository) GetMerchantFeeXB(ctx context.Context, q *merchant.MerchantFeeXBQuery) (*merchant.MerchantFee, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantFeeXB")
	}

	var r0 *merchant.MerchantFee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.MerchantFeeXBQuery) (*merchant.MerchantFee, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.MerchantFeeXBQuery) *merchant.MerchantFee); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantFee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *merchant.MerchantFeeXBQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantSnapPKCS8KeyByMerchantID provides a mock function with given fields: ctx, merchantID
func (_m *IMerchantRepository) GetMerchantSnapPKCS8KeyByMerchantID(ctx context.Context, merchantID string) (*merchant.MerchantAuth, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantSnapPKCS8KeyByMerchantID")
	}

	var r0 *merchant.MerchantAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*merchant.MerchantAuth, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *merchant.MerchantAuth); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.MerchantAuth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantsByIDs provides a mock function with given fields: ctx, merchantIDs
func (_m *IMerchantRepository) GetMerchantsByIDs(ctx context.Context, merchantIDs []string) ([]*merchant.Merchant, error) {
	ret := _m.Called(ctx, merchantIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantsByIDs")
	}

	var r0 []*merchant.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*merchant.Merchant, error)); ok {
		return rf(ctx, merchantIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*merchant.Merchant); ok {
		r0 = rf(ctx, merchantIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*merchant.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, merchantIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSettlementConfig provides a mock function with given fields: ctx, request
func (_m *IMerchantRepository) GetSettlementConfig(ctx context.Context, request merchant.GetSettlementConfigRequest) (*merchant.SettlementConfig, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetSettlementConfig")
	}

	var r0 *merchant.SettlementConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, merchant.GetSettlementConfigRequest) (*merchant.SettlementConfig, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, merchant.GetSettlementConfigRequest) *merchant.SettlementConfig); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.SettlementConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, merchant.GetSettlementConfigRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubMerchantIdListByParentId provides a mock function with given fields: ctx, parentId
func (_m *IMerchantRepository) GetSubMerchantIdListByParentId(ctx context.Context, parentId string) ([]string, error) {
	ret := _m.Called(ctx, parentId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubMerchantIdListByParentId")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, parentId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, parentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, parentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubMerchantsByParentID provides a mock function with given fields: ctx, parentMerchantID
func (_m *IMerchantRepository) GetSubMerchantsByParentID(ctx context.Context, parentMerchantID string) ([]*merchant.Merchant, error) {
	ret := _m.Called(ctx, parentMerchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubMerchantsByParentID")
	}

	var r0 []*merchant.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*merchant.Merchant, error)); ok {
		return rf(ctx, parentMerchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*merchant.Merchant); ok {
		r0 = rf(ctx, parentMerchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*merchant.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, parentMerchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubmerchantsByIDs provides a mock function with given fields: ctx, parentMerchantID, submerchantIDs
func (_m *IMerchantRepository) GetSubmerchantsByIDs(ctx context.Context, parentMerchantID string, submerchantIDs []string) ([]*merchant.Merchant, error) {
	ret := _m.Called(ctx, parentMerchantID, submerchantIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetSubmerchantsByIDs")
	}

	var r0 []*merchant.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) ([]*merchant.Merchant, error)); ok {
		return rf(ctx, parentMerchantID, submerchantIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) []*merchant.Merchant); ok {
		r0 = rf(ctx, parentMerchantID, submerchantIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*merchant.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, parentMerchantID, submerchantIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionConfig provides a mock function with given fields: ctx, merchantId
func (_m *IMerchantRepository) GetTransactionConfig(ctx context.Context, merchantId string) (*merchant.TransactionConfigResp, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionConfig")
	}

	var r0 *merchant.TransactionConfigResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*merchant.TransactionConfigResp, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *merchant.TransactionConfigResp); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.TransactionConfigResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionFeeOnBehalf provides a mock function with given fields: ctx, merchantId, subMerchantId, reference, paymentMethod, referenceType
func (_m *IMerchantRepository) GetTransactionFeeOnBehalf(ctx context.Context, merchantId string, subMerchantId string, reference string, paymentMethod string, referenceType string) (*merchant.TransactionFeeOnBehalf, error) {
	ret := _m.Called(ctx, merchantId, subMerchantId, reference, paymentMethod, referenceType)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionFeeOnBehalf")
	}

	var r0 *merchant.TransactionFeeOnBehalf
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*merchant.TransactionFeeOnBehalf, error)); ok {
		return rf(ctx, merchantId, subMerchantId, reference, paymentMethod, referenceType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *merchant.TransactionFeeOnBehalf); ok {
		r0 = rf(ctx, merchantId, subMerchantId, reference, paymentMethod, referenceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.TransactionFeeOnBehalf)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, merchantId, subMerchantId, reference, paymentMethod, referenceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsInvestigationFlowEnabled provides a mock function with given fields: ctx, merchantID
func (_m *IMerchantRepository) IsInvestigationFlowEnabled(ctx context.Context, merchantID string) (bool, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for IsInvestigationFlowEnabled")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, merchantID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSubMerchantByParentID provides a mock function with given fields: ctx, filter, page, perPage
func (_m *IMerchantRepository) ListSubMerchantByParentID(ctx context.Context, filter *merchant.SubMerchantListFilter, page int64, perPage int64) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListSubMerchantByParentID")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.SubMerchantListFilter, int64, int64) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.SubMerchantListFilter, int64, int64) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *merchant.SubMerchantListFilter, int64, int64) error); ok {
		r1 = rf(ctx, filter, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUnencryptedMerchantSecretsForMigration provides a mock function with given fields: ctx
func (_m *IMerchantRepository) ListUnencryptedMerchantSecretsForMigration(ctx context.Context) ([]merchant.UnencryptedMerchantSecretsForMigration, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUnencryptedMerchantSecretsForMigration")
	}

	var r0 []merchant.UnencryptedMerchantSecretsForMigration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]merchant.UnencryptedMerchantSecretsForMigration, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []merchant.UnencryptedMerchantSecretsForMigration); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]merchant.UnencryptedMerchantSecretsForMigration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MigrateMerchantSecretsToEncryption provides a mock function with given fields: ctx, _a1
func (_m *IMerchantRepository) MigrateMerchantSecretsToEncryption(ctx context.Context, _a1 merchant.MigrateMerchantSecretsToEncryption) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MigrateMerchantSecretsToEncryption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, merchant.MigrateMerchantSecretsToEncryption) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PayBillingFees provides a mock function with given fields: ctx, request
func (_m *IMerchantRepository) PayBillingFees(ctx context.Context, request merchant.PayBillingFeeRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for PayBillingFees")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, merchant.PayBillingFeeRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollbackTransaction provides a mock function with given fields: ctx
func (_m *IMerchantRepository) RollbackTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAutoWithdrawal provides a mock function with given fields: ctx, request
func (_m *IMerchantRepository) SetAutoWithdrawal(ctx context.Context, request *merchant.AutoWithdrawalSettingRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SetAutoWithdrawal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.AutoWithdrawalSettingRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *IMerchantRepository) Update(ctx context.Context, _a1 *merchant.Merchant) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.Merchant) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCallbackApiKey provides a mock function with given fields: ctx, merchantId, apiKey, version
func (_m *IMerchantRepository) UpdateCallbackApiKey(ctx context.Context, merchantId string, apiKey string, version uint) error {
	ret := _m.Called(ctx, merchantId, apiKey, version)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCallbackApiKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uint) error); ok {
		r0 = rf(ctx, merchantId, apiKey, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDocument provides a mock function with given fields: ctx, document
func (_m *IMerchantRepository) UpdateDocument(ctx context.Context, document *merchant.Document) error {
	ret := _m.Called(ctx, document)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.Document) error); ok {
		r0 = rf(ctx, document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateFDSConfig provides a mock function with given fields: ctx, merchantID, config
func (_m *IMerchantRepository) UpdateFDSConfig(ctx context.Context, merchantID string, config merchant.FDSConfigRequest) error {
	ret := _m.Called(ctx, merchantID, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFDSConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, merchant.FDSConfigRequest) error); ok {
		r0 = rf(ctx, merchantID, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateFeeConfigOnBehalf provides a mock function with given fields: ctx, id, request
func (_m *IMerchantRepository) UpdateFeeConfigOnBehalf(ctx context.Context, id string, request *merchant.UpdateFeeConfigOnBehalfRequest) error {
	ret := _m.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFeeConfigOnBehalf")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *merchant.UpdateFeeConfigOnBehalfRequest) error); ok {
		r0 = rf(ctx, id, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateFeeTieringConfig provides a mock function with given fields: ctx, request
func (_m *IMerchantRepository) UpdateFeeTieringConfig(ctx context.Context, request *merchant.FeeTieringRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFeeTieringConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.FeeTieringRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateKYC provides a mock function with given fields: ctx, payload
func (_m *IMerchantRepository) UpdateKYC(ctx context.Context, payload merchant.UpdateMerchantKYCRequest) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKYC")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, merchant.UpdateMerchantKYCRequest) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMerchantAuth provides a mock function with given fields: ctx, merchantAuth
func (_m *IMerchantRepository) UpdateMerchantAuth(ctx context.Context, merchantAuth *merchant.MerchantAuth) error {
	ret := _m.Called(ctx, merchantAuth)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMerchantAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.MerchantAuth) error); ok {
		r0 = rf(ctx, merchantAuth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMerchantFee provides a mock function with given fields: ctx, merchantFee
func (_m *IMerchantRepository) UpdateMerchantFee(ctx context.Context, merchantFee *merchant.MerchantFee) error {
	ret := _m.Called(ctx, merchantFee)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMerchantFee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.MerchantFee) error); ok {
		r0 = rf(ctx, merchantFee)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMerchantFeeLastDeductionDate provides a mock function with given fields: ctx, merchantId, reference, date
func (_m *IMerchantRepository) UpdateMerchantFeeLastDeductionDate(ctx context.Context, merchantId string, reference string, date time.Time) error {
	ret := _m.Called(ctx, merchantId, reference, date)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMerchantFeeLastDeductionDate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, merchantId, reference, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentInvestigationConfig provides a mock function with given fields: ctx, merchantID, config
func (_m *IMerchantRepository) UpdatePaymentInvestigationConfig(ctx context.Context, merchantID string, config merchant.PaymentInvestigationConfigRequest) error {
	ret := _m.Called(ctx, merchantID, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentInvestigationConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, merchant.PaymentInvestigationConfigRequest) error); ok {
		r0 = rf(ctx, merchantID, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusByID provides a mock function with given fields: ctx, status, reasonStatus, id
func (_m *IMerchantRepository) UpdateStatusByID(ctx context.Context, status string, reasonStatus string, id string) error {
	ret := _m.Called(ctx, status, reasonStatus, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, status, reasonStatus, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateThirdPartyScreeningData provides a mock function with given fields: ctx, merchantID, screeningData
func (_m *IMerchantRepository) UpdateThirdPartyScreeningData(ctx context.Context, merchantID string, screeningData types.NullJSONText) error {
	ret := _m.Called(ctx, merchantID, screeningData)

	if len(ret) == 0 {
		panic("no return value specified for UpdateThirdPartyScreeningData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.NullJSONText) error); ok {
		r0 = rf(ctx, merchantID, screeningData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionConfig provides a mock function with given fields: ctx, merchantId, config
func (_m *IMerchantRepository) UpdateTransactionConfig(ctx context.Context, merchantId string, config *merchant.TransactionConfigs) error {
	ret := _m.Called(ctx, merchantId, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *merchant.TransactionConfigs) error); ok {
		r0 = rf(ctx, merchantId, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertMerchantBOD provides a mock function with given fields: ctx, action, data
func (_m *IMerchantRepository) UpsertMerchantBOD(ctx context.Context, action string, data *merchant.BoardOfDirector) error {
	ret := _m.Called(ctx, action, data)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMerchantBOD")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *merchant.BoardOfDirector) error); ok {
		r0 = rf(ctx, action, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateCreateFeeConfigOnBehalf provides a mock function with given fields: ctx, request
func (_m *IMerchantRepository) ValidateCreateFeeConfigOnBehalf(ctx context.Context, request *merchant.CreateFeeConfigOnBehalfRequest) (bool, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCreateFeeConfigOnBehalf")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.CreateFeeConfigOnBehalfRequest) (bool, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.CreateFeeConfigOnBehalfRequest) bool); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *merchant.CreateFeeConfigOnBehalfRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateMerchantBODData provides a mock function with given fields: ctx, req
func (_m *IMerchantRepository) ValidateMerchantBODData(ctx context.Context, req *merchant.UpsertBoardOfDirectorReq) (*merchant.BODValidation, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ValidateMerchantBODData")
	}

	var r0 *merchant.BODValidation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.UpsertBoardOfDirectorReq) (*merchant.BODValidation, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *merchant.UpsertBoardOfDirectorReq) *merchant.BODValidation); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merchant.BODValidation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *merchant.UpsertBoardOfDirectorReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIMerchantRepository creates a new instance of IMerchantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMerchantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMerchantRepository {
	mock := &IMerchantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
