// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	cardFundedPayoutModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/cardFundedPayout"
	commonModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/common"

	config "github.com/paper-indonesia/pivot-backoffice/config"

	context "context"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	paymentModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/payment"

	time "time"

	unifiedPaymentModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/unifiedPayment"
)

// IPaymentRepository is an autogenerated mock type for the IPaymentRepository type
type IPaymentRepository struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields: ctx
func (_m *IPaymentRepository) BeginTransaction(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculateInvestigationMonthlyReconciliation provides a mock function with given fields: ctx, request
func (_m *IPaymentRepository) CalculateInvestigationMonthlyReconciliation(ctx context.Context, request paymentModel.MonthlyReconciliationRequest) ([]paymentModel.CalculateInvestigationMonthlyReconciliation, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CalculateInvestigationMonthlyReconciliation")
	}

	var r0 []paymentModel.CalculateInvestigationMonthlyReconciliation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.MonthlyReconciliationRequest) ([]paymentModel.CalculateInvestigationMonthlyReconciliation, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.MonthlyReconciliationRequest) []paymentModel.CalculateInvestigationMonthlyReconciliation); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]paymentModel.CalculateInvestigationMonthlyReconciliation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.MonthlyReconciliationRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangePaymentMethod provides a mock function with given fields: ctx, payment
func (_m *IPaymentRepository) ChangePaymentMethod(ctx context.Context, payment *paymentModel.PaymentDTO) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for ChangePaymentMethod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.PaymentDTO) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommitTransaction provides a mock function with given fields: ctx
func (_m *IPaymentRepository) CommitTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountActiveStaticPayment provides a mock function with given fields: ctx, merchantID, paymentMethodID
func (_m *IPaymentRepository) CountActiveStaticPayment(ctx context.Context, merchantID string, paymentMethodID string) (int, error) {
	ret := _m.Called(ctx, merchantID, paymentMethodID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveStaticPayment")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return rf(ctx, merchantID, paymentMethodID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, merchantID, paymentMethodID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantID, paymentMethodID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePayment provides a mock function with given fields: ctx, paymentDTO
func (_m *IPaymentRepository) CreatePayment(ctx context.Context, paymentDTO *paymentModel.PaymentDTO) error {
	ret := _m.Called(ctx, paymentDTO)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.PaymentDTO) error); ok {
		r0 = rf(ctx, paymentDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePaymentItem provides a mock function with given fields: ctx, paymentItemDTO
func (_m *IPaymentRepository) CreatePaymentItem(ctx context.Context, paymentItemDTO *paymentModel.PaymentItemDTO) error {
	ret := _m.Called(ctx, paymentItemDTO)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.PaymentItemDTO) error); ok {
		r0 = rf(ctx, paymentItemDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FilterPaymentHistory provides a mock function with given fields: ctx, opt
func (_m *IPaymentRepository) FilterPaymentHistory(ctx context.Context, opt paymentModel.FilterPaymentHistoryOption) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for FilterPaymentHistory")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.FilterPaymentHistoryOption) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.FilterPaymentHistoryOption) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.FilterPaymentHistoryOption) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilterStaticQrisList provides a mock function with given fields: ctx, opt
func (_m *IPaymentRepository) FilterStaticQrisList(ctx context.Context, opt paymentModel.StaticQrisFilterRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for FilterStaticQrisList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticQrisFilterRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticQrisFilterRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.StaticQrisFilterRequest) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilterStaticVaList provides a mock function with given fields: ctx, opt
func (_m *IPaymentRepository) FilterStaticVaList(ctx context.Context, opt paymentModel.StaticVaFilterRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for FilterStaticVaList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticVaFilterRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticVaFilterRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.StaticVaFilterRequest) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPendingSubsequentCardFundedPayout provides a mock function with given fields: ctx, merchantID, referenceID
func (_m *IPaymentRepository) FindPendingSubsequentCardFundedPayout(ctx context.Context, merchantID string, referenceID string) ([]cardFundedPayoutModel.CardFundedPayment, error) {
	ret := _m.Called(ctx, merchantID, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingSubsequentCardFundedPayout")
	}

	var r0 []cardFundedPayoutModel.CardFundedPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]cardFundedPayoutModel.CardFundedPayment, error)); ok {
		return rf(ctx, merchantID, referenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []cardFundedPayoutModel.CardFundedPayment); ok {
		r0 = rf(ctx, merchantID, referenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cardFundedPayoutModel.CardFundedPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantID, referenceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActivePaymentByProcessorReferenceNumber provides a mock function with given fields: ctx, request
func (_m *IPaymentRepository) GetActivePaymentByProcessorReferenceNumber(ctx context.Context, request *paymentModel.GetActivePaymentByProcessorReferenceNumberRequest) (*paymentModel.Payment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetActivePaymentByProcessorReferenceNumber")
	}

	var r0 *paymentModel.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetActivePaymentByProcessorReferenceNumberRequest) (*paymentModel.Payment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetActivePaymentByProcessorReferenceNumberRequest) *paymentModel.Payment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *paymentModel.GetActivePaymentByProcessorReferenceNumberRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAutoSplitSubPayments provides a mock function with given fields: ctx, request
func (_m *IPaymentRepository) GetAutoSplitSubPayments(ctx context.Context, request *paymentModel.GetSubPaymentsRequest) ([]*paymentModel.Payment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetAutoSplitSubPayments")
	}

	var r0 []*paymentModel.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetSubPaymentsRequest) ([]*paymentModel.Payment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetSubPaymentsRequest) []*paymentModel.Payment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*paymentModel.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *paymentModel.GetSubPaymentsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardFundedPayoutFundingSummary provides a mock function with given fields: ctx, merchantID, referenceID, maxCreatedDays
func (_m *IPaymentRepository) GetCardFundedPayoutFundingSummary(ctx context.Context, merchantID string, referenceID string, maxCreatedDays int) (*cardFundedPayoutModel.CardFundedPayoutFundingSummary, error) {
	ret := _m.Called(ctx, merchantID, referenceID, maxCreatedDays)

	if len(ret) == 0 {
		panic("no return value specified for GetCardFundedPayoutFundingSummary")
	}

	var r0 *cardFundedPayoutModel.CardFundedPayoutFundingSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*cardFundedPayoutModel.CardFundedPayoutFundingSummary, error)); ok {
		return rf(ctx, merchantID, referenceID, maxCreatedDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *cardFundedPayoutModel.CardFundedPayoutFundingSummary); ok {
		r0 = rf(ctx, merchantID, referenceID, maxCreatedDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cardFundedPayoutModel.CardFundedPayoutFundingSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, merchantID, referenceID, maxCreatedDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChargeByID provides a mock function with given fields: ctx, id
func (_m *IPaymentRepository) GetChargeByID(ctx context.Context, id string) (*unifiedPaymentModel.ChargeResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChargeByID")
	}

	var r0 *unifiedPaymentModel.ChargeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*unifiedPaymentModel.ChargeResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *unifiedPaymentModel.ChargeResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unifiedPaymentModel.ChargeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChargeList provides a mock function with given fields: ctx, request
func (_m *IPaymentRepository) GetChargeList(ctx context.Context, request *unifiedPaymentModel.FilterChargeRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetChargeList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unifiedPaymentModel.FilterChargeRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unifiedPaymentModel.FilterChargeRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unifiedPaymentModel.FilterChargeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCharges provides a mock function with given fields: ctx, request
func (_m *IPaymentRepository) GetCharges(ctx context.Context, request *unifiedPaymentModel.FilterChargeRequest) ([]unifiedPaymentModel.ChargeResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetCharges")
	}

	var r0 []unifiedPaymentModel.ChargeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unifiedPaymentModel.FilterChargeRequest) ([]unifiedPaymentModel.ChargeResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unifiedPaymentModel.FilterChargeRequest) []unifiedPaymentModel.ChargeResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]unifiedPaymentModel.ChargeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unifiedPaymentModel.FilterChargeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpiringPayments provides a mock function with given fields: ctx, start, end
func (_m *IPaymentRepository) GetExpiringPayments(ctx context.Context, start time.Time, end time.Time) ([]*paymentModel.ExpiringPayment, error) {
	ret := _m.Called(ctx, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiringPayments")
	}

	var r0 []*paymentModel.ExpiringPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]*paymentModel.ExpiringPayment, error)); ok {
		return rf(ctx, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []*paymentModel.ExpiringPayment); ok {
		r0 = rf(ctx, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*paymentModel.ExpiringPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFirstActiveStaticQrisByMerchant provides a mock function with given fields: ctx, merchantID, partnerReferenceNo
func (_m *IPaymentRepository) GetFirstActiveStaticQrisByMerchant(ctx context.Context, merchantID string, partnerReferenceNo string) (*paymentModel.Payment, error) {
	ret := _m.Called(ctx, merchantID, partnerReferenceNo)

	if len(ret) == 0 {
		panic("no return value specified for GetFirstActiveStaticQrisByMerchant")
	}

	var r0 *paymentModel.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*paymentModel.Payment, error)); ok {
		return rf(ctx, merchantID, partnerReferenceNo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *paymentModel.Payment); ok {
		r0 = rf(ctx, merchantID, partnerReferenceNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantID, partnerReferenceNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvestigatedPayments provides a mock function with given fields: ctx, filter
func (_m *IPaymentRepository) GetInvestigatedPayments(ctx context.Context, filter *paymentModel.GetInvestigatedPaymentsFilterRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetInvestigatedPayments")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetInvestigatedPaymentsFilterRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetInvestigatedPaymentsFilterRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *paymentModel.GetInvestigatedPaymentsFilterRequest) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvestigationSummary provides a mock function with given fields: ctx, opt
func (_m *IPaymentRepository) GetInvestigationSummary(ctx context.Context, opt paymentModel.GetInvestigationSummaryOption) (*paymentModel.InvestigationSummaryResponse, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for GetInvestigationSummary")
	}

	var r0 *paymentModel.InvestigationSummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.GetInvestigationSummaryOption) (*paymentModel.InvestigationSummaryResponse, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.GetInvestigationSummaryOption) *paymentModel.InvestigationSummaryResponse); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.InvestigationSummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.GetInvestigationSummaryOption) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, filter
func (_m *IPaymentRepository) GetList(ctx context.Context, filter *paymentModel.GetListFilterRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetListFilterRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetListFilterRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *paymentModel.GetListFilterRequest) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentById provides a mock function with given fields: ctx, id
func (_m *IPaymentRepository) GetPaymentById(ctx context.Context, id string) (*paymentModel.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentById")
	}

	var r0 *paymentModel.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*paymentModel.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *paymentModel.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentByIdAndMerchantId provides a mock function with given fields: ctx, id, merchantId
func (_m *IPaymentRepository) GetPaymentByIdAndMerchantId(ctx context.Context, id string, merchantId string) (*paymentModel.Payment, error) {
	ret := _m.Called(ctx, id, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByIdAndMerchantId")
	}

	var r0 *paymentModel.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*paymentModel.Payment, error)); ok {
		return rf(ctx, id, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *paymentModel.Payment); ok {
		r0 = rf(ctx, id, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentByMerchantAndReferenceId provides a mock function with given fields: ctx, merchantId, referenceId
func (_m *IPaymentRepository) GetPaymentByMerchantAndReferenceId(ctx context.Context, merchantId string, referenceId string) (*paymentModel.Payment, error) {
	ret := _m.Called(ctx, merchantId, referenceId)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByMerchantAndReferenceId")
	}

	var r0 *paymentModel.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*paymentModel.Payment, error)); ok {
		return rf(ctx, merchantId, referenceId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *paymentModel.Payment); ok {
		r0 = rf(ctx, merchantId, referenceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, referenceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentDashboardInsights provides a mock function with given fields: ctx, request
func (_m *IPaymentRepository) GetPaymentDashboardInsights(ctx context.Context, request paymentModel.GetPaymentDashboardInsightRequest) (*paymentModel.PaymentDashboardInsights, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentDashboardInsights")
	}

	var r0 *paymentModel.PaymentDashboardInsights
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.GetPaymentDashboardInsightRequest) (*paymentModel.PaymentDashboardInsights, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.GetPaymentDashboardInsightRequest) *paymentModel.PaymentDashboardInsights); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.PaymentDashboardInsights)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.GetPaymentDashboardInsightRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentItemsByPaymentId provides a mock function with given fields: ctx, paymentID
func (_m *IPaymentRepository) GetPaymentItemsByPaymentId(ctx context.Context, paymentID string) ([]*paymentModel.PaymentItem, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentItemsByPaymentId")
	}

	var r0 []*paymentModel.PaymentItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*paymentModel.PaymentItem, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*paymentModel.PaymentItem); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*paymentModel.PaymentItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentQrStaticByMerchantId provides a mock function with given fields: ctx, merchantId, subMerchantId, paymentMethodId
func (_m *IPaymentRepository) GetPaymentQrStaticByMerchantId(ctx context.Context, merchantId string, subMerchantId string, paymentMethodId string) (*paymentModel.Payment, error) {
	ret := _m.Called(ctx, merchantId, subMerchantId, paymentMethodId)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentQrStaticByMerchantId")
	}

	var r0 *paymentModel.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*paymentModel.Payment, error)); ok {
		return rf(ctx, merchantId, subMerchantId, paymentMethodId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *paymentModel.Payment); ok {
		r0 = rf(ctx, merchantId, subMerchantId, paymentMethodId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, merchantId, subMerchantId, paymentMethodId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentReceiptData provides a mock function with given fields: ctx, paymentID, referenceID, merchantID
func (_m *IPaymentRepository) GetPaymentReceiptData(ctx context.Context, paymentID string, referenceID string, merchantID string) (*paymentModel.PaymentReceiptDTO, error) {
	ret := _m.Called(ctx, paymentID, referenceID, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentReceiptData")
	}

	var r0 *paymentModel.PaymentReceiptDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*paymentModel.PaymentReceiptDTO, error)); ok {
		return rf(ctx, paymentID, referenceID, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *paymentModel.PaymentReceiptDTO); ok {
		r0 = rf(ctx, paymentID, referenceID, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.PaymentReceiptDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, paymentID, referenceID, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStaticQrisDetail provides a mock function with given fields: ctx, opt
func (_m *IPaymentRepository) GetStaticQrisDetail(ctx context.Context, opt paymentModel.StaticQrisDetailRequest) (*paymentModel.StaticQrisDetailResponse, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for GetStaticQrisDetail")
	}

	var r0 *paymentModel.StaticQrisDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticQrisDetailRequest) (*paymentModel.StaticQrisDetailResponse, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticQrisDetailRequest) *paymentModel.StaticQrisDetailResponse); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.StaticQrisDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.StaticQrisDetailRequest) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStaticQrisTransactions provides a mock function with given fields: ctx, opt
func (_m *IPaymentRepository) GetStaticQrisTransactions(ctx context.Context, opt paymentModel.StaticQrisTransactionFilterRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for GetStaticQrisTransactions")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticQrisTransactionFilterRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticQrisTransactionFilterRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.StaticQrisTransactionFilterRequest) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStaticVaDetail provides a mock function with given fields: ctx, opt
func (_m *IPaymentRepository) GetStaticVaDetail(ctx context.Context, opt paymentModel.StaticVaDetailRequest) (*paymentModel.StaticVaDetailResponse, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for GetStaticVaDetail")
	}

	var r0 *paymentModel.StaticVaDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticVaDetailRequest) (*paymentModel.StaticVaDetailResponse, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticVaDetailRequest) *paymentModel.StaticVaDetailResponse); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.StaticVaDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.StaticVaDetailRequest) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStaticVaTransactions provides a mock function with given fields: ctx, opt
func (_m *IPaymentRepository) GetStaticVaTransactions(ctx context.Context, opt paymentModel.StaticVaTransactionFilterRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for GetStaticVaTransactions")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticVaTransactionFilterRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.StaticVaTransactionFilterRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.StaticVaTransactionFilterRequest) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSummaryAutoSplitPayment provides a mock function with given fields: ctx, request
func (_m *IPaymentRepository) GetSummaryAutoSplitPayment(ctx context.Context, request *paymentModel.GetAutoSplitPaymentSummaryRequest) (*paymentModel.AutoSplitPaymentSummary, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaryAutoSplitPayment")
	}

	var r0 *paymentModel.AutoSplitPaymentSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetAutoSplitPaymentSummaryRequest) (*paymentModel.AutoSplitPaymentSummary, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetAutoSplitPaymentSummaryRequest) *paymentModel.AutoSplitPaymentSummary); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.AutoSplitPaymentSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *paymentModel.GetAutoSplitPaymentSummaryRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTodayPaymentStatusInsight provides a mock function with given fields: ctx, opt
func (_m *IPaymentRepository) GetTodayPaymentStatusInsight(ctx context.Context, opt paymentModel.PaymentInsightOption) (*paymentModel.PaymentInsightItem, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for GetTodayPaymentStatusInsight")
	}

	var r0 *paymentModel.PaymentInsightItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.PaymentInsightOption) (*paymentModel.PaymentInsightItem, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.PaymentInsightOption) *paymentModel.PaymentInsightItem); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentModel.PaymentInsightItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paymentModel.PaymentInsightOption) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVCCTerminalList provides a mock function with given fields: ctx, filter
func (_m *IPaymentRepository) GetVCCTerminalList(ctx context.Context, filter *paymentModel.GetVCCTerminalListFilterRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetVCCTerminalList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetVCCTerminalListFilterRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.GetVCCTerminalListFilterRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *paymentModel.GetVCCTerminalListFilterRequest) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDeleteAutoSplitSubPayments provides a mock function with given fields: ctx, merchantID, referenceID
func (_m *IPaymentRepository) HardDeleteAutoSplitSubPayments(ctx context.Context, merchantID string, referenceID string) error {
	ret := _m.Called(ctx, merchantID, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteAutoSplitSubPayments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, merchantID, referenceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HardDeleteCardFundedPayoutPayments provides a mock function with given fields: ctx, merchantID, referenceID
func (_m *IPaymentRepository) HardDeleteCardFundedPayoutPayments(ctx context.Context, merchantID string, referenceID string) error {
	ret := _m.Called(ctx, merchantID, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteCardFundedPayoutPayments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, merchantID, referenceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertInvestigationMonthlyReconciliation provides a mock function with given fields: ctx, data
func (_m *IPaymentRepository) InsertInvestigationMonthlyReconciliation(ctx context.Context, data paymentModel.PaymentInvestigationMonthlyReconciliation) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for InsertInvestigationMonthlyReconciliation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.PaymentInvestigationMonthlyReconciliation) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveImages provides a mock function with given fields: ctx
func (_m *IPaymentRepository) RetrieveImages(ctx context.Context) (paymentModel.ImageResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveImages")
	}

	var r0 paymentModel.ImageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (paymentModel.ImageResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) paymentModel.ImageResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(paymentModel.ImageResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveInstructions provides a mock function with given fields: ctx
func (_m *IPaymentRepository) RetrieveInstructions(ctx context.Context) ([]paymentModel.InstructionResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveInstructions")
	}

	var r0 []paymentModel.InstructionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]paymentModel.InstructionResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []paymentModel.InstructionResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]paymentModel.InstructionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollbackTransaction provides a mock function with given fields: ctx
func (_m *IPaymentRepository) RollbackTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateInvestigationStatus provides a mock function with given fields: ctx, request
func (_m *IPaymentRepository) UpdateInvestigationStatus(ctx context.Context, request paymentModel.UpdateInvestigationStatusRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInvestigationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.UpdateInvestigationStatusRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePayment provides a mock function with given fields: ctx, id, amount, totalAmount, metadata, customerId, expiredAt
func (_m *IPaymentRepository) UpdatePayment(ctx context.Context, id string, amount decimal.Decimal, totalAmount decimal.Decimal, metadata string, customerId string, expiredAt time.Time) error {
	ret := _m.Called(ctx, id, amount, totalAmount, metadata, customerId, expiredAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, decimal.Decimal, decimal.Decimal, string, string, time.Time) error); ok {
		r0 = rf(ctx, id, amount, totalAmount, metadata, customerId, expiredAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentData provides a mock function with given fields: ctx, payment
func (_m *IPaymentRepository) UpdatePaymentData(ctx context.Context, payment *paymentModel.PaymentDTO) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentModel.PaymentDTO) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentForInvestigation provides a mock function with given fields: ctx, request
func (_m *IPaymentRepository) UpdatePaymentForInvestigation(ctx context.Context, request paymentModel.UpdatePaymentForInvestigationRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentForInvestigation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.UpdatePaymentForInvestigationRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentInvestigationReconciliation provides a mock function with given fields: ctx, data
func (_m *IPaymentRepository) UpdatePaymentInvestigationReconciliation(ctx context.Context, data paymentModel.PaymentInvestigationMonthlyReconciliation) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentInvestigationReconciliation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, paymentModel.PaymentInvestigationMonthlyReconciliation) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentItemsFromPaymentResponseItem provides a mock function with given fields: ctx, paymentID, paymentRespItems
func (_m *IPaymentRepository) UpdatePaymentItemsFromPaymentResponseItem(ctx context.Context, paymentID string, paymentRespItems []paymentModel.PaymentResponseItem) error {
	ret := _m.Called(ctx, paymentID, paymentRespItems)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentItemsFromPaymentResponseItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []paymentModel.PaymentResponseItem) error); ok {
		r0 = rf(ctx, paymentID, paymentRespItems)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentMetadataById provides a mock function with given fields: ctx, id, metadata
func (_m *IPaymentRepository) UpdatePaymentMetadataById(ctx context.Context, id string, metadata paymentModel.UpdatePaymentMetadataRequest) error {
	ret := _m.Called(ctx, id, metadata)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentMetadataById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, paymentModel.UpdatePaymentMetadataRequest) error); ok {
		r0 = rf(ctx, id, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentStatus provides a mock function with given fields: ctx, id, merchantId, status, updatedAt
func (_m *IPaymentRepository) UpdatePaymentStatus(ctx context.Context, id string, merchantId string, status string, updatedAt time.Time) error {
	ret := _m.Called(ctx, id, merchantId, status, updatedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) error); ok {
		r0 = rf(ctx, id, merchantId, status, updatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentStatusWithReason provides a mock function with given fields: ctx, id, request
func (_m *IPaymentRepository) UpdatePaymentStatusWithReason(ctx context.Context, id string, request paymentModel.UpdatePaymentStatusWithReasonRequest) error {
	ret := _m.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatusWithReason")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, paymentModel.UpdatePaymentStatusWithReasonRequest) error); ok {
		r0 = rf(ctx, id, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithConfig provides a mock function with given fields: _a0
func (_m *IPaymentRepository) WithConfig(_a0 *config.Config) {
	_m.Called(_a0)
}

// WithSecret provides a mock function with given fields: secret
func (_m *IPaymentRepository) WithSecret(secret *config.Secret) {
	_m.Called(secret)
}

// NewIPaymentRepository creates a new instance of IPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPaymentRepository {
	mock := &IPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
