// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	product "github.com/paper-indonesia/pivot-backoffice/internal/model/product"
	mock "github.com/stretchr/testify/mock"
)

// IProductRepository is an autogenerated mock type for the IProductRepository type
type IProductRepository struct {
	mock.Mock
}

// AddMerchantSelectedProduct provides a mock function with given fields: ctx, req
func (_m *IProductRepository) AddMerchantSelectedProduct(ctx context.Context, req *product.MerchantSelectedProduct) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddMerchantSelectedProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.MerchantSelectedProduct) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMerchantActiveProducts provides a mock function with given fields: ctx, merchantId
func (_m *IProductRepository) GetMerchantActiveProducts(ctx context.Context, merchantId string) ([]*product.MerchantWithProductName, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantActiveProducts")
	}

	var r0 []*product.MerchantWithProductName
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*product.MerchantWithProductName, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*product.MerchantWithProductName); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*product.MerchantWithProductName)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantSelectedProductById provides a mock function with given fields: ctx, merchantId, productId
func (_m *IProductRepository) GetMerchantSelectedProductById(ctx context.Context, merchantId string, productId string) (*product.MerchantWithProductName, error) {
	ret := _m.Called(ctx, merchantId, productId)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantSelectedProductById")
	}

	var r0 *product.MerchantWithProductName
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*product.MerchantWithProductName, error)); ok {
		return rf(ctx, merchantId, productId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *product.MerchantWithProductName); ok {
		r0 = rf(ctx, merchantId, productId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.MerchantWithProductName)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantSelectedProductByName provides a mock function with given fields: ctx, merchantId, productName
func (_m *IProductRepository) GetMerchantSelectedProductByName(ctx context.Context, merchantId string, productName string) (*product.MerchantWithProductName, error) {
	ret := _m.Called(ctx, merchantId, productName)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantSelectedProductByName")
	}

	var r0 *product.MerchantWithProductName
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*product.MerchantWithProductName, error)); ok {
		return rf(ctx, merchantId, productName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *product.MerchantWithProductName); ok {
		r0 = rf(ctx, merchantId, productName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.MerchantWithProductName)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, merchantId, productName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantSelectedProducts provides a mock function with given fields: ctx, merchantId
func (_m *IProductRepository) GetMerchantSelectedProducts(ctx context.Context, merchantId string) ([]*product.MerchantWithProductName, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantSelectedProducts")
	}

	var r0 []*product.MerchantWithProductName
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*product.MerchantWithProductName, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*product.MerchantWithProductName); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*product.MerchantWithProductName)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductById provides a mock function with given fields: ctx, productId
func (_m *IProductRepository) GetProductById(ctx context.Context, productId string) (*product.Product, error) {
	ret := _m.Called(ctx, productId)

	if len(ret) == 0 {
		panic("no return value specified for GetProductById")
	}

	var r0 *product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*product.Product, error)); ok {
		return rf(ctx, productId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *product.Product); ok {
		r0 = rf(ctx, productId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductList provides a mock function with given fields: ctx
func (_m *IProductRepository) GetProductList(ctx context.Context) ([]*product.Product, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProductList")
	}

	var r0 []*product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*product.Product, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*product.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMerchantProductAvailability provides a mock function with given fields: ctx, req
func (_m *IProductRepository) UpdateMerchantProductAvailability(ctx context.Context, req *product.UpdateMerchantSelectedProductAvailabilityRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMerchantProductAvailability")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.UpdateMerchantSelectedProductAvailabilityRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProductAvailability provides a mock function with given fields: ctx, req
func (_m *IProductRepository) UpdateProductAvailability(ctx context.Context, req *product.UpdateProductRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProductAvailability")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.UpdateProductRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIProductRepository creates a new instance of IProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProductRepository {
	mock := &IProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
