// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	qris "github.com/paper-indonesia/pivot-backoffice/internal/model/qris"
	mock "github.com/stretchr/testify/mock"
)

// IQrisRepository is an autogenerated mock type for the IQrisRepository type
type IQrisRepository struct {
	mock.Mock
}

// FindQrRegistrationByExternalID provides a mock function with given fields: ctx, externalID
func (_m *IQrisRepository) FindQrRegistrationByExternalID(ctx context.Context, externalID string) (*qris.Registration, error) {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindQrRegistrationByExternalID")
	}

	var r0 *qris.Registration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*qris.Registration, error)); ok {
		return rf(ctx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *qris.Registration); ok {
		r0 = rf(ctx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qris.Registration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindQrRegistrationByExternalIDAndAcquirer provides a mock function with given fields: ctx, externalID, acquirer
func (_m *IQrisRepository) FindQrRegistrationByExternalIDAndAcquirer(ctx context.Context, externalID string, acquirer string) (*qris.Registration, error) {
	ret := _m.Called(ctx, externalID, acquirer)

	if len(ret) == 0 {
		panic("no return value specified for FindQrRegistrationByExternalIDAndAcquirer")
	}

	var r0 *qris.Registration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*qris.Registration, error)); ok {
		return rf(ctx, externalID, acquirer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *qris.Registration); ok {
		r0 = rf(ctx, externalID, acquirer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qris.Registration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, externalID, acquirer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindQrRegistrationForValidationById provides a mock function with given fields: ctx, id
func (_m *IQrisRepository) FindQrRegistrationForValidationById(ctx context.Context, id string) (*qris.Registration, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindQrRegistrationForValidationById")
	}

	var r0 *qris.Registration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*qris.Registration, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *qris.Registration); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qris.Registration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindRegistrationById provides a mock function with given fields: ctx, id
func (_m *IQrisRepository) FindRegistrationById(ctx context.Context, id string) (*qris.RegistrationMerchant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindRegistrationById")
	}

	var r0 *qris.RegistrationMerchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*qris.RegistrationMerchant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *qris.RegistrationMerchant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qris.RegistrationMerchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitRegistration provides a mock function with given fields: ctx, data
func (_m *IQrisRepository) InitRegistration(ctx context.Context, data *qris.Registration) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for InitRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *qris.Registration) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistrationList provides a mock function with given fields: ctx, merchantId
func (_m *IQrisRepository) RegistrationList(ctx context.Context, merchantId string) ([]qris.RegistrationListResp, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for RegistrationList")
	}

	var r0 []qris.RegistrationListResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]qris.RegistrationListResp, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []qris.RegistrationListResp); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]qris.RegistrationListResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCallbackQrRegistration provides a mock function with given fields: ctx, id, data
func (_m *IQrisRepository) UpdateCallbackQrRegistration(ctx context.Context, id string, data *qris.RegistrationCallback) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCallbackQrRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *qris.RegistrationCallback) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateQrRegistration provides a mock function with given fields: ctx, id, acquirerMerchantId, acquirerTerminalId
func (_m *IQrisRepository) UpdateQrRegistration(ctx context.Context, id string, acquirerMerchantId string, acquirerTerminalId string) error {
	ret := _m.Called(ctx, id, acquirerMerchantId, acquirerTerminalId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQrRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, id, acquirerMerchantId, acquirerTerminalId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRegistrationStatus provides a mock function with given fields: ctx, id, status
func (_m *IQrisRepository) UpdateRegistrationStatus(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRegistrationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUploadedDocument provides a mock function with given fields: ctx, id, data
func (_m *IQrisRepository) UpdateUploadedDocument(ctx context.Context, id string, data *qris.UpdateDocument) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUploadedDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *qris.UpdateDocument) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIQrisRepository creates a new instance of IQrisRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIQrisRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IQrisRepository {
	mock := &IQrisRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
