// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	ratelimiter "github.com/paper-indonesia/pivot-backoffice/internal/model/rateLimiter"
	mock "github.com/stretchr/testify/mock"
)

// IRateLimiterRepository is an autogenerated mock type for the IRateLimiterRepository type
type IRateLimiterRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, configuration
func (_m *IRateLimiterRepository) Create(ctx context.Context, configuration *ratelimiter.RateLimitConfiguration) error {
	ret := _m.Called(ctx, configuration)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ratelimiter.RateLimitConfiguration) error); ok {
		r0 = rf(ctx, configuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Detail provides a mock function with given fields: ctx, uuid
func (_m *IRateLimiterRepository) Detail(ctx context.Context, uuid string) (*ratelimiter.RateLimitConfiguration, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Detail")
	}

	var r0 *ratelimiter.RateLimitConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ratelimiter.RateLimitConfiguration, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ratelimiter.RateLimitConfiguration); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ratelimiter.RateLimitConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchantConfigs provides a mock function with given fields: ctx, merchantID
func (_m *IRateLimiterRepository) GetMerchantConfigs(ctx context.Context, merchantID string) (*[]ratelimiter.MerchantRateLimitConfig, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantConfigs")
	}

	var r0 *[]ratelimiter.MerchantRateLimitConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*[]ratelimiter.MerchantRateLimitConfig, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *[]ratelimiter.MerchantRateLimitConfig); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]ratelimiter.MerchantRateLimitConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, req
func (_m *IRateLimiterRepository) List(ctx context.Context, req *ratelimiter.MerchantRateLimitRequest) ([]*ratelimiter.RateLimitConfiguration, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*ratelimiter.RateLimitConfiguration
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *ratelimiter.MerchantRateLimitRequest) ([]*ratelimiter.RateLimitConfiguration, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ratelimiter.MerchantRateLimitRequest) []*ratelimiter.RateLimitConfiguration); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ratelimiter.RateLimitConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ratelimiter.MerchantRateLimitRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *ratelimiter.MerchantRateLimitRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, configuration
func (_m *IRateLimiterRepository) Update(ctx context.Context, configuration *ratelimiter.RateLimitConfiguration) error {
	ret := _m.Called(ctx, configuration)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ratelimiter.RateLimitConfiguration) error); ok {
		r0 = rf(ctx, configuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIRateLimiterRepository creates a new instance of IRateLimiterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRateLimiterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRateLimiterRepository {
	mock := &IRateLimiterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
