// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	commonModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/common"

	mock "github.com/stretchr/testify/mock"

	refundModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/refund"
)

// IRefundRepository is an autogenerated mock type for the IRefundRepository type
type IRefundRepository struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields: ctx
func (_m *IRefundRepository) BeginTransaction(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitTransaction provides a mock function with given fields: ctx
func (_m *IRefundRepository) CommitTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistsByClientReferenceAndMerchantID provides a mock function with given fields: ctx, clientReferenceID, merchantID
func (_m *IRefundRepository) ExistsByClientReferenceAndMerchantID(ctx context.Context, clientReferenceID string, merchantID string) (bool, error) {
	ret := _m.Called(ctx, clientReferenceID, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByClientReferenceAndMerchantID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, clientReferenceID, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, clientReferenceID, merchantID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, clientReferenceID, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *IRefundRepository) FindByID(ctx context.Context, id string) (*refundModel.Refund, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *refundModel.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*refundModel.Refund, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *refundModel.Refund); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*refundModel.Refund)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindRefundByChargeID provides a mock function with given fields: ctx, chargeID
func (_m *IRefundRepository) FindRefundByChargeID(ctx context.Context, chargeID string) (*refundModel.Refund, error) {
	ret := _m.Called(ctx, chargeID)

	if len(ret) == 0 {
		panic("no return value specified for FindRefundByChargeID")
	}

	var r0 *refundModel.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*refundModel.Refund, error)); ok {
		return rf(ctx, chargeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *refundModel.Refund); ok {
		r0 = rf(ctx, chargeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*refundModel.Refund)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chargeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRefundByID provides a mock function with given fields: ctx, refundID, merchantID
func (_m *IRefundRepository) GetRefundByID(ctx context.Context, refundID string, merchantID string) (*refundModel.RefundResponse, error) {
	ret := _m.Called(ctx, refundID, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefundByID")
	}

	var r0 *refundModel.RefundResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*refundModel.RefundResponse, error)); ok {
		return rf(ctx, refundID, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *refundModel.RefundResponse); ok {
		r0 = rf(ctx, refundID, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*refundModel.RefundResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, refundID, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRefundList provides a mock function with given fields: ctx, request
func (_m *IRefundRepository) GetRefundList(ctx context.Context, request refundModel.FilterRefundRequest) (*commonModel.PaginationResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetRefundList")
	}

	var r0 *commonModel.PaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, refundModel.FilterRefundRequest) (*commonModel.PaginationResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, refundModel.FilterRefundRequest) *commonModel.PaginationResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonModel.PaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, refundModel.FilterRefundRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalRefundedAmount provides a mock function with given fields: ctx, paymentID
func (_m *IRefundRepository) GetTotalRefundedAmount(ctx context.Context, paymentID string) (float64, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalRefundedAmount")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, paymentID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, refund
func (_m *IRefundRepository) Insert(ctx context.Context, refund *refundModel.Refund) error {
	ret := _m.Called(ctx, refund)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *refundModel.Refund) error); ok {
		r0 = rf(ctx, refund)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListByPaymentID provides a mock function with given fields: ctx, paymentID, request
func (_m *IRefundRepository) ListByPaymentID(ctx context.Context, paymentID string, request refundModel.ListByPaymentIDRequest) ([]refundModel.RefundResponse, error) {
	ret := _m.Called(ctx, paymentID, request)

	if len(ret) == 0 {
		panic("no return value specified for ListByPaymentID")
	}

	var r0 []refundModel.RefundResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, refundModel.ListByPaymentIDRequest) ([]refundModel.RefundResponse, error)); ok {
		return rf(ctx, paymentID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, refundModel.ListByPaymentIDRequest) []refundModel.RefundResponse); ok {
		r0 = rf(ctx, paymentID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]refundModel.RefundResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, refundModel.ListByPaymentIDRequest) error); ok {
		r1 = rf(ctx, paymentID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollbackTransaction provides a mock function with given fields: ctx
func (_m *IRefundRepository) RollbackTransaction(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateData provides a mock function with given fields: ctx, refund
func (_m *IRefundRepository) UpdateData(ctx context.Context, refund *refundModel.Refund) error {
	ret := _m.Called(ctx, refund)

	if len(ret) == 0 {
		panic("no return value specified for UpdateData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *refundModel.Refund) error); ok {
		r0 = rf(ctx, refund)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIRefundRepository creates a new instance of IRefundRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRefundRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRefundRepository {
	mock := &IRefundRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
