// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	partitionModel "github.com/paper-indonesia/pivot-backoffice/internal/model/backendportal/partition"
	mock "github.com/stretchr/testify/mock"
)

// ITablePartitionRepository is an autogenerated mock type for the ITablePartitionRepository type
type ITablePartitionRepository struct {
	mock.Mock
}

// GetPartitionNames provides a mock function with given fields: ctx, tableName, ordinalPartitionOrder, limit
func (_m *ITablePartitionRepository) GetPartitionNames(ctx context.Context, tableName string, ordinalPartitionOrder string, limit int) ([]string, error) {
	ret := _m.Called(ctx, tableName, ordinalPartitionOrder, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPartitionNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) ([]string, error)); ok {
		return rf(ctx, tableName, ordinalPartitionOrder, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) []string); ok {
		r0 = rf(ctx, tableName, ordinalPartitionOrder, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, tableName, ordinalPartitionOrder, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReorganizeDailyRangePartition provides a mock function with given fields: ctx, request
func (_m *ITablePartitionRepository) ReorganizeDailyRangePartition(ctx context.Context, request partitionModel.ReorganizeRangePartitionRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ReorganizeDailyRangePartition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, partitionModel.ReorganizeRangePartitionRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReorganizeMonthlyRangePartition provides a mock function with given fields: ctx, request
func (_m *ITablePartitionRepository) ReorganizeMonthlyRangePartition(ctx context.Context, request partitionModel.ReorganizeRangePartitionRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ReorganizeMonthlyRangePartition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, partitionModel.ReorganizeRangePartitionRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewITablePartitionRepository creates a new instance of ITablePartitionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITablePartitionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITablePartitionRepository {
	mock := &ITablePartitionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
