// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	vccSettlement "github.com/paper-indonesia/pivot-backoffice/internal/model/vccSettlement"
)

// IVCCSettlementRepository is an autogenerated mock type for the IVCCSettlementRepository type
type IVCCSettlementRepository struct {
	mock.Mock
}

// BulkInsert provides a mock function with given fields: ctx, data
func (_m *IVCCSettlementRepository) BulkInsert(ctx context.Context, data []*vccSettlement.VccSettlement) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*vccSettlement.VccSettlement) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, rcnId, postingDate
func (_m *IVCCSettlementRepository) Delete(ctx context.Context, rcnId string, postingDate time.Time) error {
	ret := _m.Called(ctx, rcnId, postingDate)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, rcnId, postingDate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIVCCSettlementRepository creates a new instance of IVCCSettlementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIVCCSettlementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IVCCSettlementRepository {
	mock := &IVCCSettlementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
