// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: payment-gateway/backend-portal/messages/callback/sub_account_registration.proto

package callback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubAccountRegistration struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SubAccountId        string                 `protobuf:"bytes,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	SubAccountStatus    string                 `protobuf:"bytes,2,opt,name=sub_account_status,json=subAccountStatus,proto3" json:"sub_account_status,omitempty"`
	SubAccountKycStatus string                 `protobuf:"bytes,3,opt,name=sub_account_kyc_status,json=subAccountKycStatus,proto3" json:"sub_account_kyc_status,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubAccountRegistration) Reset() {
	*x = SubAccountRegistration{}
	mi := &file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAccountRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAccountRegistration) ProtoMessage() {}

func (x *SubAccountRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAccountRegistration.ProtoReflect.Descriptor instead.
func (*SubAccountRegistration) Descriptor() ([]byte, []int) {
	return file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDescGZIP(), []int{0}
}

func (x *SubAccountRegistration) GetSubAccountId() string {
	if x != nil {
		return x.SubAccountId
	}
	return ""
}

func (x *SubAccountRegistration) GetSubAccountStatus() string {
	if x != nil {
		return x.SubAccountStatus
	}
	return ""
}

func (x *SubAccountRegistration) GetSubAccountKycStatus() string {
	if x != nil {
		return x.SubAccountKycStatus
	}
	return ""
}

func (x *SubAccountRegistration) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto protoreflect.FileDescriptor

const file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDesc = "" +
	"\n" +
	"Opayment-gateway/backend-portal/messages/callback/sub_account_registration.proto\x12\bcallback\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\x16SubAccountRegistration\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\tR\fsubAccountId\x12,\n" +
	"\x12sub_account_status\x18\x02 \x01(\tR\x10subAccountStatus\x123\n" +
	"\x16sub_account_kyc_status\x18\x03 \x01(\tR\x13subAccountKycStatus\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBSZQgithub.com/paper-indonesia/proto/payment-gateway/backend-portal/messages/callbackb\x06proto3"

var (
	file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDescOnce sync.Once
	file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDescData []byte
)

func file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDescGZIP() []byte {
	file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDescOnce.Do(func() {
		file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDesc), len(file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDesc)))
	})
	return file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDescData
}

var file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_goTypes = []any{
	(*SubAccountRegistration)(nil), // 0: callback.SubAccountRegistration
	(*timestamppb.Timestamp)(nil),  // 1: google.protobuf.Timestamp
}
var file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_depIdxs = []int32{
	1, // 0: callback.SubAccountRegistration.updated_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_init()
}
func file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_init() {
	if File_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDesc), len(file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_goTypes,
		DependencyIndexes: file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_depIdxs,
		MessageInfos:      file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_msgTypes,
	}.Build()
	File_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto = out.File
	file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_goTypes = nil
	file_payment_gateway_backend_portal_messages_callback_sub_account_registration_proto_depIdxs = nil
}
