// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: virtual_card.proto

package callback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtualCardCallbackRequest struct {
	state              protoimpl.MessageState              `protogen:"open.v1"`
	TrxTimestamp       int64                               `protobuf:"varint,1,opt,name=trx_timestamp,json=trxTimestamp,proto3" json:"trx_timestamp,omitempty"`
	AuthorizationCode  string                              `protobuf:"bytes,2,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	ResponseCode       string                              `protobuf:"bytes,3,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	TransactionId      string                              `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserRefId          string                              `protobuf:"bytes,5,opt,name=user_ref_id,json=userRefId,proto3" json:"user_ref_id,omitempty"`
	CardId             string                              `protobuf:"bytes,6,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	CumulativeLimit    float64                             `protobuf:"fixed64,7,opt,name=cumulative_limit,json=cumulativeLimit,proto3" json:"cumulative_limit,omitempty"`
	Amount             float64                             `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrencyCode       string                              `protobuf:"bytes,9,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	OriginAmount       float64                             `protobuf:"fixed64,10,opt,name=origin_amount,json=originAmount,proto3" json:"origin_amount,omitempty"`
	OriginCurrencyCode string                              `protobuf:"bytes,11,opt,name=origin_currency_code,json=originCurrencyCode,proto3" json:"origin_currency_code,omitempty"`
	Type               string                              `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	Status             string                              `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	ExternalId         string                              `protobuf:"bytes,14,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Merchant           *VirtualCardCallbackRequestMerchant `protobuf:"bytes,15,opt,name=merchant,proto3" json:"merchant,omitempty"`
	ResultCode         string                              `protobuf:"bytes,16,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VirtualCardCallbackRequest) Reset() {
	*x = VirtualCardCallbackRequest{}
	mi := &file_virtual_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualCardCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualCardCallbackRequest) ProtoMessage() {}

func (x *VirtualCardCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtual_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualCardCallbackRequest.ProtoReflect.Descriptor instead.
func (*VirtualCardCallbackRequest) Descriptor() ([]byte, []int) {
	return file_virtual_card_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualCardCallbackRequest) GetTrxTimestamp() int64 {
	if x != nil {
		return x.TrxTimestamp
	}
	return 0
}

func (x *VirtualCardCallbackRequest) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetUserRefId() string {
	if x != nil {
		return x.UserRefId
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetCumulativeLimit() float64 {
	if x != nil {
		return x.CumulativeLimit
	}
	return 0
}

func (x *VirtualCardCallbackRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *VirtualCardCallbackRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetOriginAmount() float64 {
	if x != nil {
		return x.OriginAmount
	}
	return 0
}

func (x *VirtualCardCallbackRequest) GetOriginCurrencyCode() string {
	if x != nil {
		return x.OriginCurrencyCode
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *VirtualCardCallbackRequest) GetMerchant() *VirtualCardCallbackRequestMerchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

func (x *VirtualCardCallbackRequest) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

type VirtualCardCallbackRequestMerchant struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryCode       string                 `protobuf:"bytes,2,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StateOrCountryCode string                 `protobuf:"bytes,4,opt,name=state_or_country_code,json=stateOrCountryCode,proto3" json:"state_or_country_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VirtualCardCallbackRequestMerchant) Reset() {
	*x = VirtualCardCallbackRequestMerchant{}
	mi := &file_virtual_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualCardCallbackRequestMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualCardCallbackRequestMerchant) ProtoMessage() {}

func (x *VirtualCardCallbackRequestMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_virtual_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualCardCallbackRequestMerchant.ProtoReflect.Descriptor instead.
func (*VirtualCardCallbackRequestMerchant) Descriptor() ([]byte, []int) {
	return file_virtual_card_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualCardCallbackRequestMerchant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VirtualCardCallbackRequestMerchant) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *VirtualCardCallbackRequestMerchant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualCardCallbackRequestMerchant) GetStateOrCountryCode() string {
	if x != nil {
		return x.StateOrCountryCode
	}
	return ""
}

var File_virtual_card_proto protoreflect.FileDescriptor

const file_virtual_card_proto_rawDesc = "" +
	"\n" +
	"\x12virtual_card.proto\x12\bcallback\"\xec\x04\n" +
	"\x1aVirtualCardCallbackRequest\x12#\n" +
	"\rtrx_timestamp\x18\x01 \x01(\x03R\ftrxTimestamp\x12-\n" +
	"\x12authorization_code\x18\x02 \x01(\tR\x11authorizationCode\x12#\n" +
	"\rresponse_code\x18\x03 \x01(\tR\fresponseCode\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12\x1e\n" +
	"\vuser_ref_id\x18\x05 \x01(\tR\tuserRefId\x12\x17\n" +
	"\acard_id\x18\x06 \x01(\tR\x06cardId\x12)\n" +
	"\x10cumulative_limit\x18\a \x01(\x01R\x0fcumulativeLimit\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12#\n" +
	"\rcurrency_code\x18\t \x01(\tR\fcurrencyCode\x12#\n" +
	"\rorigin_amount\x18\n" +
	" \x01(\x01R\foriginAmount\x120\n" +
	"\x14origin_currency_code\x18\v \x01(\tR\x12originCurrencyCode\x12\x12\n" +
	"\x04type\x18\f \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1f\n" +
	"\vexternal_id\x18\x0e \x01(\tR\n" +
	"externalId\x12H\n" +
	"\bmerchant\x18\x0f \x01(\v2,.callback.VirtualCardCallbackRequestMerchantR\bmerchant\x12\x1f\n" +
	"\vresult_code\x18\x10 \x01(\tR\n" +
	"resultCode\"\xa0\x01\n" +
	"\"VirtualCardCallbackRequestMerchant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcategory_code\x18\x02 \x01(\tR\fcategoryCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x121\n" +
	"\x15state_or_country_code\x18\x04 \x01(\tR\x12stateOrCountryCodeBSZQgithub.com/paper-indonesia/proto/payment-gateway/backend-portal/messages/callbackb\x06proto3"

var (
	file_virtual_card_proto_rawDescOnce sync.Once
	file_virtual_card_proto_rawDescData []byte
)

func file_virtual_card_proto_rawDescGZIP() []byte {
	file_virtual_card_proto_rawDescOnce.Do(func() {
		file_virtual_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_virtual_card_proto_rawDesc), len(file_virtual_card_proto_rawDesc)))
	})
	return file_virtual_card_proto_rawDescData
}

var file_virtual_card_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_virtual_card_proto_goTypes = []any{
	(*VirtualCardCallbackRequest)(nil),         // 0: callback.VirtualCardCallbackRequest
	(*VirtualCardCallbackRequestMerchant)(nil), // 1: callback.VirtualCardCallbackRequestMerchant
}
var file_virtual_card_proto_depIdxs = []int32{
	1, // 0: callback.VirtualCardCallbackRequest.merchant:type_name -> callback.VirtualCardCallbackRequestMerchant
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_virtual_card_proto_init() }
func file_virtual_card_proto_init() {
	if File_virtual_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_virtual_card_proto_rawDesc), len(file_virtual_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_virtual_card_proto_goTypes,
		DependencyIndexes: file_virtual_card_proto_depIdxs,
		MessageInfos:      file_virtual_card_proto_msgTypes,
	}.Build()
	File_virtual_card_proto = out.File
	file_virtual_card_proto_goTypes = nil
	file_virtual_card_proto_depIdxs = nil
}
