// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	storage "cloud.google.com/go/storage"
	mock "github.com/stretchr/testify/mock"
)

// WriterOpts is an autogenerated mock type for the WriterOpts type
type WriterOpts struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *WriterOpts) Execute(_a0 *storage.Writer) {
	_m.Called(_a0)
}

// NewWriterOpts creates a new instance of WriterOpts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriterOpts(t interface {
	mock.TestingT
	Cleanup(func())
}) *WriterOpts {
	mock := &WriterOpts{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
