package docs

import (
	_ "embed"
	"github.com/paper-indonesia/pivot-backoffice/config"
	"github.com/swaggo/swag"
	"gopkg.in/yaml.v2"
)

//go:embed swagger.yaml
var contents []byte

var (
	ENVIRONMENT, LOCAL, STAGING, PRODUCTION string
)

type OpenAPI interface {
	ReadDoc() string
}

type apiSpec struct {
	config *config.Config
	*swag.Spec
}

func New(cfg *config.Config) OpenAPI {
	ENVIRONMENT = cfg.Environment
	LOCAL = cfg.Host.Local
	STAGING = cfg.Host.Staging
	PRODUCTION = cfg.Host.Production

	return &apiSpec{config: cfg}
}

func (s *apiSpec) ReadDoc() string {
	var (
		temp                  SwaggerSpec
		prodServer, devServer Servers
	)

	// unmarshal swagger.yaml contents
	err := yaml.Unmarshal(contents, &temp)
	if err != nil {
		panic(err)
	}

	// remove old server generated by swag
	newServers := temp.Servers[:0]

	// if the environment is production, only add production server
	if ENVIRONMENT == "production" {
		temp.Servers = append(newServers, Servers{
			URL:         PRODUCTION,
			Description: "Production server",
		})
	} else if ENVIRONMENT == "local" {
		temp.Servers = append(newServers, Servers{
			URL:         LOCAL,
			Description: "Local server",
		})
	} else if ENVIRONMENT == "staging" {
		// if the environment is staging, add multiple servers, expected to be accessed by internal
		prodServer = Servers{
			URL:         PRODUCTION,
			Description: "Production server",
		}

		devServer = Servers{
			URL:         STAGING,
			Description: "Staging server",
		}

		temp.Servers = append(newServers, prodServer, devServer)
	}

	// marshal the updated temp
	contents, err = yaml.Marshal(temp)
	if err != nil {
		panic(err)
	}

	return string(contents)
}

func init() {
	swag.Register("swagger", &apiSpec{})
}
