// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	redis_rate "github.com/go-redis/redis_rate/v10"
)

// ILimiter is an autogenerated mock type for the ILimiter type
type ILimiter struct {
	mock.Mock
}

// Allow provides a mock function with given fields: ctx, key, limit
func (_m *ILimiter) Allow(ctx context.Context, key string, limit *redis_rate.Limit) (*redis_rate.Result, error) {
	ret := _m.Called(ctx, key, limit)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 *redis_rate.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *redis_rate.Limit) (*redis_rate.Result, error)); ok {
		return rf(ctx, key, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *redis_rate.Limit) *redis_rate.Result); ok {
		r0 = rf(ctx, key, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis_rate.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *redis_rate.Limit) error); ok {
		r1 = rf(ctx, key, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reset provides a mock function with given fields: ctx, key
func (_m *ILimiter) Reset(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewILimiter creates a new instance of ILimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILimiter {
	mock := &ILimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
