// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IGCPSecretManager is an autogenerated mock type for the IGCPSecretManager type
type IGCPSecretManager struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *IGCPSecretManager) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLatestSecretValueJSON provides a mock function with given fields: ctx, projectId, secretId, secret
func (_m *IGCPSecretManager) GetLatestSecretValueJSON(ctx context.Context, projectId string, secretId string, secret interface{}) (int, error) {
	ret := _m.Called(ctx, projectId, secretId, secret)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSecretValueJSON")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) (int, error)); ok {
		return rf(ctx, projectId, secretId, secret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) int); ok {
		r0 = rf(ctx, projectId, secretId, secret)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, interface{}) error); ok {
		r1 = rf(ctx, projectId, secretId, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSecretValueJSON provides a mock function with given fields: ctx, projectId, secretId, version, secret
func (_m *IGCPSecretManager) GetSecretValueJSON(ctx context.Context, projectId string, secretId string, version int, secret interface{}) error {
	ret := _m.Called(ctx, projectId, secretId, version, secret)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretValueJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, interface{}) error); ok {
		r0 = rf(ctx, projectId, secretId, version, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIGCPSecretManager creates a new instance of IGCPSecretManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGCPSecretManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGCPSecretManager {
	mock := &IGCPSecretManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
